#!/bin/bash
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This script generates certs for testing the magma and cloud VM.

set -e

if [ $# -eq 0 ]
then
  echo "Usage: $0 <output_dir>"
  exit 1
fi

cd $1

echo "#################"
echo "Creating root CA.."
echo "#################"
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 -out rootCA.pem \
       -subj "/C=US/CN=rootca.magma.test"

echo "#################"
echo "Creating bootstrapper key.."
echo "#################"
openssl genrsa -out bootstrapper.key 2048

echo "#################"
echo "Creating controller cert.."
echo "#################"
openssl genrsa -out controller.key 2048
openssl req -new -key controller.key -out controller.csr \
       -subj "/C=US/CN=*.magma.test"
openssl x509 -req -in controller.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out controller.crt -days 36400 -sha256

echo "#################"
echo "Creating certifier CA.."
echo "#################"
openssl genrsa -out certifier.key 2048
openssl req -x509 -new -nodes -key certifier.key -sha256 -days 365000 -out certifier.pem \
       -subj "/C=US/CN=certifier.magma.test"

       