#!/bin/bash
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This script generates certs for testing the magma and cloud VM.

set -e

if [ $# -eq 0 ]
then
  echo "Usage: $0 <output_dir>"
  exit 1
fi

cd "$1"

echo "#################"
echo "Creating VPN CA.."
echo "#################"
openssl genrsa -out vpn_ca.key 2048
openssl req -x509 -new -nodes -key vpn_ca.key -sha256 -days 365000 -out vpn_ca.crt \
       -subj "/C=US/CN=vpn.magma.test"
