// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orc8r/cloud/go/services/metricsd/protos/exporter.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_go "github.com/prometheus/client_model/go"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitMetricsRequest struct {
	Metrics              []*ContextualizedMetric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SubmitMetricsRequest) Reset()         { *m = SubmitMetricsRequest{} }
func (m *SubmitMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitMetricsRequest) ProtoMessage()    {}
func (*SubmitMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{0}
}

func (m *SubmitMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitMetricsRequest.Unmarshal(m, b)
}
func (m *SubmitMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitMetricsRequest.Marshal(b, m, deterministic)
}
func (m *SubmitMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitMetricsRequest.Merge(m, src)
}
func (m *SubmitMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitMetricsRequest.Size(m)
}
func (m *SubmitMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitMetricsRequest proto.InternalMessageInfo

func (m *SubmitMetricsRequest) GetMetrics() []*ContextualizedMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type SubmitMetricsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitMetricsResponse) Reset()         { *m = SubmitMetricsResponse{} }
func (m *SubmitMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitMetricsResponse) ProtoMessage()    {}
func (*SubmitMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{1}
}

func (m *SubmitMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitMetricsResponse.Unmarshal(m, b)
}
func (m *SubmitMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitMetricsResponse.Marshal(b, m, deterministic)
}
func (m *SubmitMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitMetricsResponse.Merge(m, src)
}
func (m *SubmitMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitMetricsResponse.Size(m)
}
func (m *SubmitMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitMetricsResponse proto.InternalMessageInfo

type ContextualizedMetric struct {
	Family               *_go.MetricFamily `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Context              *Context          `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContextualizedMetric) Reset()         { *m = ContextualizedMetric{} }
func (m *ContextualizedMetric) String() string { return proto.CompactTextString(m) }
func (*ContextualizedMetric) ProtoMessage()    {}
func (*ContextualizedMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{2}
}

func (m *ContextualizedMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContextualizedMetric.Unmarshal(m, b)
}
func (m *ContextualizedMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContextualizedMetric.Marshal(b, m, deterministic)
}
func (m *ContextualizedMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContextualizedMetric.Merge(m, src)
}
func (m *ContextualizedMetric) XXX_Size() int {
	return xxx_messageInfo_ContextualizedMetric.Size(m)
}
func (m *ContextualizedMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_ContextualizedMetric.DiscardUnknown(m)
}

var xxx_messageInfo_ContextualizedMetric proto.InternalMessageInfo

func (m *ContextualizedMetric) GetFamily() *_go.MetricFamily {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *ContextualizedMetric) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

// Context provides information to the exporter about a metric's origin.
type Context struct {
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Types that are valid to be assigned to OriginContext:
	//	*Context_CloudMetric
	//	*Context_GatewayMetric
	//	*Context_PushedMetric
	OriginContext        isContext_OriginContext `protobuf_oneof:"OriginContext"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{3}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

type isContext_OriginContext interface {
	isContext_OriginContext()
}

type Context_CloudMetric struct {
	CloudMetric *CloudContext `protobuf:"bytes,2,opt,name=cloud_metric,json=cloudMetric,proto3,oneof"`
}

type Context_GatewayMetric struct {
	GatewayMetric *GatewayContext `protobuf:"bytes,3,opt,name=gateway_metric,json=gatewayMetric,proto3,oneof"`
}

type Context_PushedMetric struct {
	PushedMetric *PushedContext `protobuf:"bytes,4,opt,name=pushed_metric,json=pushedMetric,proto3,oneof"`
}

func (*Context_CloudMetric) isContext_OriginContext() {}

func (*Context_GatewayMetric) isContext_OriginContext() {}

func (*Context_PushedMetric) isContext_OriginContext() {}

func (m *Context) GetOriginContext() isContext_OriginContext {
	if m != nil {
		return m.OriginContext
	}
	return nil
}

func (m *Context) GetCloudMetric() *CloudContext {
	if x, ok := m.GetOriginContext().(*Context_CloudMetric); ok {
		return x.CloudMetric
	}
	return nil
}

func (m *Context) GetGatewayMetric() *GatewayContext {
	if x, ok := m.GetOriginContext().(*Context_GatewayMetric); ok {
		return x.GatewayMetric
	}
	return nil
}

func (m *Context) GetPushedMetric() *PushedContext {
	if x, ok := m.GetOriginContext().(*Context_PushedMetric); ok {
		return x.PushedMetric
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Context) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Context_CloudMetric)(nil),
		(*Context_GatewayMetric)(nil),
		(*Context_PushedMetric)(nil),
	}
}

// CloudContext contains context for metrics scraped from cloud services.
type CloudContext struct {
	CloudHost            string   `protobuf:"bytes,1,opt,name=cloud_host,json=cloudHost,proto3" json:"cloud_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudContext) Reset()         { *m = CloudContext{} }
func (m *CloudContext) String() string { return proto.CompactTextString(m) }
func (*CloudContext) ProtoMessage()    {}
func (*CloudContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{4}
}

func (m *CloudContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudContext.Unmarshal(m, b)
}
func (m *CloudContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudContext.Marshal(b, m, deterministic)
}
func (m *CloudContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudContext.Merge(m, src)
}
func (m *CloudContext) XXX_Size() int {
	return xxx_messageInfo_CloudContext.Size(m)
}
func (m *CloudContext) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudContext.DiscardUnknown(m)
}

var xxx_messageInfo_CloudContext proto.InternalMessageInfo

func (m *CloudContext) GetCloudHost() string {
	if m != nil {
		return m.CloudHost
	}
	return ""
}

// GatewayContext contains context for metrics submitted from gateways.
type GatewayContext struct {
	NetworkId            string   `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	GatewayId            string   `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayContext) Reset()         { *m = GatewayContext{} }
func (m *GatewayContext) String() string { return proto.CompactTextString(m) }
func (*GatewayContext) ProtoMessage()    {}
func (*GatewayContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{5}
}

func (m *GatewayContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayContext.Unmarshal(m, b)
}
func (m *GatewayContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayContext.Marshal(b, m, deterministic)
}
func (m *GatewayContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayContext.Merge(m, src)
}
func (m *GatewayContext) XXX_Size() int {
	return xxx_messageInfo_GatewayContext.Size(m)
}
func (m *GatewayContext) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayContext.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayContext proto.InternalMessageInfo

func (m *GatewayContext) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *GatewayContext) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

// PushedContext contains context for metrics pushed via the REST API.
type PushedContext struct {
	NetworkId            string   `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushedContext) Reset()         { *m = PushedContext{} }
func (m *PushedContext) String() string { return proto.CompactTextString(m) }
func (*PushedContext) ProtoMessage()    {}
func (*PushedContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17e02f1d288e07d, []int{6}
}

func (m *PushedContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushedContext.Unmarshal(m, b)
}
func (m *PushedContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushedContext.Marshal(b, m, deterministic)
}
func (m *PushedContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushedContext.Merge(m, src)
}
func (m *PushedContext) XXX_Size() int {
	return xxx_messageInfo_PushedContext.Size(m)
}
func (m *PushedContext) XXX_DiscardUnknown() {
	xxx_messageInfo_PushedContext.DiscardUnknown(m)
}

var xxx_messageInfo_PushedContext proto.InternalMessageInfo

func (m *PushedContext) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func init() {
	proto.RegisterType((*SubmitMetricsRequest)(nil), "magma.orc8r.metricsd.SubmitMetricsRequest")
	proto.RegisterType((*SubmitMetricsResponse)(nil), "magma.orc8r.metricsd.SubmitMetricsResponse")
	proto.RegisterType((*ContextualizedMetric)(nil), "magma.orc8r.metricsd.ContextualizedMetric")
	proto.RegisterType((*Context)(nil), "magma.orc8r.metricsd.Context")
	proto.RegisterType((*CloudContext)(nil), "magma.orc8r.metricsd.CloudContext")
	proto.RegisterType((*GatewayContext)(nil), "magma.orc8r.metricsd.GatewayContext")
	proto.RegisterType((*PushedContext)(nil), "magma.orc8r.metricsd.PushedContext")
}

func init() {
	proto.RegisterFile("orc8r/cloud/go/services/metricsd/protos/exporter.proto", fileDescriptor_d17e02f1d288e07d)
}

var fileDescriptor_d17e02f1d288e07d = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x6f, 0x6b, 0x13, 0x41,
	0x10, 0xc6, 0x9b, 0x56, 0x12, 0x32, 0xc9, 0xb5, 0xb0, 0x44, 0x0c, 0x85, 0x62, 0x59, 0x7d, 0x51,
	0x94, 0xee, 0x41, 0x04, 0x15, 0x5f, 0xd6, 0x3f, 0x6d, 0x85, 0x56, 0x39, 0xdf, 0x89, 0x10, 0xb6,
	0x77, 0x63, 0xb2, 0x98, 0xbd, 0x8d, 0xbb, 0x7b, 0xfd, 0xe3, 0x57, 0xf0, 0x43, 0xf8, 0x55, 0xe5,
	0x76, 0xe7, 0xac, 0x95, 0xab, 0xcd, 0xab, 0xe4, 0x9e, 0x7b, 0x9e, 0xdf, 0xce, 0xce, 0xcd, 0xc0,
	0x73, 0x63, 0xf3, 0x97, 0x36, 0xcd, 0x17, 0xa6, 0x2a, 0xd2, 0x99, 0x49, 0x1d, 0xda, 0x73, 0x95,
	0xa3, 0x4b, 0x35, 0x7a, 0xab, 0x72, 0x57, 0xa4, 0x4b, 0x6b, 0xbc, 0x71, 0x29, 0x5e, 0x2e, 0x8d,
	0xf5, 0x68, 0x45, 0x78, 0x66, 0x23, 0x2d, 0x67, 0x5a, 0x8a, 0x90, 0x16, 0x8d, 0x77, 0x3b, 0xa1,
	0x7f, 0xd1, 0xc4, 0xbf, 0xc0, 0xe8, 0x53, 0x75, 0xa6, 0x95, 0x3f, 0x89, 0x72, 0x86, 0xdf, 0x2b,
	0x74, 0x9e, 0xbd, 0x81, 0x1e, 0x19, 0xc7, 0x9d, 0xdd, 0x8d, 0xbd, 0xc1, 0xe4, 0x89, 0x68, 0xc3,
	0x89, 0xd7, 0xa6, 0xf4, 0x78, 0xe9, 0x2b, 0xb9, 0x50, 0x3f, 0xb0, 0x88, 0x90, 0xac, 0x89, 0xf2,
	0x07, 0x70, 0xff, 0x1f, 0xba, 0x5b, 0x9a, 0xd2, 0x21, 0xff, 0xd9, 0x81, 0x51, 0x5b, 0x94, 0xbd,
	0x82, 0xee, 0x57, 0xa9, 0xd5, 0xe2, 0x6a, 0xdc, 0xd9, 0xed, 0xec, 0x0d, 0x26, 0x5c, 0x28, 0x53,
	0x97, 0xaa, 0xd1, 0xcf, 0xb1, 0x72, 0x22, 0x5f, 0x28, 0x2c, 0xbd, 0x88, 0xee, 0x77, 0xc1, 0x99,
	0x51, 0x82, 0xbd, 0x80, 0x5e, 0x1e, 0x99, 0xe3, 0xf5, 0x10, 0xde, 0xf9, 0x6f, 0xcd, 0x59, 0xe3,
	0xe6, 0xbf, 0xd6, 0xa1, 0x47, 0x22, 0x7b, 0x08, 0x83, 0x68, 0x9c, 0x96, 0x52, 0x63, 0xa8, 0xa2,
	0x9f, 0x41, 0x94, 0x4e, 0xa5, 0x46, 0x76, 0x08, 0xc3, 0xf0, 0x29, 0xa6, 0x51, 0xa3, 0xa3, 0xf8,
	0x2d, 0x47, 0xd5, 0x4e, 0x42, 0x1f, 0xad, 0x65, 0x83, 0x90, 0xa4, 0xab, 0x9e, 0xc0, 0xe6, 0x4c,
	0x7a, 0xbc, 0x90, 0x57, 0x0d, 0x6a, 0x23, 0xa0, 0x1e, 0xb7, 0xa3, 0x0e, 0xa3, 0xf7, 0x1a, 0x96,
	0x50, 0x9a, 0x70, 0xef, 0x21, 0x59, 0x56, 0x6e, 0x8e, 0x7f, 0x0a, 0xbb, 0x17, 0x68, 0x8f, 0xda,
	0x69, 0x1f, 0x83, 0xf5, 0x1a, 0x36, 0x8c, 0xd9, 0xc8, 0x3a, 0xd8, 0x82, 0xe4, 0x83, 0x55, 0x33,
	0x55, 0x92, 0x81, 0xef, 0xc3, 0xf0, 0xef, 0xab, 0xb0, 0x1d, 0x80, 0xd8, 0x84, 0xb9, 0x71, 0x9e,
	0x9a, 0xd4, 0x0f, 0xca, 0x91, 0x71, 0x9e, 0x9f, 0xc2, 0xe6, 0xcd, 0x72, 0xeb, 0x40, 0x89, 0xfe,
	0xc2, 0xd8, 0x6f, 0x53, 0x55, 0x34, 0x01, 0x52, 0x8e, 0x8b, 0xfa, 0x75, 0xd3, 0x0b, 0x55, 0x84,
	0x96, 0xf6, 0xb3, 0x3e, 0x29, 0xc7, 0x05, 0x17, 0x90, 0xdc, 0x28, 0xf8, 0x0e, 0xdc, 0xe4, 0x1c,
	0xb6, 0x68, 0xe2, 0xde, 0xd2, 0x4e, 0xb0, 0x1c, 0xba, 0x71, 0x14, 0xd9, 0x2d, 0x93, 0xdc, 0xb6,
	0x06, 0xdb, 0x4f, 0x57, 0xf2, 0xd2, 0x50, 0xaf, 0x1d, 0xa4, 0x9f, 0xf7, 0x83, 0x3f, 0x5d, 0x71,
	0x65, 0xcf, 0xba, 0xe1, 0xf7, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xc0, 0x48, 0xf3,
	0xe4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetricsExporterClient is the client API for MetricsExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsExporterClient interface {
	// Submit metrics to datasinks.
	Submit(ctx context.Context, in *SubmitMetricsRequest, opts ...grpc.CallOption) (*SubmitMetricsResponse, error)
}

type metricsExporterClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsExporterClient(cc grpc.ClientConnInterface) MetricsExporterClient {
	return &metricsExporterClient{cc}
}

func (c *metricsExporterClient) Submit(ctx context.Context, in *SubmitMetricsRequest, opts ...grpc.CallOption) (*SubmitMetricsResponse, error) {
	out := new(SubmitMetricsResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.metricsd.MetricsExporter/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsExporterServer is the server API for MetricsExporter service.
type MetricsExporterServer interface {
	// Submit metrics to datasinks.
	Submit(context.Context, *SubmitMetricsRequest) (*SubmitMetricsResponse, error)
}

// UnimplementedMetricsExporterServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsExporterServer struct {
}

func (*UnimplementedMetricsExporterServer) Submit(ctx context.Context, req *SubmitMetricsRequest) (*SubmitMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}

func RegisterMetricsExporterServer(s *grpc.Server, srv MetricsExporterServer) {
	s.RegisterService(&_MetricsExporter_serviceDesc, srv)
}

func _MetricsExporter_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsExporterServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.metricsd.MetricsExporter/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsExporterServer).Submit(ctx, req.(*SubmitMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetricsExporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.orc8r.metricsd.MetricsExporter",
	HandlerType: (*MetricsExporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _MetricsExporter_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orc8r/cloud/go/services/metricsd/protos/exporter.proto",
}
