// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feg/protos/s8_proxy.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "magma/lte/cloud/go/protos/oai"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PDNType int32

const (
	PDNType_UNUSED PDNType = 0
	PDNType_IPV4   PDNType = 1
	PDNType_IPV6   PDNType = 2
	PDNType_IPV4V6 PDNType = 3
	PDNType_NonIP  PDNType = 5
)

var PDNType_name = map[int32]string{
	0: "UNUSED",
	1: "IPV4",
	2: "IPV6",
	3: "IPV4V6",
	5: "NonIP",
}

var PDNType_value = map[string]int32{
	"UNUSED": 0,
	"IPV4":   1,
	"IPV6":   2,
	"IPV4V6": 3,
	"NonIP":  5,
}

func (x PDNType) String() string {
	return proto.EnumName(PDNType_name, int32(x))
}

func (PDNType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{0}
}

// 3GPP TS 29.274  (not all 3gpp create session fields are included)
type CreateSessionRequestPgw struct {
	PgwAddrs                string                   `protobuf:"bytes,1,opt,name=pgwAddrs,proto3" json:"pgwAddrs,omitempty"`
	Imsi                    string                   `protobuf:"bytes,2,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Msisdn                  string                   `protobuf:"bytes,3,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	Mei                     string                   `protobuf:"bytes,4,opt,name=mei,proto3" json:"mei,omitempty"`
	ServingNetwork          *ServingNetwork          `protobuf:"bytes,6,opt,name=serving_network,json=servingNetwork,proto3" json:"serving_network,omitempty"`
	Uli                     *UserLocationInformation `protobuf:"bytes,7,opt,name=uli,proto3" json:"uli,omitempty"`
	RatType                 uint32                   `protobuf:"varint,9,opt,name=rat_type,json=ratType,proto3" json:"rat_type,omitempty"`
	PdnType                 PDNType                  `protobuf:"varint,10,opt,name=pdn_type,json=pdnType,proto3,enum=magma.feg.PDNType" json:"pdn_type,omitempty"`
	Paa                     *PdnAddressAllocation    `protobuf:"bytes,11,opt,name=paa,proto3" json:"paa,omitempty"`
	Apn                     string                   `protobuf:"bytes,14,opt,name=apn,proto3" json:"apn,omitempty"`
	SelectionMode           string                   `protobuf:"bytes,15,opt,name=selection_mode,json=selectionMode,proto3" json:"selection_mode,omitempty"`
	ApnRestriction          uint32                   `protobuf:"varint,16,opt,name=apn_restriction,json=apnRestriction,proto3" json:"apn_restriction,omitempty"`
	Ambr                    *Ambr                    `protobuf:"bytes,17,opt,name=ambr,proto3" json:"ambr,omitempty"`
	BearerContext           *BearerContext           `protobuf:"bytes,20,opt,name=bearer_context,json=bearerContext,proto3" json:"bearer_context,omitempty"`
	IndicationFlag          []byte                   `protobuf:"bytes,21,opt,name=indication_flag,json=indicationFlag,proto3" json:"indication_flag,omitempty"`
	ChargingCharacteristics string                   `protobuf:"bytes,22,opt,name=charging_characteristics,json=chargingCharacteristics,proto3" json:"charging_characteristics,omitempty"`
	TimeZone                *TimeZone                `protobuf:"bytes,23,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *CreateSessionRequestPgw) Reset()         { *m = CreateSessionRequestPgw{} }
func (m *CreateSessionRequestPgw) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequestPgw) ProtoMessage()    {}
func (*CreateSessionRequestPgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{0}
}

func (m *CreateSessionRequestPgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequestPgw.Unmarshal(m, b)
}
func (m *CreateSessionRequestPgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequestPgw.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequestPgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequestPgw.Merge(m, src)
}
func (m *CreateSessionRequestPgw) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequestPgw.Size(m)
}
func (m *CreateSessionRequestPgw) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequestPgw.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequestPgw proto.InternalMessageInfo

func (m *CreateSessionRequestPgw) GetPgwAddrs() string {
	if m != nil {
		return m.PgwAddrs
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetMsisdn() string {
	if m != nil {
		return m.Msisdn
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetMei() string {
	if m != nil {
		return m.Mei
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetServingNetwork() *ServingNetwork {
	if m != nil {
		return m.ServingNetwork
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetUli() *UserLocationInformation {
	if m != nil {
		return m.Uli
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetRatType() uint32 {
	if m != nil {
		return m.RatType
	}
	return 0
}

func (m *CreateSessionRequestPgw) GetPdnType() PDNType {
	if m != nil {
		return m.PdnType
	}
	return PDNType_UNUSED
}

func (m *CreateSessionRequestPgw) GetPaa() *PdnAddressAllocation {
	if m != nil {
		return m.Paa
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetApn() string {
	if m != nil {
		return m.Apn
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetSelectionMode() string {
	if m != nil {
		return m.SelectionMode
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetApnRestriction() uint32 {
	if m != nil {
		return m.ApnRestriction
	}
	return 0
}

func (m *CreateSessionRequestPgw) GetAmbr() *Ambr {
	if m != nil {
		return m.Ambr
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetBearerContext() *BearerContext {
	if m != nil {
		return m.BearerContext
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetIndicationFlag() []byte {
	if m != nil {
		return m.IndicationFlag
	}
	return nil
}

func (m *CreateSessionRequestPgw) GetChargingCharacteristics() string {
	if m != nil {
		return m.ChargingCharacteristics
	}
	return ""
}

func (m *CreateSessionRequestPgw) GetTimeZone() *TimeZone {
	if m != nil {
		return m.TimeZone
	}
	return nil
}

type UserLocationInformation struct {
	Lac                  uint32   `protobuf:"varint,1,opt,name=lac,proto3" json:"lac,omitempty"`
	Ci                   uint32   `protobuf:"varint,2,opt,name=ci,proto3" json:"ci,omitempty"`
	Sac                  uint32   `protobuf:"varint,3,opt,name=sac,proto3" json:"sac,omitempty"`
	Rac                  uint32   `protobuf:"varint,4,opt,name=rac,proto3" json:"rac,omitempty"`
	Tac                  uint32   `protobuf:"varint,5,opt,name=tac,proto3" json:"tac,omitempty"`
	Eci                  uint32   `protobuf:"varint,6,opt,name=eci,proto3" json:"eci,omitempty"`
	MeNbi                uint32   `protobuf:"varint,7,opt,name=MeNbi,proto3" json:"MeNbi,omitempty"`
	EMeNbi               uint32   `protobuf:"varint,8,opt,name=EMeNbi,proto3" json:"EMeNbi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLocationInformation) Reset()         { *m = UserLocationInformation{} }
func (m *UserLocationInformation) String() string { return proto.CompactTextString(m) }
func (*UserLocationInformation) ProtoMessage()    {}
func (*UserLocationInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{1}
}

func (m *UserLocationInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLocationInformation.Unmarshal(m, b)
}
func (m *UserLocationInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLocationInformation.Marshal(b, m, deterministic)
}
func (m *UserLocationInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLocationInformation.Merge(m, src)
}
func (m *UserLocationInformation) XXX_Size() int {
	return xxx_messageInfo_UserLocationInformation.Size(m)
}
func (m *UserLocationInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLocationInformation.DiscardUnknown(m)
}

var xxx_messageInfo_UserLocationInformation proto.InternalMessageInfo

func (m *UserLocationInformation) GetLac() uint32 {
	if m != nil {
		return m.Lac
	}
	return 0
}

func (m *UserLocationInformation) GetCi() uint32 {
	if m != nil {
		return m.Ci
	}
	return 0
}

func (m *UserLocationInformation) GetSac() uint32 {
	if m != nil {
		return m.Sac
	}
	return 0
}

func (m *UserLocationInformation) GetRac() uint32 {
	if m != nil {
		return m.Rac
	}
	return 0
}

func (m *UserLocationInformation) GetTac() uint32 {
	if m != nil {
		return m.Tac
	}
	return 0
}

func (m *UserLocationInformation) GetEci() uint32 {
	if m != nil {
		return m.Eci
	}
	return 0
}

func (m *UserLocationInformation) GetMeNbi() uint32 {
	if m != nil {
		return m.MeNbi
	}
	return 0
}

func (m *UserLocationInformation) GetEMeNbi() uint32 {
	if m != nil {
		return m.EMeNbi
	}
	return 0
}

type ServingNetwork struct {
	Mcc                  string   `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc                  string   `protobuf:"bytes,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServingNetwork) Reset()         { *m = ServingNetwork{} }
func (m *ServingNetwork) String() string { return proto.CompactTextString(m) }
func (*ServingNetwork) ProtoMessage()    {}
func (*ServingNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{2}
}

func (m *ServingNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServingNetwork.Unmarshal(m, b)
}
func (m *ServingNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServingNetwork.Marshal(b, m, deterministic)
}
func (m *ServingNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServingNetwork.Merge(m, src)
}
func (m *ServingNetwork) XXX_Size() int {
	return xxx_messageInfo_ServingNetwork.Size(m)
}
func (m *ServingNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_ServingNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_ServingNetwork proto.InternalMessageInfo

func (m *ServingNetwork) GetMcc() string {
	if m != nil {
		return m.Mcc
	}
	return ""
}

func (m *ServingNetwork) GetMnc() string {
	if m != nil {
		return m.Mnc
	}
	return ""
}

type BearerContext struct {
	Id                   uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserPlaneFteid       *Fteid          `protobuf:"bytes,2,opt,name=user_plane_fteid,json=userPlaneFteid,proto3" json:"user_plane_fteid,omitempty"`
	Qos                  *QosInformation `protobuf:"bytes,4,opt,name=qos,proto3" json:"qos,omitempty"`
	ChargingId           uint32          `protobuf:"varint,5,opt,name=charging_id,json=chargingId,proto3" json:"charging_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BearerContext) Reset()         { *m = BearerContext{} }
func (m *BearerContext) String() string { return proto.CompactTextString(m) }
func (*BearerContext) ProtoMessage()    {}
func (*BearerContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{3}
}

func (m *BearerContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BearerContext.Unmarshal(m, b)
}
func (m *BearerContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BearerContext.Marshal(b, m, deterministic)
}
func (m *BearerContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BearerContext.Merge(m, src)
}
func (m *BearerContext) XXX_Size() int {
	return xxx_messageInfo_BearerContext.Size(m)
}
func (m *BearerContext) XXX_DiscardUnknown() {
	xxx_messageInfo_BearerContext.DiscardUnknown(m)
}

var xxx_messageInfo_BearerContext proto.InternalMessageInfo

func (m *BearerContext) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BearerContext) GetUserPlaneFteid() *Fteid {
	if m != nil {
		return m.UserPlaneFteid
	}
	return nil
}

func (m *BearerContext) GetQos() *QosInformation {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *BearerContext) GetChargingId() uint32 {
	if m != nil {
		return m.ChargingId
	}
	return 0
}

type QosInformation struct {
	Pci                     uint32   `protobuf:"varint,1,opt,name=pci,proto3" json:"pci,omitempty"`
	PriorityLevel           uint32   `protobuf:"varint,2,opt,name=priority_level,json=priorityLevel,proto3" json:"priority_level,omitempty"`
	PreemptionCapability    uint32   `protobuf:"varint,4,opt,name=preemption_capability,json=preemptionCapability,proto3" json:"preemption_capability,omitempty"`
	PreemptionVulnerability uint32   `protobuf:"varint,5,opt,name=preemption_vulnerability,json=preemptionVulnerability,proto3" json:"preemption_vulnerability,omitempty"`
	Qci                     uint32   `protobuf:"varint,6,opt,name=qci,proto3" json:"qci,omitempty"`
	Gbr                     *Ambr    `protobuf:"bytes,7,opt,name=gbr,proto3" json:"gbr,omitempty"`
	Mbr                     *Ambr    `protobuf:"bytes,8,opt,name=mbr,proto3" json:"mbr,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *QosInformation) Reset()         { *m = QosInformation{} }
func (m *QosInformation) String() string { return proto.CompactTextString(m) }
func (*QosInformation) ProtoMessage()    {}
func (*QosInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{4}
}

func (m *QosInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosInformation.Unmarshal(m, b)
}
func (m *QosInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosInformation.Marshal(b, m, deterministic)
}
func (m *QosInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosInformation.Merge(m, src)
}
func (m *QosInformation) XXX_Size() int {
	return xxx_messageInfo_QosInformation.Size(m)
}
func (m *QosInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_QosInformation.DiscardUnknown(m)
}

var xxx_messageInfo_QosInformation proto.InternalMessageInfo

func (m *QosInformation) GetPci() uint32 {
	if m != nil {
		return m.Pci
	}
	return 0
}

func (m *QosInformation) GetPriorityLevel() uint32 {
	if m != nil {
		return m.PriorityLevel
	}
	return 0
}

func (m *QosInformation) GetPreemptionCapability() uint32 {
	if m != nil {
		return m.PreemptionCapability
	}
	return 0
}

func (m *QosInformation) GetPreemptionVulnerability() uint32 {
	if m != nil {
		return m.PreemptionVulnerability
	}
	return 0
}

func (m *QosInformation) GetQci() uint32 {
	if m != nil {
		return m.Qci
	}
	return 0
}

func (m *QosInformation) GetGbr() *Ambr {
	if m != nil {
		return m.Gbr
	}
	return nil
}

func (m *QosInformation) GetMbr() *Ambr {
	if m != nil {
		return m.Mbr
	}
	return nil
}

type Ambr struct {
	BrUl                 uint64   `protobuf:"varint,1,opt,name=br_ul,json=brUl,proto3" json:"br_ul,omitempty"`
	BrDl                 uint64   `protobuf:"varint,2,opt,name=br_dl,json=brDl,proto3" json:"br_dl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ambr) Reset()         { *m = Ambr{} }
func (m *Ambr) String() string { return proto.CompactTextString(m) }
func (*Ambr) ProtoMessage()    {}
func (*Ambr) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{5}
}

func (m *Ambr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ambr.Unmarshal(m, b)
}
func (m *Ambr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ambr.Marshal(b, m, deterministic)
}
func (m *Ambr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ambr.Merge(m, src)
}
func (m *Ambr) XXX_Size() int {
	return xxx_messageInfo_Ambr.Size(m)
}
func (m *Ambr) XXX_DiscardUnknown() {
	xxx_messageInfo_Ambr.DiscardUnknown(m)
}

var xxx_messageInfo_Ambr proto.InternalMessageInfo

func (m *Ambr) GetBrUl() uint64 {
	if m != nil {
		return m.BrUl
	}
	return 0
}

func (m *Ambr) GetBrDl() uint64 {
	if m != nil {
		return m.BrDl
	}
	return 0
}

type PdnAddressAllocation struct {
	Ipv4Address          string   `protobuf:"bytes,1,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address          string   `protobuf:"bytes,2,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Ipv6Prefix           uint32   `protobuf:"varint,3,opt,name=ipv6_prefix,json=ipv6Prefix,proto3" json:"ipv6_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PdnAddressAllocation) Reset()         { *m = PdnAddressAllocation{} }
func (m *PdnAddressAllocation) String() string { return proto.CompactTextString(m) }
func (*PdnAddressAllocation) ProtoMessage()    {}
func (*PdnAddressAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{6}
}

func (m *PdnAddressAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdnAddressAllocation.Unmarshal(m, b)
}
func (m *PdnAddressAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdnAddressAllocation.Marshal(b, m, deterministic)
}
func (m *PdnAddressAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdnAddressAllocation.Merge(m, src)
}
func (m *PdnAddressAllocation) XXX_Size() int {
	return xxx_messageInfo_PdnAddressAllocation.Size(m)
}
func (m *PdnAddressAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_PdnAddressAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_PdnAddressAllocation proto.InternalMessageInfo

func (m *PdnAddressAllocation) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *PdnAddressAllocation) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

func (m *PdnAddressAllocation) GetIpv6Prefix() uint32 {
	if m != nil {
		return m.Ipv6Prefix
	}
	return 0
}

type TimeZone struct {
	DeltaSeconds         int32    `protobuf:"varint,1,opt,name=delta_seconds,json=deltaSeconds,proto3" json:"delta_seconds,omitempty"`
	DaylightSavingTime   uint32   `protobuf:"varint,2,opt,name=daylight_saving_time,json=daylightSavingTime,proto3" json:"daylight_saving_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeZone) Reset()         { *m = TimeZone{} }
func (m *TimeZone) String() string { return proto.CompactTextString(m) }
func (*TimeZone) ProtoMessage()    {}
func (*TimeZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{7}
}

func (m *TimeZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeZone.Unmarshal(m, b)
}
func (m *TimeZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeZone.Marshal(b, m, deterministic)
}
func (m *TimeZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeZone.Merge(m, src)
}
func (m *TimeZone) XXX_Size() int {
	return xxx_messageInfo_TimeZone.Size(m)
}
func (m *TimeZone) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeZone.DiscardUnknown(m)
}

var xxx_messageInfo_TimeZone proto.InternalMessageInfo

func (m *TimeZone) GetDeltaSeconds() int32 {
	if m != nil {
		return m.DeltaSeconds
	}
	return 0
}

func (m *TimeZone) GetDaylightSavingTime() uint32 {
	if m != nil {
		return m.DaylightSavingTime
	}
	return 0
}

type Fteid struct {
	Ipv4Address          string   `protobuf:"bytes,1,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address          string   `protobuf:"bytes,2,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Teid                 uint32   `protobuf:"varint,3,opt,name=teid,proto3" json:"teid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fteid) Reset()         { *m = Fteid{} }
func (m *Fteid) String() string { return proto.CompactTextString(m) }
func (*Fteid) ProtoMessage()    {}
func (*Fteid) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{8}
}

func (m *Fteid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fteid.Unmarshal(m, b)
}
func (m *Fteid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fteid.Marshal(b, m, deterministic)
}
func (m *Fteid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fteid.Merge(m, src)
}
func (m *Fteid) XXX_Size() int {
	return xxx_messageInfo_Fteid.Size(m)
}
func (m *Fteid) XXX_DiscardUnknown() {
	xxx_messageInfo_Fteid.DiscardUnknown(m)
}

var xxx_messageInfo_Fteid proto.InternalMessageInfo

func (m *Fteid) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *Fteid) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

func (m *Fteid) GetTeid() uint32 {
	if m != nil {
		return m.Teid
	}
	return 0
}

type CreateSessionResponsePgw struct {
	SubscriberIp         string         `protobuf:"bytes,3,opt,name=subscriber_ip,json=subscriberIp,proto3" json:"subscriber_ip,omitempty"`
	ApnRestriction       uint32         `protobuf:"varint,4,opt,name=apn_restriction,json=apnRestriction,proto3" json:"apn_restriction,omitempty"`
	BearerContext        *BearerContext `protobuf:"bytes,5,opt,name=bearer_context,json=bearerContext,proto3" json:"bearer_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateSessionResponsePgw) Reset()         { *m = CreateSessionResponsePgw{} }
func (m *CreateSessionResponsePgw) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponsePgw) ProtoMessage()    {}
func (*CreateSessionResponsePgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{9}
}

func (m *CreateSessionResponsePgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponsePgw.Unmarshal(m, b)
}
func (m *CreateSessionResponsePgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponsePgw.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponsePgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponsePgw.Merge(m, src)
}
func (m *CreateSessionResponsePgw) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponsePgw.Size(m)
}
func (m *CreateSessionResponsePgw) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponsePgw.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponsePgw proto.InternalMessageInfo

func (m *CreateSessionResponsePgw) GetSubscriberIp() string {
	if m != nil {
		return m.SubscriberIp
	}
	return ""
}

func (m *CreateSessionResponsePgw) GetApnRestriction() uint32 {
	if m != nil {
		return m.ApnRestriction
	}
	return 0
}

func (m *CreateSessionResponsePgw) GetBearerContext() *BearerContext {
	if m != nil {
		return m.BearerContext
	}
	return nil
}

type ModifyBearerRequestPgw struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	EnbFteid             *Fteid   `protobuf:"bytes,2,opt,name=enb_fteid,json=enbFteid,proto3" json:"enb_fteid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBearerRequestPgw) Reset()         { *m = ModifyBearerRequestPgw{} }
func (m *ModifyBearerRequestPgw) String() string { return proto.CompactTextString(m) }
func (*ModifyBearerRequestPgw) ProtoMessage()    {}
func (*ModifyBearerRequestPgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{10}
}

func (m *ModifyBearerRequestPgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBearerRequestPgw.Unmarshal(m, b)
}
func (m *ModifyBearerRequestPgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBearerRequestPgw.Marshal(b, m, deterministic)
}
func (m *ModifyBearerRequestPgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBearerRequestPgw.Merge(m, src)
}
func (m *ModifyBearerRequestPgw) XXX_Size() int {
	return xxx_messageInfo_ModifyBearerRequestPgw.Size(m)
}
func (m *ModifyBearerRequestPgw) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBearerRequestPgw.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBearerRequestPgw proto.InternalMessageInfo

func (m *ModifyBearerRequestPgw) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func (m *ModifyBearerRequestPgw) GetEnbFteid() *Fteid {
	if m != nil {
		return m.EnbFteid
	}
	return nil
}

type ModifyBearerResponsePgw struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBearerResponsePgw) Reset()         { *m = ModifyBearerResponsePgw{} }
func (m *ModifyBearerResponsePgw) String() string { return proto.CompactTextString(m) }
func (*ModifyBearerResponsePgw) ProtoMessage()    {}
func (*ModifyBearerResponsePgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{11}
}

func (m *ModifyBearerResponsePgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBearerResponsePgw.Unmarshal(m, b)
}
func (m *ModifyBearerResponsePgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBearerResponsePgw.Marshal(b, m, deterministic)
}
func (m *ModifyBearerResponsePgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBearerResponsePgw.Merge(m, src)
}
func (m *ModifyBearerResponsePgw) XXX_Size() int {
	return xxx_messageInfo_ModifyBearerResponsePgw.Size(m)
}
func (m *ModifyBearerResponsePgw) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBearerResponsePgw.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBearerResponsePgw proto.InternalMessageInfo

type DeleteSessionRequestPgw struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequestPgw) Reset()         { *m = DeleteSessionRequestPgw{} }
func (m *DeleteSessionRequestPgw) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequestPgw) ProtoMessage()    {}
func (*DeleteSessionRequestPgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{12}
}

func (m *DeleteSessionRequestPgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequestPgw.Unmarshal(m, b)
}
func (m *DeleteSessionRequestPgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequestPgw.Marshal(b, m, deterministic)
}
func (m *DeleteSessionRequestPgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequestPgw.Merge(m, src)
}
func (m *DeleteSessionRequestPgw) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequestPgw.Size(m)
}
func (m *DeleteSessionRequestPgw) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequestPgw.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequestPgw proto.InternalMessageInfo

func (m *DeleteSessionRequestPgw) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type DeleteSessionResponsePgw struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionResponsePgw) Reset()         { *m = DeleteSessionResponsePgw{} }
func (m *DeleteSessionResponsePgw) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionResponsePgw) ProtoMessage()    {}
func (*DeleteSessionResponsePgw) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{13}
}

func (m *DeleteSessionResponsePgw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionResponsePgw.Unmarshal(m, b)
}
func (m *DeleteSessionResponsePgw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionResponsePgw.Marshal(b, m, deterministic)
}
func (m *DeleteSessionResponsePgw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionResponsePgw.Merge(m, src)
}
func (m *DeleteSessionResponsePgw) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionResponsePgw.Size(m)
}
func (m *DeleteSessionResponsePgw) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionResponsePgw.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionResponsePgw proto.InternalMessageInfo

type EchoRequest struct {
	PgwAddrs             string   `protobuf:"bytes,1,opt,name=pgwAddrs,proto3" json:"pgwAddrs,omitempty"`
	Imsi                 string   `protobuf:"bytes,2,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{14}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetPgwAddrs() string {
	if m != nil {
		return m.PgwAddrs
	}
	return ""
}

func (m *EchoRequest) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type EchoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a775e17ac280154, []int{15}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("magma.feg.PDNType", PDNType_name, PDNType_value)
	proto.RegisterType((*CreateSessionRequestPgw)(nil), "magma.feg.CreateSessionRequestPgw")
	proto.RegisterType((*UserLocationInformation)(nil), "magma.feg.UserLocationInformation")
	proto.RegisterType((*ServingNetwork)(nil), "magma.feg.ServingNetwork")
	proto.RegisterType((*BearerContext)(nil), "magma.feg.BearerContext")
	proto.RegisterType((*QosInformation)(nil), "magma.feg.QosInformation")
	proto.RegisterType((*Ambr)(nil), "magma.feg.Ambr")
	proto.RegisterType((*PdnAddressAllocation)(nil), "magma.feg.PdnAddressAllocation")
	proto.RegisterType((*TimeZone)(nil), "magma.feg.TimeZone")
	proto.RegisterType((*Fteid)(nil), "magma.feg.Fteid")
	proto.RegisterType((*CreateSessionResponsePgw)(nil), "magma.feg.CreateSessionResponsePgw")
	proto.RegisterType((*ModifyBearerRequestPgw)(nil), "magma.feg.ModifyBearerRequestPgw")
	proto.RegisterType((*ModifyBearerResponsePgw)(nil), "magma.feg.ModifyBearerResponsePgw")
	proto.RegisterType((*DeleteSessionRequestPgw)(nil), "magma.feg.DeleteSessionRequestPgw")
	proto.RegisterType((*DeleteSessionResponsePgw)(nil), "magma.feg.DeleteSessionResponsePgw")
	proto.RegisterType((*EchoRequest)(nil), "magma.feg.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "magma.feg.EchoResponse")
}

func init() { proto.RegisterFile("feg/protos/s8_proxy.proto", fileDescriptor_8a775e17ac280154) }

var fileDescriptor_8a775e17ac280154 = []byte{
	// 1205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdb, 0xb6,
	0x17, 0x8f, 0xbf, 0x12, 0xe7, 0x24, 0x72, 0xfc, 0x67, 0xd3, 0x58, 0xc9, 0xff, 0xa2, 0xa9, 0x82,
	0x61, 0xc1, 0x86, 0x26, 0x5d, 0x1a, 0x04, 0xdd, 0x80, 0x62, 0x6b, 0x93, 0x16, 0x08, 0xd0, 0x06,
	0x9e, 0xdc, 0x74, 0x40, 0x76, 0x21, 0x50, 0xd2, 0xb1, 0x4b, 0x4c, 0x22, 0x15, 0x92, 0x4e, 0xeb,
	0x01, 0x7b, 0x88, 0x3d, 0xc6, 0x2e, 0xf7, 0x16, 0x7b, 0x85, 0xbd, 0xcd, 0x40, 0x4a, 0xb6, 0xa5,
	0x26, 0xc6, 0x50, 0x60, 0x57, 0x3a, 0xe7, 0x77, 0x7e, 0xa4, 0xce, 0x27, 0x49, 0xd8, 0x1e, 0xe2,
	0xe8, 0x30, 0x93, 0x42, 0x0b, 0x75, 0xa8, 0x9e, 0x06, 0x99, 0x14, 0x1f, 0x27, 0x07, 0x56, 0x27,
	0xab, 0x29, 0x1d, 0xa5, 0xf4, 0x60, 0x88, 0xa3, 0x1d, 0x2f, 0xd1, 0x38, 0x65, 0x09, 0xca, 0x0e,
	0xd3, 0x14, 0x03, 0x4e, 0x55, 0xa0, 0x34, 0xd5, 0x98, 0xd3, 0xbd, 0xbf, 0x5a, 0xd0, 0x3b, 0x95,
	0x48, 0x35, 0x0e, 0x50, 0x29, 0x26, 0xb8, 0x8f, 0xd7, 0x63, 0x54, 0xba, 0x3f, 0xfa, 0x40, 0x76,
	0xa0, 0x9d, 0x8d, 0x3e, 0x3c, 0x8f, 0x63, 0xa9, 0xdc, 0xda, 0x6e, 0x6d, 0x7f, 0xd5, 0x9f, 0xe9,
	0x84, 0x40, 0x93, 0xa5, 0x8a, 0xb9, 0x75, 0x8b, 0x5b, 0x99, 0x6c, 0xc1, 0x72, 0xaa, 0x98, 0x8a,
	0xb9, 0xdb, 0xb0, 0x68, 0xa1, 0x91, 0x2e, 0x34, 0x52, 0x64, 0x6e, 0xd3, 0x82, 0x46, 0x24, 0x2f,
	0x60, 0x43, 0xa1, 0xbc, 0x61, 0x7c, 0x14, 0x70, 0xd4, 0x1f, 0x84, 0xfc, 0xc5, 0x5d, 0xde, 0xad,
	0xed, 0xaf, 0x1d, 0x6d, 0x1f, 0xcc, 0xdc, 0x3f, 0x18, 0xe4, 0x8c, 0x8b, 0x9c, 0xe0, 0x77, 0x54,
	0x45, 0x27, 0xc7, 0xd0, 0x18, 0x27, 0xcc, 0x5d, 0xb1, 0xeb, 0xbc, 0xd2, 0xba, 0x4b, 0x85, 0xf2,
	0xb5, 0x88, 0xa8, 0x66, 0x82, 0x9f, 0xf3, 0xa1, 0x90, 0xa9, 0x15, 0x7d, 0x43, 0x27, 0xdb, 0xd0,
	0x96, 0x54, 0x07, 0x7a, 0x92, 0xa1, 0xbb, 0xba, 0x5b, 0xdb, 0x77, 0xfc, 0x15, 0x49, 0xf5, 0xdb,
	0x49, 0x86, 0xe4, 0x11, 0xb4, 0xb3, 0x98, 0xe7, 0x26, 0xd8, 0xad, 0xed, 0x77, 0x8e, 0x48, 0x69,
	0xd7, 0xfe, 0xd9, 0x85, 0x61, 0xf9, 0x2b, 0x59, 0xcc, 0x2d, 0xfd, 0x1b, 0x68, 0x64, 0x94, 0xba,
	0x6b, 0xf6, 0xff, 0x0f, 0xca, 0xcc, 0x98, 0x9b, 0x1c, 0xa1, 0x52, 0xcf, 0x93, 0xa4, 0xf0, 0xc3,
	0x37, 0x5c, 0x93, 0x08, 0x9a, 0x71, 0xb7, 0x93, 0x27, 0x82, 0x66, 0x9c, 0x7c, 0x01, 0x1d, 0x85,
	0x09, 0x46, 0x86, 0x13, 0xa4, 0x22, 0x46, 0x77, 0xc3, 0x1a, 0x9d, 0x19, 0xfa, 0x46, 0xc4, 0x48,
	0xbe, 0x84, 0x0d, 0x9a, 0xf1, 0x40, 0xa2, 0xd2, 0x92, 0x59, 0xd8, 0xed, 0x5a, 0xe7, 0x3b, 0x34,
	0xe3, 0xfe, 0x1c, 0x25, 0x7b, 0xd0, 0xa4, 0x69, 0x28, 0xdd, 0xff, 0x59, 0xaf, 0x36, 0x4a, 0x5e,
	0x3d, 0x4f, 0x43, 0xe9, 0x5b, 0x23, 0xf9, 0x1e, 0x3a, 0x21, 0x52, 0x89, 0x32, 0x88, 0x04, 0xd7,
	0xf8, 0x51, 0xbb, 0x9b, 0x96, 0xee, 0x96, 0xe8, 0x2f, 0x2c, 0xe1, 0x34, 0xb7, 0xfb, 0x4e, 0x58,
	0x56, 0x8d, 0x3b, 0x8c, 0xc7, 0x2c, 0x0f, 0x2d, 0x18, 0x26, 0x74, 0xe4, 0xde, 0xdf, 0xad, 0xed,
	0xaf, 0xfb, 0x9d, 0x39, 0xfc, 0x2a, 0xa1, 0x23, 0xf2, 0x2d, 0xb8, 0xd1, 0x7b, 0x2a, 0x47, 0xa6,
	0xd0, 0x46, 0xa0, 0x91, 0x46, 0xc9, 0x94, 0x66, 0x91, 0x72, 0xb7, 0x6c, 0xa0, 0xbd, 0xa9, 0xfd,
	0xb4, 0x6a, 0x26, 0x8f, 0x61, 0x55, 0xb3, 0x14, 0x83, 0x5f, 0x05, 0x47, 0xb7, 0x67, 0xfd, 0xbb,
	0x57, 0xf2, 0xef, 0x2d, 0x4b, 0xf1, 0x4a, 0x70, 0xf4, 0xdb, 0xba, 0x90, 0xbc, 0x3f, 0x6b, 0xd0,
	0x5b, 0x50, 0x7b, 0x93, 0xf9, 0x84, 0x46, 0xb6, 0x8b, 0x1d, 0xdf, 0x88, 0xa4, 0x03, 0xf5, 0x28,
	0x6f, 0x5f, 0xc7, 0xaf, 0x47, 0xcc, 0x30, 0x14, 0x8d, 0x6c, 0xe7, 0x3a, 0xbe, 0x11, 0x0d, 0x22,
	0x69, 0x64, 0xdb, 0xd6, 0xf1, 0x8d, 0x68, 0x10, 0x4d, 0x23, 0xb7, 0x95, 0x23, 0x3a, 0x47, 0x30,
	0x62, 0xb6, 0x79, 0x1d, 0xdf, 0x88, 0x64, 0x13, 0x5a, 0x6f, 0xf0, 0x22, 0xcc, 0x1b, 0xd3, 0xf1,
	0x73, 0xc5, 0x8c, 0xc6, 0xcb, 0x1c, 0x6e, 0x5b, 0xb8, 0xd0, 0xbc, 0x63, 0xe8, 0x54, 0xdb, 0xdc,
	0x0e, 0x4b, 0x14, 0x15, 0xf3, 0x66, 0x44, 0x8b, 0xf0, 0xa8, 0x98, 0x34, 0x23, 0x7a, 0x7f, 0xd4,
	0xc0, 0xa9, 0x14, 0xc8, 0x44, 0xc3, 0xe2, 0x22, 0xbc, 0x3a, 0x8b, 0xc9, 0x77, 0xd0, 0x1d, 0x2b,
	0x94, 0x41, 0x96, 0x50, 0x8e, 0xc1, 0x50, 0x23, 0x8b, 0xed, 0x06, 0x6b, 0x47, 0xdd, 0x52, 0x12,
	0x5f, 0x19, 0xdc, 0xef, 0x18, 0x66, 0xdf, 0x10, 0xad, 0x4e, 0xbe, 0x86, 0xc6, 0xb5, 0x50, 0x36,
	0xee, 0xea, 0x40, 0xfe, 0x28, 0x54, 0x65, 0x9e, 0xae, 0x85, 0x22, 0x0f, 0x60, 0x6d, 0x56, 0x61,
	0x16, 0x17, 0xa9, 0x81, 0x29, 0x74, 0x1e, 0x7b, 0xbf, 0xd7, 0xa1, 0x53, 0x5d, 0x68, 0x02, 0xca,
	0x22, 0x36, 0x2d, 0x46, 0x16, 0x31, 0x33, 0x06, 0x99, 0x64, 0x42, 0x32, 0x3d, 0x09, 0x12, 0xbc,
	0xc1, 0xa4, 0x28, 0x8c, 0x33, 0x45, 0x5f, 0x1b, 0x90, 0x3c, 0x81, 0xfb, 0x99, 0x44, 0x4c, 0x33,
	0xdb, 0x77, 0x11, 0xcd, 0x68, 0xc8, 0x12, 0xa6, 0x27, 0x45, 0x8d, 0x36, 0xe7, 0xc6, 0xd3, 0x99,
	0xcd, 0xf4, 0x60, 0x69, 0xd1, 0xcd, 0x38, 0xe1, 0x28, 0xa7, 0xeb, 0x72, 0x77, 0x7b, 0x73, 0xfb,
	0xbb, 0xb2, 0xd9, 0x38, 0x7a, 0x3d, 0xaf, 0xee, 0x75, 0xc4, 0xc8, 0x43, 0x68, 0x8c, 0x42, 0x59,
	0x1c, 0x3a, 0xb7, 0xc6, 0xcb, 0xd8, 0x0c, 0xc5, 0x4c, 0x60, 0x7b, 0x01, 0x25, 0x0d, 0xa5, 0xf7,
	0x18, 0x9a, 0x46, 0x21, 0xf7, 0xa0, 0x15, 0xca, 0x60, 0x9c, 0xd8, 0x54, 0x34, 0xfd, 0x66, 0x28,
	0x2f, 0x93, 0x02, 0x8c, 0xf3, 0x14, 0x58, 0xf0, 0x2c, 0xf1, 0x7e, 0x83, 0xcd, 0xbb, 0x8e, 0x15,
	0xf2, 0x10, 0xd6, 0x59, 0x76, 0x73, 0x1c, 0xd0, 0xdc, 0x52, 0xb4, 0xcd, 0x9a, 0xc1, 0x0a, 0x72,
	0x41, 0x39, 0x99, 0x51, 0xea, 0x33, 0xca, 0xc9, 0x94, 0xf2, 0x00, 0xac, 0x1a, 0x64, 0x12, 0x87,
	0xec, 0x63, 0x31, 0x03, 0x60, 0xa0, 0xbe, 0x45, 0x3c, 0x0a, 0xed, 0xe9, 0xc0, 0x91, 0x3d, 0x70,
	0x62, 0x4c, 0x34, 0x0d, 0x14, 0x46, 0x82, 0xc7, 0xf9, 0x3f, 0x5b, 0xfe, 0xba, 0x05, 0x07, 0x39,
	0x46, 0x1e, 0xc3, 0x66, 0x4c, 0x27, 0x09, 0x1b, 0xbd, 0xd7, 0x81, 0xa2, 0xf6, 0xa0, 0x37, 0x73,
	0x5a, 0x94, 0x95, 0x4c, 0x6d, 0x03, 0x6b, 0x32, 0x5b, 0x7b, 0x14, 0x5a, 0x79, 0xfb, 0xfd, 0x37,
	0x21, 0x11, 0x68, 0xda, 0xa6, 0xcf, 0x63, 0xb1, 0xb2, 0x19, 0x1b, 0xf7, 0x93, 0xbb, 0x4e, 0x65,
	0x82, 0x2b, 0x34, 0x97, 0xdd, 0x1e, 0x38, 0x6a, 0x1c, 0xaa, 0x48, 0xb2, 0x10, 0x65, 0xc0, 0xb2,
	0xe2, 0x0e, 0x5b, 0x9f, 0x83, 0xe7, 0xd9, 0x5d, 0xe7, 0x70, 0xf3, 0xce, 0x73, 0xf8, 0xf6, 0x11,
	0xdb, 0xfa, 0xac, 0x23, 0xd6, 0xfb, 0x19, 0xb6, 0xde, 0x88, 0x98, 0x0d, 0x27, 0x39, 0xab, 0x74,
	0x2b, 0x4f, 0x6f, 0xde, 0x5a, 0xe9, 0xe6, 0x7d, 0x04, 0xab, 0xc8, 0xc3, 0x7f, 0x99, 0xf3, 0x36,
	0xf2, 0xd0, 0x4a, 0xde, 0x36, 0xf4, 0xaa, 0x9b, 0xcf, 0xd2, 0xe0, 0x3d, 0x82, 0xde, 0x19, 0x26,
	0x78, 0xd7, 0x73, 0xe0, 0x8e, 0x1f, 0x7b, 0x3b, 0xe0, 0x7e, 0x42, 0x9f, 0x6f, 0xf5, 0x0c, 0xd6,
	0x5e, 0x46, 0xef, 0x45, 0xb1, 0xc3, 0xe7, 0xbe, 0x26, 0xbc, 0x0e, 0xac, 0xe7, 0xcb, 0xf3, 0x1d,
	0xbf, 0xfa, 0x01, 0x56, 0x8a, 0x3b, 0x98, 0x00, 0x2c, 0x5f, 0x5e, 0x5c, 0x0e, 0x5e, 0x9e, 0x75,
	0x97, 0x48, 0x1b, 0x9a, 0xe7, 0xfd, 0x77, 0xc7, 0xdd, 0x5a, 0x21, 0x9d, 0x74, 0xeb, 0xc6, 0x6e,
	0xb0, 0x77, 0x27, 0xdd, 0x06, 0x59, 0x85, 0xd6, 0x85, 0xe0, 0xe7, 0xfd, 0x6e, 0xeb, 0xe8, 0xef,
	0x3a, 0xac, 0x0c, 0x9e, 0xf6, 0xcd, 0x63, 0x89, 0x5c, 0x81, 0x53, 0x69, 0x05, 0x52, 0x7e, 0x41,
	0x2c, 0x78, 0x10, 0xed, 0xec, 0x2d, 0xe6, 0xcc, 0xc3, 0x5e, 0x22, 0x3f, 0xc1, 0x7a, 0x39, 0xbd,
	0xe4, 0x61, 0x69, 0xd9, 0xdd, 0x45, 0xdd, 0xf1, 0x16, 0x52, 0xca, 0x1b, 0x5f, 0x81, 0x53, 0xc9,
	0x76, 0xc5, 0xe9, 0x05, 0x65, 0xab, 0x38, 0xbd, 0xb0, 0x56, 0x4b, 0xe4, 0x19, 0xb4, 0x07, 0xc8,
	0x63, 0x93, 0x72, 0xb2, 0x55, 0x5a, 0x52, 0x2a, 0xe1, 0x4e, 0xef, 0x16, 0x9e, 0xef, 0xe0, 0x2d,
	0xbd, 0xf8, 0xff, 0xd5, 0xb6, 0xb5, 0x1d, 0x9a, 0x97, 0x69, 0x94, 0x88, 0x71, 0x7c, 0x38, 0x12,
	0xc5, 0xe3, 0x33, 0x5c, 0xb6, 0xdf, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xd7, 0x1b,
	0x0d, 0xb7, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// S8ProxyClient is the client API for S8Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type S8ProxyClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequestPgw, opts ...grpc.CallOption) (*CreateSessionResponsePgw, error)
	ModifyBearer(ctx context.Context, in *ModifyBearerRequestPgw, opts ...grpc.CallOption) (*ModifyBearerResponsePgw, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequestPgw, opts ...grpc.CallOption) (*DeleteSessionResponsePgw, error)
	SendEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type s8ProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewS8ProxyClient(cc grpc.ClientConnInterface) S8ProxyClient {
	return &s8ProxyClient{cc}
}

func (c *s8ProxyClient) CreateSession(ctx context.Context, in *CreateSessionRequestPgw, opts ...grpc.CallOption) (*CreateSessionResponsePgw, error) {
	out := new(CreateSessionResponsePgw)
	err := c.cc.Invoke(ctx, "/magma.feg.S8Proxy/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s8ProxyClient) ModifyBearer(ctx context.Context, in *ModifyBearerRequestPgw, opts ...grpc.CallOption) (*ModifyBearerResponsePgw, error) {
	out := new(ModifyBearerResponsePgw)
	err := c.cc.Invoke(ctx, "/magma.feg.S8Proxy/ModifyBearer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s8ProxyClient) DeleteSession(ctx context.Context, in *DeleteSessionRequestPgw, opts ...grpc.CallOption) (*DeleteSessionResponsePgw, error) {
	out := new(DeleteSessionResponsePgw)
	err := c.cc.Invoke(ctx, "/magma.feg.S8Proxy/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s8ProxyClient) SendEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/magma.feg.S8Proxy/SendEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S8ProxyServer is the server API for S8Proxy service.
type S8ProxyServer interface {
	CreateSession(context.Context, *CreateSessionRequestPgw) (*CreateSessionResponsePgw, error)
	ModifyBearer(context.Context, *ModifyBearerRequestPgw) (*ModifyBearerResponsePgw, error)
	DeleteSession(context.Context, *DeleteSessionRequestPgw) (*DeleteSessionResponsePgw, error)
	SendEcho(context.Context, *EchoRequest) (*EchoResponse, error)
}

// UnimplementedS8ProxyServer can be embedded to have forward compatible implementations.
type UnimplementedS8ProxyServer struct {
}

func (*UnimplementedS8ProxyServer) CreateSession(ctx context.Context, req *CreateSessionRequestPgw) (*CreateSessionResponsePgw, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (*UnimplementedS8ProxyServer) ModifyBearer(ctx context.Context, req *ModifyBearerRequestPgw) (*ModifyBearerResponsePgw, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyBearer not implemented")
}
func (*UnimplementedS8ProxyServer) DeleteSession(ctx context.Context, req *DeleteSessionRequestPgw) (*DeleteSessionResponsePgw, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (*UnimplementedS8ProxyServer) SendEcho(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEcho not implemented")
}

func RegisterS8ProxyServer(s *grpc.Server, srv S8ProxyServer) {
	s.RegisterService(&_S8Proxy_serviceDesc, srv)
}

func _S8Proxy_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequestPgw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S8ProxyServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.feg.S8Proxy/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S8ProxyServer).CreateSession(ctx, req.(*CreateSessionRequestPgw))
	}
	return interceptor(ctx, in, info, handler)
}

func _S8Proxy_ModifyBearer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyBearerRequestPgw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S8ProxyServer).ModifyBearer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.feg.S8Proxy/ModifyBearer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S8ProxyServer).ModifyBearer(ctx, req.(*ModifyBearerRequestPgw))
	}
	return interceptor(ctx, in, info, handler)
}

func _S8Proxy_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequestPgw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S8ProxyServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.feg.S8Proxy/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S8ProxyServer).DeleteSession(ctx, req.(*DeleteSessionRequestPgw))
	}
	return interceptor(ctx, in, info, handler)
}

func _S8Proxy_SendEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S8ProxyServer).SendEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.feg.S8Proxy/SendEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S8ProxyServer).SendEcho(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _S8Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.feg.S8Proxy",
	HandlerType: (*S8ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _S8Proxy_CreateSession_Handler,
		},
		{
			MethodName: "ModifyBearer",
			Handler:    _S8Proxy_ModifyBearer_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _S8Proxy_DeleteSession_Handler,
		},
		{
			MethodName: "SendEcho",
			Handler:    _S8Proxy_SendEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feg/protos/s8_proxy.proto",
}
