{
 "title": "Orchestrator",
 "description": "Overview of Orchestrator Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus Cache Utilization",
   "type": "graph",
   "description": "Percent of the available cache limit that is being used. Will start dropping metrics if it approaches too close to 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(cache_size[2m]) / avg_over_time(cache_limit[2m]) * 100"
    }
   ]
  },
  {
   "title": "Service Memory Usage",
   "type": "graph",
   "description": "Average memory usage of each magma service (avearged over controller instances)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes) by (service)"
    }
   ]
  },
  {
   "title": "Targets Up",
   "type": "graph",
   "description": "1 if prometheus scrape target returned metrics successfully at last scrape, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Get Metrics Status",
   "type": "graph",
   "description": "Number of services successfully submitting metrics on each controller instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(get_metrics_status) by (gatewayID)"
    }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "graph",
   "description": "Number of samples retrieved during each scrape event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(scrape_samples_scraped[2m])\n"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Time",
   "type": "graph",
   "description": "Time it takes for prometheus to perform a scrape operation. Metrics performance will degrade if scrapes timeout (usually 10 seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds\n" }
   ]
  },
  {
   "title": "Prometheus Query Time",
   "type": "graph",
   "description": "Duration of prometheus queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds) by (quantile)"
    }
   ]
  },
  {
   "title": "Controller Disk Usage",
   "type": "graph",
   "description": "Percent of disk space used by each controller instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(disk_used / disk_total) * 100\n\n"
    }
   ]
  }
 ]
}