cc_library(
	name = "diameter_codes",
	srcs = ["DiameterCodes.cpp"],
	hdrs = ["DiameterCodes.h"],
)
cc_library(
	name = "utilities",
	srcs = ["Utilities.cpp"],
	hdrs = ["Utilities.h"],
)
cc_library(
	name = "session_id",
	srcs = ["SessionID.cpp"],
	hdrs = ["SessionID.h"],
)