#!/bin/sh
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Delete OVS bridge on boot
sed -i "s/.*OVS_CTL_OPTS.*/OVS_CTL_OPTS='--delete-bridges'/" /etc/default/openvswitch-switch

# Create /var/core directory
mkdir -p /var/core

# Set magmad service to start on boot
systemctl enable -f magma@magmad.service

# Installation of the redis-server Debian package has a post-install
# script that starts a redis-server process. We kill and disable this
# process, allowing us to manage the process using magmad and our own
# systemd files.
systemctl stop redis-server
systemctl disable redis-server

# Dnsmasq also starts up post-install.
systemctl stop dnsmasq
systemctl disable dnsmasq

# Lighttpd also starts up post-install.
systemctl stop lighttpd
systemctl disable lighttpd

# Restart rsyslog to pick up fluent-bit config, create fluent-bit DB directory
systemctl restart rsyslog
mkdir -p /var/opt/magma/fluent-bit

# Restart all services on package install
if [ -f /var/run/sctpd.version ]; then
    /usr/bin/env python3 -c 'from distutils.version import LooseVersion; import sys; ver = lambda n: LooseVersion(open(n).read()); sys.exit(1) if ver("/var/run/sctpd.version") < ver("/usr/local/share/magma/sctpd_min_version") else sys.exit(0)' || systemctl restart sctpd
else
    killall -9 sctpd || true
fi
systemctl restart magma@* || true
