FROM node:12.5.0-alpine

# Install dependencies required by some node modules
RUN apk add --no-cache curl python g++ make libx11 glew-dev libxi-dev

# Create app directory
WORKDIR /app

# Copy package dependencies
COPY package.json yarn.lock babel.config.js ./
COPY fbcnms-projects/inventory/package.json fbcnms-projects/inventory/
COPY fbcnms-projects/magmalte/package.json fbcnms-projects/magmalte/

# Install shared dependencies
COPY fbcnms-packages fbcnms-packages
RUN yarn install --frozen-lockfile && yarn cache clean

# Copy app source
WORKDIR /app/fbcnms-projects/inventory
COPY fbcnms-projects/inventory .
COPY fbcnms-projects/magmalte /app/fbcnms-projects/magmalte

# Start app
CMD yarn dev
