#!/bin/bash
set -e

dir=$1
shift
pkg=$1
shift

bi_start=$(date +%s)

(
  cd "$dir"

  docker_registry=${SYMPHONY_DOCKER_REGISTRY:="facebookconnectivity-southpoll-dev-docker.jfrog.io"}
  tag="${docker_registry}/${pkg}"

  [[ -f "${pkg}/deps" ]]    && deps=$(cat ${pkg}/deps)         || deps=""
  [[ -f "${pkg}/url" ]]     && url="$(cat ${pkg}/url)"         || url="."
  [[ -f "${pkg}/version" ]] && version="$(cat ${pkg}/version)" || version="."
  [[ -f "${pkg}/context" ]] && context="$(cat ${pkg}/context)" || context="."

  install="apt-get -qq -y update \&\& apt-get -qq -y install "

  sed -E -e "s!%%PKG%%!${pkg}!g" \
         -e "s!%%DEPS%%!${deps//$'\n'/ }!g" \
         -e "s!%%URL%%!${url}!g" \
         -e "s!%%INSTALL%%!${install}!g" \
         -e "s!%%VERSION%%!${version}!g" \
         -e "s!%%DOCKER_REGISTRY%%!${docker_registry}!g" \
         "${pkg}/Dockerfile" \
           | docker build -f - --tag "${tag}" "${context}" "$@"
)

bi_end=$(date +%s)
runtime=$((bi_end-bi_start))
echo "The image (${pkg}) script took ${runtime} seconds to run."
