#!/bin/bash
set -e

tp_start=$(date +%s)

for pkg in thirdparty/*; do
  # shellcheck source=/dev/null
  . scripts/build_image thirdparty "$(basename "${pkg}")"
done

# shellcheck source=/dev/null
. scripts/build_thirdparty_image

tp_end=$(date +%s)
runtime=$((tp_end-tp_start))
echo "The thirdparty script took ${runtime} seconds to run."
