#!/bin/bash
set -e

ch_start=$(date +%s)

# shellcheck source=/dev/null
. scripts/build_cached_thirdparty
# shellcheck source=/dev/null
. scripts/build_cached_firstparty

ch_end=$(date +%s)
runtime=$((ch_end-ch_start))
echo "The script took ${runtime} seconds to run."
