#!/bin/bash
set -e

fp_start=$(date +%s)

# shellcheck source=/dev/null
. scripts/build_image firstparty magma
# shellcheck source=/dev/null
. scripts/build_image firstparty firstparty

fp_end=$(date +%s)
runtime=$((fp_end-fp_start))
echo "The firstparty script took ${runtime} seconds to run."
