#!/bin/bash
set -e

# boslab snowflake faceb00c-face-b00c-face-fbb05fbcface"
case $(uname -a) in
*Darwin*)
  uid=$(system_profiler SPHardwareDataType | \
    awk '/Hardware UUID: / {print tolower($3)}'| tail -c 13)
  ;;
*fedora*)
  for eth in /sys/class/net/enp*s*/address ; do
    uid="$(sed 's/://g' "${eth}")"
    break
  done
  ;;
*)
  # I don't know how to generate a unique id for your system so using default
  uid="0bad0badbeef"
  ;;
esac
echo "faceb00c-face-b00c-face-${uid}"
