#!/bin/bash

CACHE_DIR=${SYMPHONY_AGENT_CACHE_DIR:-$(realpath ~)/cache_devmand_build}
docker run \
  -v "$(realpath ../):/cache/devmand/repo:ro" \
  -v "$CACHE_DIR:/cache/devmand/build:rw" \
  devmand-built \
  make test
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ] ; then
  echo "You have gotten a CI failure in devmand's unit tests."
  echo "If you are sure your changes did not cause the issue or if you"
  echo "need help please reach out to the south poll symphony oncall."
  exit ${EXIT_CODE}
fi
