{
 "title": "test",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Select tenant",
    "query": "label_values(conductor_workflow_count, tenant)"
   },
   {
    "name": "workflow",
    "label": "Select workflow",
    "query": "label_values(conductor_workflow_count{tenant=~\"${tenant}\"}, workflow)"
   }
  ]
 },
 "panels": [
  {
   "title": "Matched tenants",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (tenant)(conductor_workflow_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total executions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(conductor_workflow_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"})",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Matched tenants",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (tenant)(conductor_workflow_failure_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "sum(conductor_workflow_failure_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"})",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Per workflow executions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "conductor_workflow_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Per workflow failures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "conductor_workflow_failure_count{tenant=~\"${tenant}\", workflow=~\"${workflow}\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Mean workflow execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "conductor_workflow_mean_duration{tenant=~\"${tenant}\", workflow=~\"${workflow}\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Max workflow execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "conductor_workflow_max_duration{tenant=~\"${tenant}\", workflow=~\"${workflow}\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Task poll count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "conductor_taskType_poll_count", "legendFormat": "{{taskType}}" }
   ]
  },
  {
   "title": "Task mean poll frequency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Polling frequency" }
   ],
   "targets": [
    {
     "expr": "conductor_taskType_mean_poll_frequency",
     "legendFormat": "{{taskType}}"
    }
   ]
  }
 ]
}