// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/eap_auth.proto

package protos // import "magma/feg/gateway/services/eap/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EapType int32

const (
	// Mandatory EAP Method types
	EapType_Reserved      EapType = 0
	EapType_Identity      EapType = 1
	EapType_Notification  EapType = 2
	EapType_Legacy_Nak    EapType = 3
	EapType_MD5_Challenge EapType = 4
	EapType_Expanded      EapType = 254
	EapType_Experimental  EapType = 255
	// EAP Method Authenticator types
	EapType_TLS      EapType = 13
	EapType_SIM      EapType = 18
	EapType_AKA      EapType = 23
	EapType_AKAPrime EapType = 50
)

var EapType_name = map[int32]string{
	0:   "Reserved",
	1:   "Identity",
	2:   "Notification",
	3:   "Legacy_Nak",
	4:   "MD5_Challenge",
	254: "Expanded",
	255: "Experimental",
	13:  "TLS",
	18:  "SIM",
	23:  "AKA",
	50:  "AKAPrime",
}
var EapType_value = map[string]int32{
	"Reserved":      0,
	"Identity":      1,
	"Notification":  2,
	"Legacy_Nak":    3,
	"MD5_Challenge": 4,
	"Expanded":      254,
	"Experimental":  255,
	"TLS":           13,
	"SIM":           18,
	"AKA":           23,
	"AKAPrime":      50,
}

func (x EapType) String() string {
	return proto.EnumName(EapType_name, int32(x))
}
func (EapType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eap_auth_f956189136c1ef81, []int{0}
}

type EapCode int32

const (
	EapCode_Undefined EapCode = 0
	EapCode_Request   EapCode = 1
	EapCode_Response  EapCode = 2
	EapCode_Success   EapCode = 3
	EapCode_Failure   EapCode = 4
)

var EapCode_name = map[int32]string{
	0: "Undefined",
	1: "Request",
	2: "Response",
	3: "Success",
	4: "Failure",
}
var EapCode_value = map[string]int32{
	"Undefined": 0,
	"Request":   1,
	"Response":  2,
	"Success":   3,
	"Failure":   4,
}

func (x EapCode) String() string {
	return proto.EnumName(EapCode_name, int32(x))
}
func (EapCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eap_auth_f956189136c1ef81, []int{1}
}

type EapContext struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Msk                  []byte   `protobuf:"bytes,2,opt,name=msk,proto3" json:"msk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EapContext) Reset()         { *m = EapContext{} }
func (m *EapContext) String() string { return proto.CompactTextString(m) }
func (*EapContext) ProtoMessage()    {}
func (*EapContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_eap_auth_f956189136c1ef81, []int{0}
}
func (m *EapContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EapContext.Unmarshal(m, b)
}
func (m *EapContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EapContext.Marshal(b, m, deterministic)
}
func (dst *EapContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EapContext.Merge(dst, src)
}
func (m *EapContext) XXX_Size() int {
	return xxx_messageInfo_EapContext.Size(m)
}
func (m *EapContext) XXX_DiscardUnknown() {
	xxx_messageInfo_EapContext.DiscardUnknown(m)
}

var xxx_messageInfo_EapContext proto.InternalMessageInfo

func (m *EapContext) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *EapContext) GetMsk() []byte {
	if m != nil {
		return m.Msk
	}
	return nil
}

type Eap struct {
	Payload              []byte      `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Ctx                  *EapContext `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Eap) Reset()         { *m = Eap{} }
func (m *Eap) String() string { return proto.CompactTextString(m) }
func (*Eap) ProtoMessage()    {}
func (*Eap) Descriptor() ([]byte, []int) {
	return fileDescriptor_eap_auth_f956189136c1ef81, []int{1}
}
func (m *Eap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eap.Unmarshal(m, b)
}
func (m *Eap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eap.Marshal(b, m, deterministic)
}
func (dst *Eap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eap.Merge(dst, src)
}
func (m *Eap) XXX_Size() int {
	return xxx_messageInfo_Eap.Size(m)
}
func (m *Eap) XXX_DiscardUnknown() {
	xxx_messageInfo_Eap.DiscardUnknown(m)
}

var xxx_messageInfo_Eap proto.InternalMessageInfo

func (m *Eap) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Eap) GetCtx() *EapContext {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func init() {
	proto.RegisterType((*EapContext)(nil), "eap.eap_context")
	proto.RegisterType((*Eap)(nil), "eap.eap")
	proto.RegisterEnum("eap.EapType", EapType_name, EapType_value)
	proto.RegisterEnum("eap.EapCode", EapCode_name, EapCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EapServiceClient is the client API for EapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EapServiceClient interface {
	Handle(ctx context.Context, in *Eap, opts ...grpc.CallOption) (*Eap, error)
}

type eapServiceClient struct {
	cc *grpc.ClientConn
}

func NewEapServiceClient(cc *grpc.ClientConn) EapServiceClient {
	return &eapServiceClient{cc}
}

func (c *eapServiceClient) Handle(ctx context.Context, in *Eap, opts ...grpc.CallOption) (*Eap, error) {
	out := new(Eap)
	err := c.cc.Invoke(ctx, "/eap.eap_service/handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EapServiceServer is the server API for EapService service.
type EapServiceServer interface {
	Handle(context.Context, *Eap) (*Eap, error)
}

func RegisterEapServiceServer(s *grpc.Server, srv EapServiceServer) {
	s.RegisterService(&_EapService_serviceDesc, srv)
}

func _EapService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Eap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EapServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eap.eap_service/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EapServiceServer).Handle(ctx, req.(*Eap))
	}
	return interceptor(ctx, in, info, handler)
}

var _EapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eap.eap_service",
	HandlerType: (*EapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "handle",
			Handler:    _EapService_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/eap_auth.proto",
}

func init() { proto.RegisterFile("protos/eap_auth.proto", fileDescriptor_eap_auth_f956189136c1ef81) }

var fileDescriptor_eap_auth_f956189136c1ef81 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0xed, 0x66, 0x4b, 0x93, 0xdc, 0x6c, 0xe4, 0x76, 0x40, 0x0c, 0x82, 0x52, 0x02, 0x62, 0x29,
	0x98, 0x85, 0x88, 0xaf, 0x42, 0xac, 0x15, 0x42, 0xdb, 0x20, 0x1b, 0x7d, 0xf1, 0x25, 0x5c, 0x67,
	0x6e, 0x36, 0x43, 0x37, 0x33, 0x63, 0x66, 0xa2, 0xd9, 0x3f, 0xe4, 0xcf, 0x54, 0x99, 0x4d, 0x22,
	0x7d, 0x9a, 0x73, 0xce, 0x9d, 0x73, 0x3f, 0xe1, 0xa9, 0xdb, 0xd8, 0x60, 0x7d, 0xce, 0xe4, 0x16,
	0xb4, 0x0d, 0xab, 0x51, 0xc3, 0x45, 0xca, 0xe4, 0x86, 0xef, 0xa1, 0x17, 0x65, 0x69, 0x4d, 0xe0,
	0x5d, 0x10, 0x2f, 0x00, 0x3c, 0x7b, 0xaf, 0xad, 0x59, 0x68, 0x35, 0x48, 0x2e, 0x92, 0xcb, 0x6e,
	0xd1, 0x3d, 0x28, 0x53, 0x25, 0x10, 0xd2, 0xb5, 0x7f, 0x18, 0xb4, 0x2e, 0x92, 0xcb, 0xac, 0x88,
	0x70, 0x78, 0x0d, 0x31, 0x8d, 0x18, 0x40, 0xdb, 0x51, 0x5d, 0x59, 0xda, 0x9b, 0xb2, 0xe2, 0x48,
	0xc5, 0x10, 0x52, 0x19, 0x76, 0x8d, 0xa5, 0x37, 0xc6, 0x11, 0x93, 0x1b, 0x3d, 0x2a, 0x58, 0xc4,
	0xe0, 0xd5, 0xef, 0x04, 0x3a, 0x51, 0x0c, 0xb5, 0x63, 0x91, 0x41, 0xa7, 0x60, 0xcf, 0x9b, 0x9f,
	0xac, 0xf0, 0x24, 0xb2, 0xa9, 0x62, 0x13, 0x74, 0xa8, 0x31, 0x11, 0x08, 0xd9, 0xcc, 0x06, 0xbd,
	0xd4, 0x92, 0x82, 0xb6, 0x06, 0x5b, 0xe2, 0x09, 0xc0, 0x1d, 0x97, 0x24, 0xeb, 0xc5, 0x8c, 0x1e,
	0x30, 0x15, 0xe7, 0xd0, 0xbf, 0xff, 0xf8, 0x6e, 0x71, 0xbd, 0xa2, 0xaa, 0x62, 0x53, 0x32, 0x9e,
	0x8a, 0x3e, 0x74, 0x6e, 0x76, 0x8e, 0x8c, 0x62, 0x85, 0x7f, 0x12, 0x71, 0x0e, 0xd9, 0xcd, 0xce,
	0xf1, 0x46, 0xaf, 0xd9, 0x04, 0xaa, 0xf0, 0x6f, 0x22, 0xda, 0x90, 0x7e, 0xb9, 0x9b, 0x63, 0x3f,
	0x82, 0xf9, 0xf4, 0x1e, 0x45, 0x04, 0x93, 0xdb, 0x09, 0x3e, 0x8b, 0xf5, 0x27, 0xb7, 0x93, 0xcf,
	0xf1, 0x37, 0x8e, 0xaf, 0x66, 0xfb, 0x3e, 0xa5, 0x55, 0x2c, 0xfa, 0xd0, 0xfd, 0x6a, 0x14, 0x2f,
	0xb5, 0x69, 0x1a, 0xed, 0x41, 0xbb, 0xe0, 0x1f, 0x5b, 0xf6, 0x01, 0x93, 0xc3, 0x0c, 0xce, 0x1a,
	0xcf, 0xd8, 0x8a, 0xa1, 0xf9, 0x56, 0x4a, 0xf6, 0x1e, 0xd3, 0x48, 0x3e, 0x91, 0xae, 0xb6, 0x1b,
	0xc6, 0xd3, 0xf1, 0x9b, 0xfd, 0xf6, 0xe3, 0xb4, 0x5a, 0xb2, 0x78, 0x09, 0x67, 0x2b, 0x32, 0xaa,
	0x62, 0xd1, 0x39, 0x2e, 0xea, 0xf9, 0x7f, 0x34, 0x3c, 0xf9, 0xf0, 0xfa, 0xdb, 0xab, 0x35, 0x95,
	0x6b, 0xca, 0x97, 0x5c, 0xe6, 0x25, 0x05, 0xfe, 0x45, 0x75, 0x7e, 0x30, 0x37, 0xe7, 0xcd, 0xf7,
	0x97, 0xfe, 0x7e, 0xd6, 0xbc, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xa8, 0x6d, 0x46,
	0xfa, 0x01, 0x00, 0x00,
}
