FROM grafana/grafana
ADD cloud/docker/grafana/provisioning /etc/grafana/provisioning
ADD cloud/docker/grafana/grafana.ini /etc/grafana/grafana.ini
ADD cloud/docker/grafana/config.ini /etc/grafana/config.ini
ADD cloud/docker/grafana/dashboards /var/lib/dashboards
