FROM grafana/grafana
ADD docker/grafana/provisioning /etc/grafana/provisioning
ADD docker/grafana/grafana.ini /etc/grafana/grafana.ini
ADD docker/grafana/config.ini /etc/grafana/config.ini
ADD docker/grafana/dashboards /var/lib/dashboards
