sed '/test_attach_detach_with_ovs/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_without_ips_available/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_multi_ue/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_looped/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_deactivation_timer_expiry/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_bearer_deactivation_invalid_lbi/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_bearer_deactivation_invalid_imsi/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_bearer_deactivation_invalid_ebi/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_bearer_activation_invalid_lbi/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_bearer_activation_invalid_imsi/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_activation_timer_expiry/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_dedicated_activation_reject/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_multiple_dedicated/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_secondary_pdn_disconnect_dedicated_bearer/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_secondary_pdn_with_dedicated_bearer_looped/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_secondary_pdn_with_dedicated_bearer_multi_ue/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_secondary_pdn_with_dedicated_bearer/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_secondary_pdn_with_dedicated_bearer_deactivate/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
sed '/test_attach_detach_maxbearers_twopdns/d' -i /home/vagrant/magma/lte/gateway/python/integ_tests/defs.mk
