#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass
from datetime import datetime
from gql.gql.datetime_utils import DATETIME_FIELD
from gql.gql.graphql_client import GraphqlClient
from functools import partial
from numbers import Number
from typing import Any, Callable, List, Mapping, Optional

from dataclasses_json import DataClassJsonMixin

from gql.gql.enum_utils import enum_field
from .survey_question_type_enum import SurveyQuestionType


@dataclass
class LocationSurveysQuery(DataClassJsonMixin):
    __QUERY__: str = """
    query LocationSurveysQuery($id: ID!) {
  location: node(id: $id) {
    ... on Location {
      surveys {
        id
        name
        completionTimestamp
        sourceFile {
          id
          fileName
          storeKey
        }
        surveyResponses {
          formName
          questionFormat
          questionText
          boolData
          emailData
          latitude
          longitude
          phoneData
          textData
          floatData
          intData
          dateData
        }
      }
    }
  }
}

    """

    @dataclass
    class LocationSurveysQueryData(DataClassJsonMixin):
        @dataclass
        class Node(DataClassJsonMixin):
            @dataclass
            class Survey(DataClassJsonMixin):
                @dataclass
                class File(DataClassJsonMixin):
                    id: str
                    fileName: str
                    storeKey: Optional[str] = None

                @dataclass
                class SurveyQuestion(DataClassJsonMixin):
                    questionText: str
                    formName: Optional[str] = None
                    questionFormat: Optional[SurveyQuestionType] = None
                    boolData: Optional[bool] = None
                    emailData: Optional[str] = None
                    latitude: Optional[Number] = None
                    longitude: Optional[Number] = None
                    phoneData: Optional[str] = None
                    textData: Optional[str] = None
                    floatData: Optional[Number] = None
                    intData: Optional[int] = None
                    dateData: Optional[int] = None

                id: str
                name: str
                completionTimestamp: int
                surveyResponses: List[SurveyQuestion]
                sourceFile: Optional[File] = None

            surveys: List[Survey]

        location: Optional[Node] = None

    data: Optional[LocationSurveysQueryData] = None

    @classmethod
    # fmt: off
    def execute(cls, client: GraphqlClient, id: str):
        # fmt: off
        variables = {"id": id}
        response_text = client.call(cls.__QUERY__, variables=variables)
        return cls.from_json(response_text).data
