version: "3.7"

services:
  router_agw_proxy:
    build:
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/router_agw_proxy/Dockerfile
    container_name: router_agw_proxy
    ports:
      - "9097:9097"
    environment:
      - TOKEN_URL=${TOKEN_URL}
      - API_URL=${API_URL}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    restart: unless-stopped
    
  nginx:
    build:
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/nginx/Dockerfile

  controller: 
    build:
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/controller/Dockerfile
    environment:
      - TOKEN_URL=${TOKEN_URL}
      - API_URL=${API_URL}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

  test:
    # Test service to spin up a dev container for running unit tests,
    # precommit tests (go fmt), and code gen tools (swagger, protobuf).
    build:
      context: /tmp/magma_orc8r_build
      dockerfile: $PWD/controller/Dockerfile
      target: src
    volumes:
      - $PWD/../../../nms:/src/magma/nms
    depends_on:
      - postgres_test
    working_dir: /src/magma/orc8r/cloud
    entrypoint: /bin/bash -lc
    command: ["echo Hello World!"]

  # Test instance of psql
  postgres_test:
    image: postgres
    ports:
      - 5433:5432/tcp
    environment:
      POSTGRES_USER: magma_test
      POSTGRES_PASSWORD: magma_test
      POSTGRES_DB: magma_test
    command:
      - "postgres"
      - "-c"
      - "log_duration=true"
      - "-c"
      - "log_statement=all"
    restart: always
