//
//Copyright 2020 The Magma Authors.
//
//This source code is licensed under the BSD-style license found in the
//LICENSE file in the root directory of this source tree.
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.10.0
// source: orc8r/cloud/go/services/directoryd/protos/directoryd.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protos "magma/orc8r/lib/go/protos"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHostnameForHWIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hwid string `protobuf:"bytes,1,opt,name=hwid,proto3" json:"hwid,omitempty"`
}

func (x *GetHostnameForHWIDRequest) Reset() {
	*x = GetHostnameForHWIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostnameForHWIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostnameForHWIDRequest) ProtoMessage() {}

func (x *GetHostnameForHWIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostnameForHWIDRequest.ProtoReflect.Descriptor instead.
func (*GetHostnameForHWIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{0}
}

func (x *GetHostnameForHWIDRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

type GetHostnameForHWIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *GetHostnameForHWIDResponse) Reset() {
	*x = GetHostnameForHWIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostnameForHWIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostnameForHWIDResponse) ProtoMessage() {}

func (x *GetHostnameForHWIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostnameForHWIDResponse.ProtoReflect.Descriptor instead.
func (*GetHostnameForHWIDResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{1}
}

func (x *GetHostnameForHWIDResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type MapHWIDToHostnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HwidToHostname map[string]string `protobuf:"bytes,1,rep,name=hwidToHostname,proto3" json:"hwidToHostname,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapHWIDToHostnameRequest) Reset() {
	*x = MapHWIDToHostnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapHWIDToHostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapHWIDToHostnameRequest) ProtoMessage() {}

func (x *MapHWIDToHostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapHWIDToHostnameRequest.ProtoReflect.Descriptor instead.
func (*MapHWIDToHostnameRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{2}
}

func (x *MapHWIDToHostnameRequest) GetHwidToHostname() map[string]string {
	if x != nil {
		return x.HwidToHostname
	}
	return nil
}

type UnmapHWIDToHostnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hwids []string `protobuf:"bytes,1,rep,name=hwids,proto3" json:"hwids,omitempty"`
}

func (x *UnmapHWIDToHostnameRequest) Reset() {
	*x = UnmapHWIDToHostnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmapHWIDToHostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapHWIDToHostnameRequest) ProtoMessage() {}

func (x *UnmapHWIDToHostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapHWIDToHostnameRequest.ProtoReflect.Descriptor instead.
func (*UnmapHWIDToHostnameRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{3}
}

func (x *UnmapHWIDToHostnameRequest) GetHwids() []string {
	if x != nil {
		return x.Hwids
	}
	return nil
}

type GetIMSIForSessionIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	SessionID string `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *GetIMSIForSessionIDRequest) Reset() {
	*x = GetIMSIForSessionIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIMSIForSessionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIMSIForSessionIDRequest) ProtoMessage() {}

func (x *GetIMSIForSessionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIMSIForSessionIDRequest.ProtoReflect.Descriptor instead.
func (*GetIMSIForSessionIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{4}
}

func (x *GetIMSIForSessionIDRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *GetIMSIForSessionIDRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type GetIMSIForSessionIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imsi string `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
}

func (x *GetIMSIForSessionIDResponse) Reset() {
	*x = GetIMSIForSessionIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIMSIForSessionIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIMSIForSessionIDResponse) ProtoMessage() {}

func (x *GetIMSIForSessionIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIMSIForSessionIDResponse.ProtoReflect.Descriptor instead.
func (*GetIMSIForSessionIDResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{5}
}

func (x *GetIMSIForSessionIDResponse) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

type MapSessionIDToIMSIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID       string            `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	SessionIDToIMSI map[string]string `protobuf:"bytes,2,rep,name=sessionIDToIMSI,proto3" json:"sessionIDToIMSI,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapSessionIDToIMSIRequest) Reset() {
	*x = MapSessionIDToIMSIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapSessionIDToIMSIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSessionIDToIMSIRequest) ProtoMessage() {}

func (x *MapSessionIDToIMSIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSessionIDToIMSIRequest.ProtoReflect.Descriptor instead.
func (*MapSessionIDToIMSIRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{6}
}

func (x *MapSessionIDToIMSIRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *MapSessionIDToIMSIRequest) GetSessionIDToIMSI() map[string]string {
	if x != nil {
		return x.SessionIDToIMSI
	}
	return nil
}

type UnmapSessionIDToIMSIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID  string   `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	SessionIDs []string `protobuf:"bytes,2,rep,name=sessionIDs,proto3" json:"sessionIDs,omitempty"`
}

func (x *UnmapSessionIDToIMSIRequest) Reset() {
	*x = UnmapSessionIDToIMSIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmapSessionIDToIMSIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapSessionIDToIMSIRequest) ProtoMessage() {}

func (x *UnmapSessionIDToIMSIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapSessionIDToIMSIRequest.ProtoReflect.Descriptor instead.
func (*UnmapSessionIDToIMSIRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{7}
}

func (x *UnmapSessionIDToIMSIRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *UnmapSessionIDToIMSIRequest) GetSessionIDs() []string {
	if x != nil {
		return x.SessionIDs
	}
	return nil
}

// CTeid
type GetHWIDForSgwCTeidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Teid      string `protobuf:"bytes,2,opt,name=teid,proto3" json:"teid,omitempty"`
}

func (x *GetHWIDForSgwCTeidRequest) Reset() {
	*x = GetHWIDForSgwCTeidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHWIDForSgwCTeidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHWIDForSgwCTeidRequest) ProtoMessage() {}

func (x *GetHWIDForSgwCTeidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHWIDForSgwCTeidRequest.ProtoReflect.Descriptor instead.
func (*GetHWIDForSgwCTeidRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{8}
}

func (x *GetHWIDForSgwCTeidRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *GetHWIDForSgwCTeidRequest) GetTeid() string {
	if x != nil {
		return x.Teid
	}
	return ""
}

type GetHWIDForSgwCTeidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hwid string `protobuf:"bytes,1,opt,name=hwid,proto3" json:"hwid,omitempty"`
}

func (x *GetHWIDForSgwCTeidResponse) Reset() {
	*x = GetHWIDForSgwCTeidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHWIDForSgwCTeidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHWIDForSgwCTeidResponse) ProtoMessage() {}

func (x *GetHWIDForSgwCTeidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHWIDForSgwCTeidResponse.ProtoReflect.Descriptor instead.
func (*GetHWIDForSgwCTeidResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{9}
}

func (x *GetHWIDForSgwCTeidResponse) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

type MapSgwCTeidToHWIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID  string            `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	TeidToHwid map[string]string `protobuf:"bytes,2,rep,name=teidToHwid,proto3" json:"teidToHwid,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapSgwCTeidToHWIDRequest) Reset() {
	*x = MapSgwCTeidToHWIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapSgwCTeidToHWIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSgwCTeidToHWIDRequest) ProtoMessage() {}

func (x *MapSgwCTeidToHWIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSgwCTeidToHWIDRequest.ProtoReflect.Descriptor instead.
func (*MapSgwCTeidToHWIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{10}
}

func (x *MapSgwCTeidToHWIDRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *MapSgwCTeidToHWIDRequest) GetTeidToHwid() map[string]string {
	if x != nil {
		return x.TeidToHwid
	}
	return nil
}

type UnmapSgwCTeidToHWIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string   `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Teids     []string `protobuf:"bytes,2,rep,name=teids,proto3" json:"teids,omitempty"`
}

func (x *UnmapSgwCTeidToHWIDRequest) Reset() {
	*x = UnmapSgwCTeidToHWIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmapSgwCTeidToHWIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapSgwCTeidToHWIDRequest) ProtoMessage() {}

func (x *UnmapSgwCTeidToHWIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapSgwCTeidToHWIDRequest.ProtoReflect.Descriptor instead.
func (*UnmapSgwCTeidToHWIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{11}
}

func (x *UnmapSgwCTeidToHWIDRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *UnmapSgwCTeidToHWIDRequest) GetTeids() []string {
	if x != nil {
		return x.Teids
	}
	return nil
}

type GetNewSgwCTeidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
}

func (x *GetNewSgwCTeidRequest) Reset() {
	*x = GetNewSgwCTeidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewSgwCTeidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewSgwCTeidRequest) ProtoMessage() {}

func (x *GetNewSgwCTeidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewSgwCTeidRequest.ProtoReflect.Descriptor instead.
func (*GetNewSgwCTeidRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{12}
}

func (x *GetNewSgwCTeidRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

type GetNewSgwCTeidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teid string `protobuf:"bytes,1,opt,name=teid,proto3" json:"teid,omitempty"`
}

func (x *GetNewSgwCTeidResponse) Reset() {
	*x = GetNewSgwCTeidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewSgwCTeidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewSgwCTeidResponse) ProtoMessage() {}

func (x *GetNewSgwCTeidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewSgwCTeidResponse.ProtoReflect.Descriptor instead.
func (*GetNewSgwCTeidResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{13}
}

func (x *GetNewSgwCTeidResponse) GetTeid() string {
	if x != nil {
		return x.Teid
	}
	return ""
}

// UTeid
type GetHWIDForSgwUTeidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Teid      string `protobuf:"bytes,2,opt,name=teid,proto3" json:"teid,omitempty"`
}

func (x *GetHWIDForSgwUTeidRequest) Reset() {
	*x = GetHWIDForSgwUTeidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHWIDForSgwUTeidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHWIDForSgwUTeidRequest) ProtoMessage() {}

func (x *GetHWIDForSgwUTeidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHWIDForSgwUTeidRequest.ProtoReflect.Descriptor instead.
func (*GetHWIDForSgwUTeidRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{14}
}

func (x *GetHWIDForSgwUTeidRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *GetHWIDForSgwUTeidRequest) GetTeid() string {
	if x != nil {
		return x.Teid
	}
	return ""
}

type GetHWIDForSgwUTeidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hwid string `protobuf:"bytes,1,opt,name=hwid,proto3" json:"hwid,omitempty"`
}

func (x *GetHWIDForSgwUTeidResponse) Reset() {
	*x = GetHWIDForSgwUTeidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHWIDForSgwUTeidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHWIDForSgwUTeidResponse) ProtoMessage() {}

func (x *GetHWIDForSgwUTeidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHWIDForSgwUTeidResponse.ProtoReflect.Descriptor instead.
func (*GetHWIDForSgwUTeidResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{15}
}

func (x *GetHWIDForSgwUTeidResponse) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

type MapSgwUTeidToHWIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID  string            `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	TeidToHwid map[string]string `protobuf:"bytes,2,rep,name=teidToHwid,proto3" json:"teidToHwid,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapSgwUTeidToHWIDRequest) Reset() {
	*x = MapSgwUTeidToHWIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapSgwUTeidToHWIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSgwUTeidToHWIDRequest) ProtoMessage() {}

func (x *MapSgwUTeidToHWIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSgwUTeidToHWIDRequest.ProtoReflect.Descriptor instead.
func (*MapSgwUTeidToHWIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{16}
}

func (x *MapSgwUTeidToHWIDRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *MapSgwUTeidToHWIDRequest) GetTeidToHwid() map[string]string {
	if x != nil {
		return x.TeidToHwid
	}
	return nil
}

type UnmapSgwUTeidToHWIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string   `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Teids     []string `protobuf:"bytes,2,rep,name=teids,proto3" json:"teids,omitempty"`
}

func (x *UnmapSgwUTeidToHWIDRequest) Reset() {
	*x = UnmapSgwUTeidToHWIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmapSgwUTeidToHWIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapSgwUTeidToHWIDRequest) ProtoMessage() {}

func (x *UnmapSgwUTeidToHWIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapSgwUTeidToHWIDRequest.ProtoReflect.Descriptor instead.
func (*UnmapSgwUTeidToHWIDRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{17}
}

func (x *UnmapSgwUTeidToHWIDRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

func (x *UnmapSgwUTeidToHWIDRequest) GetTeids() []string {
	if x != nil {
		return x.Teids
	}
	return nil
}

type GetNewSgwUTeidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkID string `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
}

func (x *GetNewSgwUTeidRequest) Reset() {
	*x = GetNewSgwUTeidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewSgwUTeidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewSgwUTeidRequest) ProtoMessage() {}

func (x *GetNewSgwUTeidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewSgwUTeidRequest.ProtoReflect.Descriptor instead.
func (*GetNewSgwUTeidRequest) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{18}
}

func (x *GetNewSgwUTeidRequest) GetNetworkID() string {
	if x != nil {
		return x.NetworkID
	}
	return ""
}

type GetNewSgwUTeidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teid string `protobuf:"bytes,1,opt,name=teid,proto3" json:"teid,omitempty"`
}

func (x *GetNewSgwUTeidResponse) Reset() {
	*x = GetNewSgwUTeidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewSgwUTeidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewSgwUTeidResponse) ProtoMessage() {}

func (x *GetNewSgwUTeidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewSgwUTeidResponse.ProtoReflect.Descriptor instead.
func (*GetNewSgwUTeidResponse) Descriptor() ([]byte, []int) {
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP(), []int{19}
}

func (x *GetNewSgwUTeidResponse) GetTeid() string {
	if x != nil {
		return x.Teid
	}
	return ""
}

var File_orc8r_cloud_go_services_directoryd_protos_directoryd_proto protoreflect.FileDescriptor

var file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x67, 0x6f,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6d, 0x61,
	0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x64, 0x1a, 0x19, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x6f,
	0x72, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x77, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x77, 0x69, 0x64,
	0x22, 0x38, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x46,
	0x6f, 0x72, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x18, 0x4d,
	0x61, 0x70, 0x48, 0x57, 0x49, 0x44, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6c, 0x0a, 0x0e, 0x68, 0x77, 0x69, 0x64, 0x54,
	0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x44, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x48, 0x57, 0x49, 0x44,
	0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x48, 0x77, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x68, 0x77, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x41, 0x0a, 0x13, 0x48, 0x77, 0x69, 0x64, 0x54, 0x6f, 0x48,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x1a, 0x55, 0x6e, 0x6d, 0x61,
	0x70, 0x48, 0x57, 0x49, 0x44, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x77, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x77, 0x69, 0x64, 0x73, 0x22, 0x58, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x49, 0x4d, 0x53, 0x49, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x49, 0x4d, 0x53,
	0x49, 0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x22, 0xef, 0x01, 0x0a, 0x19, 0x4d, 0x61,
	0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x70, 0x0a, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53,
	0x49, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x1a, 0x42, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5b, 0x0a, 0x1b, 0x55,
	0x6e, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49,
	0x4d, 0x53, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x22, 0x4d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x48,
	0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x48, 0x57,
	0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x77, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x77, 0x69, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x18, 0x4d, 0x61,
	0x70, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x12, 0x60, 0x0a, 0x0a, 0x74, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x77,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61,
	0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48,
	0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x69, 0x64, 0x54,
	0x6f, 0x48, 0x77, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x74, 0x65, 0x69, 0x64,
	0x54, 0x6f, 0x48, 0x77, 0x69, 0x64, 0x1a, 0x3d, 0x0a, 0x0f, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f,
	0x48, 0x77, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x1a, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53, 0x67,
	0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x65, 0x69, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x77, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x22, 0x2c,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x48, 0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x48, 0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x77, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x77, 0x69, 0x64, 0x22, 0xd9, 0x01,
	0x0a, 0x18, 0x4d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48,
	0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x60, 0x0a, 0x0a, 0x74, 0x65, 0x69, 0x64,
	0x54, 0x6f, 0x48, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69,
	0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x77, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x74, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x77, 0x69, 0x64, 0x1a, 0x3d, 0x0a, 0x0f, 0x54, 0x65,
	0x69, 0x64, 0x54, 0x6f, 0x48, 0x77, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x1a, 0x55, 0x6e, 0x6d,
	0x61, 0x70, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x69, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x55,
	0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x69, 0x64,
	0x32, 0xf3, 0x0b, 0x0a, 0x0f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x12, 0x7d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x48, 0x57, 0x49, 0x44, 0x12, 0x31, 0x2e, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x46,
	0x6f, 0x72, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e,
	0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x46, 0x6f, 0x72, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x13, 0x4d, 0x61, 0x70, 0x48, 0x57, 0x49, 0x44, 0x73, 0x54,
	0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x30, 0x2e, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x48, 0x57, 0x49, 0x44, 0x54, 0x6f, 0x48, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22,
	0x00, 0x12, 0x60, 0x0a, 0x15, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x48, 0x57, 0x49, 0x44, 0x73, 0x54,
	0x6f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x32, 0x2e, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x64, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x48, 0x57, 0x49, 0x44, 0x54, 0x6f, 0x48,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x22, 0x00, 0x12, 0x80, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x4d, 0x53, 0x49, 0x46,
	0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x32, 0x2e, 0x6d, 0x61,
	0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x4d, 0x53, 0x49, 0x46, 0x6f, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x33, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x4d, 0x53, 0x49,
	0x46, 0x6f, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x14, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x73, 0x12, 0x31,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x16, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x73,
	0x12, 0x33, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x54, 0x6f, 0x49, 0x4d, 0x53, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72,
	0x63, 0x38, 0x72, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x48, 0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64,
	0x12, 0x31, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x57, 0x49,
	0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38,
	0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x4d, 0x61, 0x70,
	0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x12, 0x30,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x43, 0x54,
	0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53, 0x67,
	0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x12, 0x32, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x43, 0x54,
	0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53,
	0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x12, 0x2d, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e,
	0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f,
	0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x43, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x48,
	0x57, 0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x12, 0x31,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x57, 0x49, 0x44, 0x46,
	0x6f, 0x72, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x32, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x57,
	0x49, 0x44, 0x46, 0x6f, 0x72, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x4d, 0x61, 0x70, 0x53, 0x67,
	0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x12, 0x30, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69,
	0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x55,
	0x54, 0x65, 0x69, 0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x12, 0x32, 0x2e, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x64, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x70, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69,
	0x64, 0x54, 0x6f, 0x48, 0x57, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63, 0x38, 0x72, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77,
	0x55, 0x54, 0x65, 0x69, 0x64, 0x12, 0x2d, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72,
	0x63, 0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6f, 0x72, 0x63,
	0x38, 0x72, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x77, 0x53, 0x67, 0x77, 0x55, 0x54, 0x65, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2f,
	0x6f, 0x72, 0x63, 0x38, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescOnce sync.Once
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescData = file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDesc
)

func file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescGZIP() []byte {
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescOnce.Do(func() {
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescData = protoimpl.X.CompressGZIP(file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescData)
	})
	return file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDescData
}

var file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_goTypes = []interface{}{
	(*GetHostnameForHWIDRequest)(nil),   // 0: magma.orc8r.directoryd.GetHostnameForHWIDRequest
	(*GetHostnameForHWIDResponse)(nil),  // 1: magma.orc8r.directoryd.GetHostnameForHWIDResponse
	(*MapHWIDToHostnameRequest)(nil),    // 2: magma.orc8r.directoryd.MapHWIDToHostnameRequest
	(*UnmapHWIDToHostnameRequest)(nil),  // 3: magma.orc8r.directoryd.UnmapHWIDToHostnameRequest
	(*GetIMSIForSessionIDRequest)(nil),  // 4: magma.orc8r.directoryd.GetIMSIForSessionIDRequest
	(*GetIMSIForSessionIDResponse)(nil), // 5: magma.orc8r.directoryd.GetIMSIForSessionIDResponse
	(*MapSessionIDToIMSIRequest)(nil),   // 6: magma.orc8r.directoryd.MapSessionIDToIMSIRequest
	(*UnmapSessionIDToIMSIRequest)(nil), // 7: magma.orc8r.directoryd.UnmapSessionIDToIMSIRequest
	(*GetHWIDForSgwCTeidRequest)(nil),   // 8: magma.orc8r.directoryd.GetHWIDForSgwCTeidRequest
	(*GetHWIDForSgwCTeidResponse)(nil),  // 9: magma.orc8r.directoryd.GetHWIDForSgwCTeidResponse
	(*MapSgwCTeidToHWIDRequest)(nil),    // 10: magma.orc8r.directoryd.MapSgwCTeidToHWIDRequest
	(*UnmapSgwCTeidToHWIDRequest)(nil),  // 11: magma.orc8r.directoryd.UnmapSgwCTeidToHWIDRequest
	(*GetNewSgwCTeidRequest)(nil),       // 12: magma.orc8r.directoryd.GetNewSgwCTeidRequest
	(*GetNewSgwCTeidResponse)(nil),      // 13: magma.orc8r.directoryd.GetNewSgwCTeidResponse
	(*GetHWIDForSgwUTeidRequest)(nil),   // 14: magma.orc8r.directoryd.GetHWIDForSgwUTeidRequest
	(*GetHWIDForSgwUTeidResponse)(nil),  // 15: magma.orc8r.directoryd.GetHWIDForSgwUTeidResponse
	(*MapSgwUTeidToHWIDRequest)(nil),    // 16: magma.orc8r.directoryd.MapSgwUTeidToHWIDRequest
	(*UnmapSgwUTeidToHWIDRequest)(nil),  // 17: magma.orc8r.directoryd.UnmapSgwUTeidToHWIDRequest
	(*GetNewSgwUTeidRequest)(nil),       // 18: magma.orc8r.directoryd.GetNewSgwUTeidRequest
	(*GetNewSgwUTeidResponse)(nil),      // 19: magma.orc8r.directoryd.GetNewSgwUTeidResponse
	nil,                                 // 20: magma.orc8r.directoryd.MapHWIDToHostnameRequest.HwidToHostnameEntry
	nil,                                 // 21: magma.orc8r.directoryd.MapSessionIDToIMSIRequest.SessionIDToIMSIEntry
	nil,                                 // 22: magma.orc8r.directoryd.MapSgwCTeidToHWIDRequest.TeidToHwidEntry
	nil,                                 // 23: magma.orc8r.directoryd.MapSgwUTeidToHWIDRequest.TeidToHwidEntry
	(*protos.Void)(nil),                 // 24: magma.orc8r.Void
}
var file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_depIdxs = []int32{
	20, // 0: magma.orc8r.directoryd.MapHWIDToHostnameRequest.hwidToHostname:type_name -> magma.orc8r.directoryd.MapHWIDToHostnameRequest.HwidToHostnameEntry
	21, // 1: magma.orc8r.directoryd.MapSessionIDToIMSIRequest.sessionIDToIMSI:type_name -> magma.orc8r.directoryd.MapSessionIDToIMSIRequest.SessionIDToIMSIEntry
	22, // 2: magma.orc8r.directoryd.MapSgwCTeidToHWIDRequest.teidToHwid:type_name -> magma.orc8r.directoryd.MapSgwCTeidToHWIDRequest.TeidToHwidEntry
	23, // 3: magma.orc8r.directoryd.MapSgwUTeidToHWIDRequest.teidToHwid:type_name -> magma.orc8r.directoryd.MapSgwUTeidToHWIDRequest.TeidToHwidEntry
	0,  // 4: magma.orc8r.directoryd.DirectoryLookup.GetHostnameForHWID:input_type -> magma.orc8r.directoryd.GetHostnameForHWIDRequest
	2,  // 5: magma.orc8r.directoryd.DirectoryLookup.MapHWIDsToHostnames:input_type -> magma.orc8r.directoryd.MapHWIDToHostnameRequest
	3,  // 6: magma.orc8r.directoryd.DirectoryLookup.UnmapHWIDsToHostnames:input_type -> magma.orc8r.directoryd.UnmapHWIDToHostnameRequest
	4,  // 7: magma.orc8r.directoryd.DirectoryLookup.GetIMSIForSessionID:input_type -> magma.orc8r.directoryd.GetIMSIForSessionIDRequest
	6,  // 8: magma.orc8r.directoryd.DirectoryLookup.MapSessionIDsToIMSIs:input_type -> magma.orc8r.directoryd.MapSessionIDToIMSIRequest
	7,  // 9: magma.orc8r.directoryd.DirectoryLookup.UnmapSessionIDsToIMSIs:input_type -> magma.orc8r.directoryd.UnmapSessionIDToIMSIRequest
	8,  // 10: magma.orc8r.directoryd.DirectoryLookup.GetHWIDForSgwCTeid:input_type -> magma.orc8r.directoryd.GetHWIDForSgwCTeidRequest
	10, // 11: magma.orc8r.directoryd.DirectoryLookup.MapSgwCTeidToHWID:input_type -> magma.orc8r.directoryd.MapSgwCTeidToHWIDRequest
	11, // 12: magma.orc8r.directoryd.DirectoryLookup.UnmapSgwCTeidToHWID:input_type -> magma.orc8r.directoryd.UnmapSgwCTeidToHWIDRequest
	12, // 13: magma.orc8r.directoryd.DirectoryLookup.GetNewSgwCTeid:input_type -> magma.orc8r.directoryd.GetNewSgwCTeidRequest
	14, // 14: magma.orc8r.directoryd.DirectoryLookup.GetHWIDForSgwUTeid:input_type -> magma.orc8r.directoryd.GetHWIDForSgwUTeidRequest
	16, // 15: magma.orc8r.directoryd.DirectoryLookup.MapSgwUTeidToHWID:input_type -> magma.orc8r.directoryd.MapSgwUTeidToHWIDRequest
	17, // 16: magma.orc8r.directoryd.DirectoryLookup.UnmapSgwUTeidToHWID:input_type -> magma.orc8r.directoryd.UnmapSgwUTeidToHWIDRequest
	18, // 17: magma.orc8r.directoryd.DirectoryLookup.GetNewSgwUTeid:input_type -> magma.orc8r.directoryd.GetNewSgwUTeidRequest
	1,  // 18: magma.orc8r.directoryd.DirectoryLookup.GetHostnameForHWID:output_type -> magma.orc8r.directoryd.GetHostnameForHWIDResponse
	24, // 19: magma.orc8r.directoryd.DirectoryLookup.MapHWIDsToHostnames:output_type -> magma.orc8r.Void
	24, // 20: magma.orc8r.directoryd.DirectoryLookup.UnmapHWIDsToHostnames:output_type -> magma.orc8r.Void
	5,  // 21: magma.orc8r.directoryd.DirectoryLookup.GetIMSIForSessionID:output_type -> magma.orc8r.directoryd.GetIMSIForSessionIDResponse
	24, // 22: magma.orc8r.directoryd.DirectoryLookup.MapSessionIDsToIMSIs:output_type -> magma.orc8r.Void
	24, // 23: magma.orc8r.directoryd.DirectoryLookup.UnmapSessionIDsToIMSIs:output_type -> magma.orc8r.Void
	9,  // 24: magma.orc8r.directoryd.DirectoryLookup.GetHWIDForSgwCTeid:output_type -> magma.orc8r.directoryd.GetHWIDForSgwCTeidResponse
	24, // 25: magma.orc8r.directoryd.DirectoryLookup.MapSgwCTeidToHWID:output_type -> magma.orc8r.Void
	24, // 26: magma.orc8r.directoryd.DirectoryLookup.UnmapSgwCTeidToHWID:output_type -> magma.orc8r.Void
	13, // 27: magma.orc8r.directoryd.DirectoryLookup.GetNewSgwCTeid:output_type -> magma.orc8r.directoryd.GetNewSgwCTeidResponse
	15, // 28: magma.orc8r.directoryd.DirectoryLookup.GetHWIDForSgwUTeid:output_type -> magma.orc8r.directoryd.GetHWIDForSgwUTeidResponse
	24, // 29: magma.orc8r.directoryd.DirectoryLookup.MapSgwUTeidToHWID:output_type -> magma.orc8r.Void
	24, // 30: magma.orc8r.directoryd.DirectoryLookup.UnmapSgwUTeidToHWID:output_type -> magma.orc8r.Void
	19, // 31: magma.orc8r.directoryd.DirectoryLookup.GetNewSgwUTeid:output_type -> magma.orc8r.directoryd.GetNewSgwUTeidResponse
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_init() }
func file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_init() {
	if File_orc8r_cloud_go_services_directoryd_protos_directoryd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostnameForHWIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostnameForHWIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapHWIDToHostnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmapHWIDToHostnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIMSIForSessionIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIMSIForSessionIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapSessionIDToIMSIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmapSessionIDToIMSIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHWIDForSgwCTeidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHWIDForSgwCTeidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapSgwCTeidToHWIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmapSgwCTeidToHWIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewSgwCTeidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewSgwCTeidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHWIDForSgwUTeidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHWIDForSgwUTeidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapSgwUTeidToHWIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmapSgwUTeidToHWIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewSgwUTeidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewSgwUTeidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_goTypes,
		DependencyIndexes: file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_depIdxs,
		MessageInfos:      file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_msgTypes,
	}.Build()
	File_orc8r_cloud_go_services_directoryd_protos_directoryd_proto = out.File
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_rawDesc = nil
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_goTypes = nil
	file_orc8r_cloud_go_services_directoryd_protos_directoryd_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DirectoryLookupClient is the client API for DirectoryLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectoryLookupClient interface {
	// HWIDsToHostname
	// GetHostnameForHWID returns the hostname mapped to by hardware ID.
	GetHostnameForHWID(ctx context.Context, in *GetHostnameForHWIDRequest, opts ...grpc.CallOption) (*GetHostnameForHWIDResponse, error)
	// MapHWIDsToHostnames maps {hwid -> hostname}.
	MapHWIDsToHostnames(ctx context.Context, in *MapHWIDToHostnameRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// UnmapHWIDsToHostnames removes {hwid -> hostname} for an specific hwid.
	UnmapHWIDsToHostnames(ctx context.Context, in *UnmapHWIDToHostnameRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// IDsToIMSI
	// GetIMSIForSessionID returns the IMSI mapped to by session ID.
	GetIMSIForSessionID(ctx context.Context, in *GetIMSIForSessionIDRequest, opts ...grpc.CallOption) (*GetIMSIForSessionIDResponse, error)
	// MapSessionIDsToIMSIs maps {session ID -> IMSI}.
	MapSessionIDsToIMSIs(ctx context.Context, in *MapSessionIDToIMSIRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// UnmapSessionIDsToIMSIs removes {session ID -> IMSI} for an specific session ID.
	UnmapSessionIDsToIMSIs(ctx context.Context, in *UnmapSessionIDToIMSIRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// CTeid
	// GetHWIDForSgwCTeid returns the HwId mapped to by sgw control plane Sgw Teid
	GetHWIDForSgwCTeid(ctx context.Context, in *GetHWIDForSgwCTeidRequest, opts ...grpc.CallOption) (*GetHWIDForSgwCTeidResponse, error)
	// MapSgwCTeidToHWID maps {teid -> HwId}.
	MapSgwCTeidToHWID(ctx context.Context, in *MapSgwCTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// UnmapSgwCTeidToHWID removes {teid -> HwId} for an specific Teid.
	UnmapSgwCTeidToHWID(ctx context.Context, in *UnmapSgwCTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// GetNewSgwCTeid get an available teid
	GetNewSgwCTeid(ctx context.Context, in *GetNewSgwCTeidRequest, opts ...grpc.CallOption) (*GetNewSgwCTeidResponse, error)
	// UTeid
	// GetHWIDForSgwUTeid returns the HwId mapped to by sgw control plane Sgw Teid
	GetHWIDForSgwUTeid(ctx context.Context, in *GetHWIDForSgwUTeidRequest, opts ...grpc.CallOption) (*GetHWIDForSgwUTeidResponse, error)
	// MapSgwUTeidToHWID maps {teid -> HwId}.
	MapSgwUTeidToHWID(ctx context.Context, in *MapSgwUTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// UnmapSgwUTeidToHWID removes {teid -> HwId} for an specific Teid.
	UnmapSgwUTeidToHWID(ctx context.Context, in *UnmapSgwUTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error)
	// GetNewSgwUTeid get an available teid
	GetNewSgwUTeid(ctx context.Context, in *GetNewSgwUTeidRequest, opts ...grpc.CallOption) (*GetNewSgwUTeidResponse, error)
}

type directoryLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryLookupClient(cc grpc.ClientConnInterface) DirectoryLookupClient {
	return &directoryLookupClient{cc}
}

func (c *directoryLookupClient) GetHostnameForHWID(ctx context.Context, in *GetHostnameForHWIDRequest, opts ...grpc.CallOption) (*GetHostnameForHWIDResponse, error) {
	out := new(GetHostnameForHWIDResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetHostnameForHWID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) MapHWIDsToHostnames(ctx context.Context, in *MapHWIDToHostnameRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/MapHWIDsToHostnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) UnmapHWIDsToHostnames(ctx context.Context, in *UnmapHWIDToHostnameRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/UnmapHWIDsToHostnames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) GetIMSIForSessionID(ctx context.Context, in *GetIMSIForSessionIDRequest, opts ...grpc.CallOption) (*GetIMSIForSessionIDResponse, error) {
	out := new(GetIMSIForSessionIDResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetIMSIForSessionID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) MapSessionIDsToIMSIs(ctx context.Context, in *MapSessionIDToIMSIRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/MapSessionIDsToIMSIs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) UnmapSessionIDsToIMSIs(ctx context.Context, in *UnmapSessionIDToIMSIRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/UnmapSessionIDsToIMSIs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) GetHWIDForSgwCTeid(ctx context.Context, in *GetHWIDForSgwCTeidRequest, opts ...grpc.CallOption) (*GetHWIDForSgwCTeidResponse, error) {
	out := new(GetHWIDForSgwCTeidResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetHWIDForSgwCTeid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) MapSgwCTeidToHWID(ctx context.Context, in *MapSgwCTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/MapSgwCTeidToHWID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) UnmapSgwCTeidToHWID(ctx context.Context, in *UnmapSgwCTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/UnmapSgwCTeidToHWID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) GetNewSgwCTeid(ctx context.Context, in *GetNewSgwCTeidRequest, opts ...grpc.CallOption) (*GetNewSgwCTeidResponse, error) {
	out := new(GetNewSgwCTeidResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetNewSgwCTeid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) GetHWIDForSgwUTeid(ctx context.Context, in *GetHWIDForSgwUTeidRequest, opts ...grpc.CallOption) (*GetHWIDForSgwUTeidResponse, error) {
	out := new(GetHWIDForSgwUTeidResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetHWIDForSgwUTeid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) MapSgwUTeidToHWID(ctx context.Context, in *MapSgwUTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/MapSgwUTeidToHWID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) UnmapSgwUTeidToHWID(ctx context.Context, in *UnmapSgwUTeidToHWIDRequest, opts ...grpc.CallOption) (*protos.Void, error) {
	out := new(protos.Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/UnmapSgwUTeidToHWID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryLookupClient) GetNewSgwUTeid(ctx context.Context, in *GetNewSgwUTeidRequest, opts ...grpc.CallOption) (*GetNewSgwUTeidResponse, error) {
	out := new(GetNewSgwUTeidResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.directoryd.DirectoryLookup/GetNewSgwUTeid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryLookupServer is the server API for DirectoryLookup service.
type DirectoryLookupServer interface {
	// HWIDsToHostname
	// GetHostnameForHWID returns the hostname mapped to by hardware ID.
	GetHostnameForHWID(context.Context, *GetHostnameForHWIDRequest) (*GetHostnameForHWIDResponse, error)
	// MapHWIDsToHostnames maps {hwid -> hostname}.
	MapHWIDsToHostnames(context.Context, *MapHWIDToHostnameRequest) (*protos.Void, error)
	// UnmapHWIDsToHostnames removes {hwid -> hostname} for an specific hwid.
	UnmapHWIDsToHostnames(context.Context, *UnmapHWIDToHostnameRequest) (*protos.Void, error)
	// IDsToIMSI
	// GetIMSIForSessionID returns the IMSI mapped to by session ID.
	GetIMSIForSessionID(context.Context, *GetIMSIForSessionIDRequest) (*GetIMSIForSessionIDResponse, error)
	// MapSessionIDsToIMSIs maps {session ID -> IMSI}.
	MapSessionIDsToIMSIs(context.Context, *MapSessionIDToIMSIRequest) (*protos.Void, error)
	// UnmapSessionIDsToIMSIs removes {session ID -> IMSI} for an specific session ID.
	UnmapSessionIDsToIMSIs(context.Context, *UnmapSessionIDToIMSIRequest) (*protos.Void, error)
	// CTeid
	// GetHWIDForSgwCTeid returns the HwId mapped to by sgw control plane Sgw Teid
	GetHWIDForSgwCTeid(context.Context, *GetHWIDForSgwCTeidRequest) (*GetHWIDForSgwCTeidResponse, error)
	// MapSgwCTeidToHWID maps {teid -> HwId}.
	MapSgwCTeidToHWID(context.Context, *MapSgwCTeidToHWIDRequest) (*protos.Void, error)
	// UnmapSgwCTeidToHWID removes {teid -> HwId} for an specific Teid.
	UnmapSgwCTeidToHWID(context.Context, *UnmapSgwCTeidToHWIDRequest) (*protos.Void, error)
	// GetNewSgwCTeid get an available teid
	GetNewSgwCTeid(context.Context, *GetNewSgwCTeidRequest) (*GetNewSgwCTeidResponse, error)
	// UTeid
	// GetHWIDForSgwUTeid returns the HwId mapped to by sgw control plane Sgw Teid
	GetHWIDForSgwUTeid(context.Context, *GetHWIDForSgwUTeidRequest) (*GetHWIDForSgwUTeidResponse, error)
	// MapSgwUTeidToHWID maps {teid -> HwId}.
	MapSgwUTeidToHWID(context.Context, *MapSgwUTeidToHWIDRequest) (*protos.Void, error)
	// UnmapSgwUTeidToHWID removes {teid -> HwId} for an specific Teid.
	UnmapSgwUTeidToHWID(context.Context, *UnmapSgwUTeidToHWIDRequest) (*protos.Void, error)
	// GetNewSgwUTeid get an available teid
	GetNewSgwUTeid(context.Context, *GetNewSgwUTeidRequest) (*GetNewSgwUTeidResponse, error)
}

// UnimplementedDirectoryLookupServer can be embedded to have forward compatible implementations.
type UnimplementedDirectoryLookupServer struct {
}

func (*UnimplementedDirectoryLookupServer) GetHostnameForHWID(context.Context, *GetHostnameForHWIDRequest) (*GetHostnameForHWIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostnameForHWID not implemented")
}
func (*UnimplementedDirectoryLookupServer) MapHWIDsToHostnames(context.Context, *MapHWIDToHostnameRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapHWIDsToHostnames not implemented")
}
func (*UnimplementedDirectoryLookupServer) UnmapHWIDsToHostnames(context.Context, *UnmapHWIDToHostnameRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapHWIDsToHostnames not implemented")
}
func (*UnimplementedDirectoryLookupServer) GetIMSIForSessionID(context.Context, *GetIMSIForSessionIDRequest) (*GetIMSIForSessionIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIMSIForSessionID not implemented")
}
func (*UnimplementedDirectoryLookupServer) MapSessionIDsToIMSIs(context.Context, *MapSessionIDToIMSIRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapSessionIDsToIMSIs not implemented")
}
func (*UnimplementedDirectoryLookupServer) UnmapSessionIDsToIMSIs(context.Context, *UnmapSessionIDToIMSIRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapSessionIDsToIMSIs not implemented")
}
func (*UnimplementedDirectoryLookupServer) GetHWIDForSgwCTeid(context.Context, *GetHWIDForSgwCTeidRequest) (*GetHWIDForSgwCTeidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHWIDForSgwCTeid not implemented")
}
func (*UnimplementedDirectoryLookupServer) MapSgwCTeidToHWID(context.Context, *MapSgwCTeidToHWIDRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapSgwCTeidToHWID not implemented")
}
func (*UnimplementedDirectoryLookupServer) UnmapSgwCTeidToHWID(context.Context, *UnmapSgwCTeidToHWIDRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapSgwCTeidToHWID not implemented")
}
func (*UnimplementedDirectoryLookupServer) GetNewSgwCTeid(context.Context, *GetNewSgwCTeidRequest) (*GetNewSgwCTeidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewSgwCTeid not implemented")
}
func (*UnimplementedDirectoryLookupServer) GetHWIDForSgwUTeid(context.Context, *GetHWIDForSgwUTeidRequest) (*GetHWIDForSgwUTeidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHWIDForSgwUTeid not implemented")
}
func (*UnimplementedDirectoryLookupServer) MapSgwUTeidToHWID(context.Context, *MapSgwUTeidToHWIDRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapSgwUTeidToHWID not implemented")
}
func (*UnimplementedDirectoryLookupServer) UnmapSgwUTeidToHWID(context.Context, *UnmapSgwUTeidToHWIDRequest) (*protos.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapSgwUTeidToHWID not implemented")
}
func (*UnimplementedDirectoryLookupServer) GetNewSgwUTeid(context.Context, *GetNewSgwUTeidRequest) (*GetNewSgwUTeidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewSgwUTeid not implemented")
}

func RegisterDirectoryLookupServer(s *grpc.Server, srv DirectoryLookupServer) {
	s.RegisterService(&_DirectoryLookup_serviceDesc, srv)
}

func _DirectoryLookup_GetHostnameForHWID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostnameForHWIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetHostnameForHWID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetHostnameForHWID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetHostnameForHWID(ctx, req.(*GetHostnameForHWIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_MapHWIDsToHostnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapHWIDToHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).MapHWIDsToHostnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/MapHWIDsToHostnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).MapHWIDsToHostnames(ctx, req.(*MapHWIDToHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_UnmapHWIDsToHostnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapHWIDToHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).UnmapHWIDsToHostnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/UnmapHWIDsToHostnames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).UnmapHWIDsToHostnames(ctx, req.(*UnmapHWIDToHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_GetIMSIForSessionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIMSIForSessionIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetIMSIForSessionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetIMSIForSessionID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetIMSIForSessionID(ctx, req.(*GetIMSIForSessionIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_MapSessionIDsToIMSIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapSessionIDToIMSIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).MapSessionIDsToIMSIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/MapSessionIDsToIMSIs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).MapSessionIDsToIMSIs(ctx, req.(*MapSessionIDToIMSIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_UnmapSessionIDsToIMSIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapSessionIDToIMSIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).UnmapSessionIDsToIMSIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/UnmapSessionIDsToIMSIs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).UnmapSessionIDsToIMSIs(ctx, req.(*UnmapSessionIDToIMSIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_GetHWIDForSgwCTeid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHWIDForSgwCTeidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetHWIDForSgwCTeid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetHWIDForSgwCTeid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetHWIDForSgwCTeid(ctx, req.(*GetHWIDForSgwCTeidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_MapSgwCTeidToHWID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapSgwCTeidToHWIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).MapSgwCTeidToHWID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/MapSgwCTeidToHWID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).MapSgwCTeidToHWID(ctx, req.(*MapSgwCTeidToHWIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_UnmapSgwCTeidToHWID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapSgwCTeidToHWIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).UnmapSgwCTeidToHWID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/UnmapSgwCTeidToHWID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).UnmapSgwCTeidToHWID(ctx, req.(*UnmapSgwCTeidToHWIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_GetNewSgwCTeid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewSgwCTeidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetNewSgwCTeid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetNewSgwCTeid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetNewSgwCTeid(ctx, req.(*GetNewSgwCTeidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_GetHWIDForSgwUTeid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHWIDForSgwUTeidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetHWIDForSgwUTeid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetHWIDForSgwUTeid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetHWIDForSgwUTeid(ctx, req.(*GetHWIDForSgwUTeidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_MapSgwUTeidToHWID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapSgwUTeidToHWIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).MapSgwUTeidToHWID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/MapSgwUTeidToHWID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).MapSgwUTeidToHWID(ctx, req.(*MapSgwUTeidToHWIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_UnmapSgwUTeidToHWID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapSgwUTeidToHWIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).UnmapSgwUTeidToHWID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/UnmapSgwUTeidToHWID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).UnmapSgwUTeidToHWID(ctx, req.(*UnmapSgwUTeidToHWIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryLookup_GetNewSgwUTeid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewSgwUTeidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryLookupServer).GetNewSgwUTeid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.directoryd.DirectoryLookup/GetNewSgwUTeid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryLookupServer).GetNewSgwUTeid(ctx, req.(*GetNewSgwUTeidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirectoryLookup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.orc8r.directoryd.DirectoryLookup",
	HandlerType: (*DirectoryLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHostnameForHWID",
			Handler:    _DirectoryLookup_GetHostnameForHWID_Handler,
		},
		{
			MethodName: "MapHWIDsToHostnames",
			Handler:    _DirectoryLookup_MapHWIDsToHostnames_Handler,
		},
		{
			MethodName: "UnmapHWIDsToHostnames",
			Handler:    _DirectoryLookup_UnmapHWIDsToHostnames_Handler,
		},
		{
			MethodName: "GetIMSIForSessionID",
			Handler:    _DirectoryLookup_GetIMSIForSessionID_Handler,
		},
		{
			MethodName: "MapSessionIDsToIMSIs",
			Handler:    _DirectoryLookup_MapSessionIDsToIMSIs_Handler,
		},
		{
			MethodName: "UnmapSessionIDsToIMSIs",
			Handler:    _DirectoryLookup_UnmapSessionIDsToIMSIs_Handler,
		},
		{
			MethodName: "GetHWIDForSgwCTeid",
			Handler:    _DirectoryLookup_GetHWIDForSgwCTeid_Handler,
		},
		{
			MethodName: "MapSgwCTeidToHWID",
			Handler:    _DirectoryLookup_MapSgwCTeidToHWID_Handler,
		},
		{
			MethodName: "UnmapSgwCTeidToHWID",
			Handler:    _DirectoryLookup_UnmapSgwCTeidToHWID_Handler,
		},
		{
			MethodName: "GetNewSgwCTeid",
			Handler:    _DirectoryLookup_GetNewSgwCTeid_Handler,
		},
		{
			MethodName: "GetHWIDForSgwUTeid",
			Handler:    _DirectoryLookup_GetHWIDForSgwUTeid_Handler,
		},
		{
			MethodName: "MapSgwUTeidToHWID",
			Handler:    _DirectoryLookup_MapSgwUTeidToHWID_Handler,
		},
		{
			MethodName: "UnmapSgwUTeidToHWID",
			Handler:    _DirectoryLookup_UnmapSgwUTeidToHWID_Handler,
		},
		{
			MethodName: "GetNewSgwUTeid",
			Handler:    _DirectoryLookup_GetNewSgwUTeid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orc8r/cloud/go/services/directoryd/protos/directoryd.proto",
}
