// Code generated by go-swagger; DO NOT EDIT.

package upgrades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/api/v1/go/models"
)

// NewPutNetworksNetworkIDTiersTierIDVersionParams creates a new PutNetworksNetworkIDTiersTierIDVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutNetworksNetworkIDTiersTierIDVersionParams() *PutNetworksNetworkIDTiersTierIDVersionParams {
	return &PutNetworksNetworkIDTiersTierIDVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutNetworksNetworkIDTiersTierIDVersionParamsWithTimeout creates a new PutNetworksNetworkIDTiersTierIDVersionParams object
// with the ability to set a timeout on a request.
func NewPutNetworksNetworkIDTiersTierIDVersionParamsWithTimeout(timeout time.Duration) *PutNetworksNetworkIDTiersTierIDVersionParams {
	return &PutNetworksNetworkIDTiersTierIDVersionParams{
		timeout: timeout,
	}
}

// NewPutNetworksNetworkIDTiersTierIDVersionParamsWithContext creates a new PutNetworksNetworkIDTiersTierIDVersionParams object
// with the ability to set a context for a request.
func NewPutNetworksNetworkIDTiersTierIDVersionParamsWithContext(ctx context.Context) *PutNetworksNetworkIDTiersTierIDVersionParams {
	return &PutNetworksNetworkIDTiersTierIDVersionParams{
		Context: ctx,
	}
}

// NewPutNetworksNetworkIDTiersTierIDVersionParamsWithHTTPClient creates a new PutNetworksNetworkIDTiersTierIDVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutNetworksNetworkIDTiersTierIDVersionParamsWithHTTPClient(client *http.Client) *PutNetworksNetworkIDTiersTierIDVersionParams {
	return &PutNetworksNetworkIDTiersTierIDVersionParams{
		HTTPClient: client,
	}
}

/* PutNetworksNetworkIDTiersTierIDVersionParams contains all the parameters to send to the API endpoint
   for the put networks network ID tiers tier ID version operation.

   Typically these are written to a http.Request.
*/
type PutNetworksNetworkIDTiersTierIDVersionParams struct {

	/* Version.

	   New version for the tier
	*/
	Version models.TierVersion

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	/* TierID.

	   Tier ID
	*/
	TierID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put networks network ID tiers tier ID version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithDefaults() *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put networks network ID tiers tier ID version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithTimeout(timeout time.Duration) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithContext(ctx context.Context) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithHTTPClient(client *http.Client) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersion adds the version to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithVersion(version models.TierVersion) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetVersion(version models.TierVersion) {
	o.Version = version
}

// WithNetworkID adds the networkID to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithNetworkID(networkID string) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithTierID adds the tierID to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WithTierID(tierID string) *PutNetworksNetworkIDTiersTierIDVersionParams {
	o.SetTierID(tierID)
	return o
}

// SetTierID adds the tierId to the put networks network ID tiers tier ID version params
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) SetTierID(tierID string) {
	o.TierID = tierID
}

// WriteToRequest writes these params to a swagger request
func (o *PutNetworksNetworkIDTiersTierIDVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Version); err != nil {
		return err
	}

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	// path param tier_id
	if err := r.SetPathParam("tier_id", o.TierID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
