// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orc8r/protos/state.proto

package protos // import "magma/orc8r/cloud/go/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StateID struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateID) Reset()         { *m = StateID{} }
func (m *StateID) String() string { return proto.CompactTextString(m) }
func (*StateID) ProtoMessage()    {}
func (*StateID) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{0}
}
func (m *StateID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateID.Unmarshal(m, b)
}
func (m *StateID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateID.Marshal(b, m, deterministic)
}
func (dst *StateID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateID.Merge(dst, src)
}
func (m *StateID) XXX_Size() int {
	return xxx_messageInfo_StateID.Size(m)
}
func (m *StateID) XXX_DiscardUnknown() {
	xxx_messageInfo_StateID.DiscardUnknown(m)
}

var xxx_messageInfo_StateID proto.InternalMessageInfo

func (m *StateID) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StateID) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type State struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *State) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *State) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetStatesRequest struct {
	NetworkID            string     `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Ids                  []*StateID `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetStatesRequest) Reset()         { *m = GetStatesRequest{} }
func (m *GetStatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatesRequest) ProtoMessage()    {}
func (*GetStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{2}
}
func (m *GetStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatesRequest.Unmarshal(m, b)
}
func (m *GetStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatesRequest.Marshal(b, m, deterministic)
}
func (dst *GetStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatesRequest.Merge(dst, src)
}
func (m *GetStatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatesRequest.Size(m)
}
func (m *GetStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatesRequest proto.InternalMessageInfo

func (m *GetStatesRequest) GetNetworkID() string {
	if m != nil {
		return m.NetworkID
	}
	return ""
}

func (m *GetStatesRequest) GetIds() []*StateID {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetStatesResponse struct {
	States               []*State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatesResponse) Reset()         { *m = GetStatesResponse{} }
func (m *GetStatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatesResponse) ProtoMessage()    {}
func (*GetStatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{3}
}
func (m *GetStatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatesResponse.Unmarshal(m, b)
}
func (m *GetStatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatesResponse.Marshal(b, m, deterministic)
}
func (dst *GetStatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatesResponse.Merge(dst, src)
}
func (m *GetStatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatesResponse.Size(m)
}
func (m *GetStatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatesResponse proto.InternalMessageInfo

func (m *GetStatesResponse) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

type ReportStatesRequest struct {
	States               []*State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportStatesRequest) Reset()         { *m = ReportStatesRequest{} }
func (m *ReportStatesRequest) String() string { return proto.CompactTextString(m) }
func (*ReportStatesRequest) ProtoMessage()    {}
func (*ReportStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{4}
}
func (m *ReportStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportStatesRequest.Unmarshal(m, b)
}
func (m *ReportStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportStatesRequest.Marshal(b, m, deterministic)
}
func (dst *ReportStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportStatesRequest.Merge(dst, src)
}
func (m *ReportStatesRequest) XXX_Size() int {
	return xxx_messageInfo_ReportStatesRequest.Size(m)
}
func (m *ReportStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportStatesRequest proto.InternalMessageInfo

func (m *ReportStatesRequest) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

type DeleteStatesRequest struct {
	NetworkID            string     `protobuf:"bytes,1,opt,name=networkID,proto3" json:"networkID,omitempty"`
	Ids                  []*StateID `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteStatesRequest) Reset()         { *m = DeleteStatesRequest{} }
func (m *DeleteStatesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStatesRequest) ProtoMessage()    {}
func (*DeleteStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_a06b0e40511df954, []int{5}
}
func (m *DeleteStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStatesRequest.Unmarshal(m, b)
}
func (m *DeleteStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStatesRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStatesRequest.Merge(dst, src)
}
func (m *DeleteStatesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStatesRequest.Size(m)
}
func (m *DeleteStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStatesRequest proto.InternalMessageInfo

func (m *DeleteStatesRequest) GetNetworkID() string {
	if m != nil {
		return m.NetworkID
	}
	return ""
}

func (m *DeleteStatesRequest) GetIds() []*StateID {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*StateID)(nil), "magma.orc8r.StateID")
	proto.RegisterType((*State)(nil), "magma.orc8r.State")
	proto.RegisterType((*GetStatesRequest)(nil), "magma.orc8r.GetStatesRequest")
	proto.RegisterType((*GetStatesResponse)(nil), "magma.orc8r.GetStatesResponse")
	proto.RegisterType((*ReportStatesRequest)(nil), "magma.orc8r.ReportStatesRequest")
	proto.RegisterType((*DeleteStatesRequest)(nil), "magma.orc8r.DeleteStatesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateServiceClient interface {
	GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesResponse, error)
	ReportStates(ctx context.Context, in *ReportStatesRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteStates(ctx context.Context, in *DeleteStatesRequest, opts ...grpc.CallOption) (*Void, error)
}

type stateServiceClient struct {
	cc *grpc.ClientConn
}

func NewStateServiceClient(cc *grpc.ClientConn) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesResponse, error) {
	out := new(GetStatesResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.StateService/GetStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) ReportStates(ctx context.Context, in *ReportStatesRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.StateService/ReportStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) DeleteStates(ctx context.Context, in *DeleteStatesRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/magma.orc8r.StateService/DeleteStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
type StateServiceServer interface {
	GetStates(context.Context, *GetStatesRequest) (*GetStatesResponse, error)
	ReportStates(context.Context, *ReportStatesRequest) (*Void, error)
	DeleteStates(context.Context, *DeleteStatesRequest) (*Void, error)
}

func RegisterStateServiceServer(s *grpc.Server, srv StateServiceServer) {
	s.RegisterService(&_StateService_serviceDesc, srv)
}

func _StateService_GetStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.StateService/GetStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetStates(ctx, req.(*GetStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_ReportStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).ReportStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.StateService/ReportStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).ReportStates(ctx, req.(*ReportStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_DeleteStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).DeleteStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.StateService/DeleteStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).DeleteStates(ctx, req.(*DeleteStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.orc8r.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStates",
			Handler:    _StateService_GetStates_Handler,
		},
		{
			MethodName: "ReportStates",
			Handler:    _StateService_ReportStates_Handler,
		},
		{
			MethodName: "DeleteStates",
			Handler:    _StateService_DeleteStates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orc8r/protos/state.proto",
}

func init() { proto.RegisterFile("orc8r/protos/state.proto", fileDescriptor_state_a06b0e40511df954) }

var fileDescriptor_state_a06b0e40511df954 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x20, 0x28, 0x03, 0x07, 0x19, 0x38, 0xd4, 0x2a, 0xa6, 0xd9, 0x83, 0x21, 0x1e, 0xda,
	0x04, 0x2f, 0x7a, 0x32, 0x9a, 0x1a, 0x43, 0xa2, 0x97, 0x25, 0x31, 0x46, 0x4f, 0xb5, 0x9d, 0x10,
	0x22, 0x65, 0xeb, 0xee, 0x82, 0xf1, 0x97, 0xfd, 0x0a, 0xc3, 0xb6, 0xc1, 0x16, 0xf1, 0xc0, 0xc1,
	0x53, 0x3b, 0x6f, 0xde, 0x7b, 0xd9, 0xf7, 0x32, 0x60, 0x0b, 0x19, 0x5d, 0x48, 0x3f, 0x95, 0x42,
	0x0b, 0xe5, 0x2b, 0x1d, 0x6a, 0xf2, 0xcc, 0x80, 0xcd, 0x24, 0x1c, 0x27, 0xa1, 0x67, 0xf6, 0xce,
	0x61, 0x89, 0x16, 0x89, 0x24, 0x11, 0xb3, 0x8c, 0xc7, 0x2e, 0x61, 0x6f, 0xb4, 0x94, 0x0d, 0x03,
	0x44, 0xd8, 0xd5, 0x9f, 0x29, 0xd9, 0x96, 0x6b, 0xf5, 0x1b, 0xdc, 0xfc, 0xa3, 0x03, 0xfb, 0x31,
	0x2d, 0x26, 0x11, 0x0d, 0x03, 0xbb, 0x62, 0xf0, 0xd5, 0xcc, 0x1e, 0xa0, 0x66, 0xa4, 0xdb, 0x0a,
	0xb1, 0x0b, 0xb5, 0x45, 0x38, 0x9d, 0x93, 0x5d, 0x75, 0xad, 0x7e, 0x8b, 0x67, 0x03, 0x7b, 0x82,
	0x83, 0x3b, 0xd2, 0xc6, 0x51, 0x71, 0x7a, 0x9f, 0x93, 0xd2, 0x78, 0x0c, 0x8d, 0x19, 0xe9, 0x0f,
	0x21, 0xdf, 0x86, 0x41, 0x6e, 0xff, 0x03, 0xe0, 0x29, 0x54, 0x27, 0xb1, 0xb2, 0x2b, 0x6e, 0xb5,
	0xdf, 0x1c, 0x74, 0xbd, 0x42, 0x62, 0x2f, 0xcf, 0xc4, 0x97, 0x04, 0x76, 0x05, 0xed, 0x82, 0xb3,
	0x4a, 0xc5, 0x4c, 0x11, 0x9e, 0x41, 0xdd, 0xf4, 0xa5, 0x6c, 0xcb, 0xe8, 0xf1, 0xb7, 0x9e, 0xe7,
	0x0c, 0x76, 0x0d, 0x1d, 0x4e, 0xa9, 0x90, 0x6b, 0xaf, 0xdb, 0xc6, 0xe2, 0x05, 0x3a, 0x01, 0x4d,
	0x49, 0xd3, 0x3f, 0x04, 0x1c, 0x7c, 0x59, 0xd0, 0x32, 0xc0, 0x88, 0xe4, 0xb2, 0x63, 0xbc, 0x87,
	0xc6, 0x2a, 0x31, 0xf6, 0x4a, 0xc2, 0xf5, 0x8e, 0x9d, 0x93, 0xbf, 0xd6, 0x59, 0x51, 0x6c, 0x07,
	0x6f, 0xa1, 0x55, 0x8c, 0x8f, 0x6e, 0x49, 0xb1, 0xa1, 0x19, 0xa7, 0x5d, 0x62, 0x3c, 0x8a, 0x49,
	0x9c, 0xd9, 0x14, 0x2b, 0x58, 0xb3, 0xd9, 0xd0, 0xce, 0x46, 0x9b, 0x9b, 0xde, 0xf3, 0x91, 0x41,
	0xfd, 0xec, 0xa8, 0xa3, 0xa9, 0x98, 0xc7, 0xfe, 0x58, 0xe4, 0xd7, 0xfd, 0x5a, 0x37, 0xdf, 0xf3,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x5a, 0x56, 0x0a, 0x1b, 0x03, 0x00, 0x00,
}
