// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// PutNetworksNetworkIDReader is a Reader for the PutNetworksNetworkID structure.
type PutNetworksNetworkIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutNetworksNetworkIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutNetworksNetworkIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutNetworksNetworkIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutNetworksNetworkIDNoContent creates a PutNetworksNetworkIDNoContent with default headers values
func NewPutNetworksNetworkIDNoContent() *PutNetworksNetworkIDNoContent {
	return &PutNetworksNetworkIDNoContent{}
}

/*PutNetworksNetworkIDNoContent handles this case with default header values.

Success
*/
type PutNetworksNetworkIDNoContent struct {
}

func (o *PutNetworksNetworkIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /networks/{network_id}][%d] putNetworksNetworkIdNoContent ", 204)
}

func (o *PutNetworksNetworkIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutNetworksNetworkIDDefault creates a PutNetworksNetworkIDDefault with default headers values
func NewPutNetworksNetworkIDDefault(code int) *PutNetworksNetworkIDDefault {
	return &PutNetworksNetworkIDDefault{
		_statusCode: code,
	}
}

/*PutNetworksNetworkIDDefault handles this case with default header values.

Unexpected Error
*/
type PutNetworksNetworkIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put networks network ID default response
func (o *PutNetworksNetworkIDDefault) Code() int {
	return o._statusCode
}

func (o *PutNetworksNetworkIDDefault) Error() string {
	return fmt.Sprintf("[PUT /networks/{network_id}][%d] PutNetworksNetworkID default  %+v", o._statusCode, o.Payload)
}

func (o *PutNetworksNetworkIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutNetworksNetworkIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
