// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	models2 "magma/lte/cloud/go/plugin/models"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FederatedNetworkCellularConfigs Cellular configuration for a federated network
// swagger:model federated_network_cellular_configs
type FederatedNetworkCellularConfigs struct {

	// epc
	// Required: true
	Epc *models2.NetworkEpcConfigs `json:"epc"`

	// feg network id
	FegNetworkID FegNetworkID `json:"feg_network_id,omitempty"`

	// network federation configs
	NetworkFederationConfigs *NetworkFederationConfigs `json:"network_federation_configs,omitempty"`

	// ran
	// Required: true
	Ran *models2.NetworkRanConfigs `json:"ran"`
}

// Validate validates this federated network cellular configs
func (m *FederatedNetworkCellularConfigs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEpc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFegNetworkID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkFederationConfigs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FederatedNetworkCellularConfigs) validateEpc(formats strfmt.Registry) error {

	if err := validate.Required("epc", "body", m.Epc); err != nil {
		return err
	}

	if m.Epc != nil {
		if err := m.Epc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("epc")
			}
			return err
		}
	}

	return nil
}

func (m *FederatedNetworkCellularConfigs) validateFegNetworkID(formats strfmt.Registry) error {

	if swag.IsZero(m.FegNetworkID) { // not required
		return nil
	}

	if err := m.FegNetworkID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("feg_network_id")
		}
		return err
	}

	return nil
}

func (m *FederatedNetworkCellularConfigs) validateNetworkFederationConfigs(formats strfmt.Registry) error {

	if swag.IsZero(m.NetworkFederationConfigs) { // not required
		return nil
	}

	if m.NetworkFederationConfigs != nil {
		if err := m.NetworkFederationConfigs.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("network_federation_configs")
			}
			return err
		}
	}

	return nil
}

func (m *FederatedNetworkCellularConfigs) validateRan(formats strfmt.Registry) error {

	if err := validate.Required("ran", "body", m.Ran); err != nil {
		return err
	}

	if m.Ran != nil {
		if err := m.Ran.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ran")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FederatedNetworkCellularConfigs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FederatedNetworkCellularConfigs) UnmarshalBinary(b []byte) error {
	var res FederatedNetworkCellularConfigs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
