#!/bin/bash

if [[ ! -d /cache/devmand ]]; then
  echo "error: the test script should only be run inside docker."
  exit 1
fi


# TODO remove?
valgrind --tool=memcheck \
         --num-callers=100 \
         --log-file=devmantest.log ./devmantest
# --track-origins=yes --leak-check=full --show-reachable=yes
# --show-reachable=no --undef-value-errors=no --track-origins=no
# --child-silent-after-fork=no --trace-children=no --fair-sched=yes"
head -n 200 devmantest.log
ctest -T memcheck -V
ctest -T test -V
