// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lte/protos/oai/s1ap_state.proto

package oai

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S1ApTimer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sec                  int32    `protobuf:"varint,2,opt,name=sec,proto3" json:"sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S1ApTimer) Reset()         { *m = S1ApTimer{} }
func (m *S1ApTimer) String() string { return proto.CompactTextString(m) }
func (*S1ApTimer) ProtoMessage()    {}
func (*S1ApTimer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{0}
}

func (m *S1ApTimer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S1ApTimer.Unmarshal(m, b)
}
func (m *S1ApTimer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S1ApTimer.Marshal(b, m, deterministic)
}
func (m *S1ApTimer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S1ApTimer.Merge(m, src)
}
func (m *S1ApTimer) XXX_Size() int {
	return xxx_messageInfo_S1ApTimer.Size(m)
}
func (m *S1ApTimer) XXX_DiscardUnknown() {
	xxx_messageInfo_S1ApTimer.DiscardUnknown(m)
}

var xxx_messageInfo_S1ApTimer proto.InternalMessageInfo

func (m *S1ApTimer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S1ApTimer) GetSec() int32 {
	if m != nil {
		return m.Sec
	}
	return 0
}

type SupportedTaiItems struct {
	Tac                  uint32   `protobuf:"varint,1,opt,name=tac,proto3" json:"tac,omitempty"`
	BplmnlistCount       uint32   `protobuf:"varint,2,opt,name=bplmnlist_count,json=bplmnlistCount,proto3" json:"bplmnlist_count,omitempty"`
	Bplmns               [][]byte `protobuf:"bytes,3,rep,name=bplmns,proto3" json:"bplmns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportedTaiItems) Reset()         { *m = SupportedTaiItems{} }
func (m *SupportedTaiItems) String() string { return proto.CompactTextString(m) }
func (*SupportedTaiItems) ProtoMessage()    {}
func (*SupportedTaiItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{1}
}

func (m *SupportedTaiItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedTaiItems.Unmarshal(m, b)
}
func (m *SupportedTaiItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedTaiItems.Marshal(b, m, deterministic)
}
func (m *SupportedTaiItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedTaiItems.Merge(m, src)
}
func (m *SupportedTaiItems) XXX_Size() int {
	return xxx_messageInfo_SupportedTaiItems.Size(m)
}
func (m *SupportedTaiItems) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedTaiItems.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedTaiItems proto.InternalMessageInfo

func (m *SupportedTaiItems) GetTac() uint32 {
	if m != nil {
		return m.Tac
	}
	return 0
}

func (m *SupportedTaiItems) GetBplmnlistCount() uint32 {
	if m != nil {
		return m.BplmnlistCount
	}
	return 0
}

func (m *SupportedTaiItems) GetBplmns() [][]byte {
	if m != nil {
		return m.Bplmns
	}
	return nil
}

// supported_ta_list_t
type SupportedTaList struct {
	ListCount            uint32               `protobuf:"varint,1,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	SupportedTaiItems    []*SupportedTaiItems `protobuf:"bytes,2,rep,name=supported_tai_items,json=supportedTaiItems,proto3" json:"supported_tai_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SupportedTaList) Reset()         { *m = SupportedTaList{} }
func (m *SupportedTaList) String() string { return proto.CompactTextString(m) }
func (*SupportedTaList) ProtoMessage()    {}
func (*SupportedTaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{2}
}

func (m *SupportedTaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedTaList.Unmarshal(m, b)
}
func (m *SupportedTaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedTaList.Marshal(b, m, deterministic)
}
func (m *SupportedTaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedTaList.Merge(m, src)
}
func (m *SupportedTaList) XXX_Size() int {
	return xxx_messageInfo_SupportedTaList.Size(m)
}
func (m *SupportedTaList) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedTaList.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedTaList proto.InternalMessageInfo

func (m *SupportedTaList) GetListCount() uint32 {
	if m != nil {
		return m.ListCount
	}
	return 0
}

func (m *SupportedTaList) GetSupportedTaiItems() []*SupportedTaiItems {
	if m != nil {
		return m.SupportedTaiItems
	}
	return nil
}

type EnbDescription struct {
	EnbId                uint32            `protobuf:"varint,1,opt,name=enb_id,json=enbId,proto3" json:"enb_id,omitempty"`
	S1State              int32             `protobuf:"varint,2,opt,name=s1_state,json=s1State,proto3" json:"s1_state,omitempty"`
	EnbName              []byte            `protobuf:"bytes,3,opt,name=enb_name,json=enbName,proto3" json:"enb_name,omitempty"`
	DefaultPagingDrx     uint32            `protobuf:"varint,4,opt,name=default_paging_drx,json=defaultPagingDrx,proto3" json:"default_paging_drx,omitempty"`
	NbUeAssociated       uint32            `protobuf:"varint,5,opt,name=nb_ue_associated,json=nbUeAssociated,proto3" json:"nb_ue_associated,omitempty"`
	SctpAssocId          uint32            `protobuf:"varint,6,opt,name=sctp_assoc_id,json=sctpAssocId,proto3" json:"sctp_assoc_id,omitempty"`
	NextSctpStream       uint32            `protobuf:"varint,7,opt,name=next_sctp_stream,json=nextSctpStream,proto3" json:"next_sctp_stream,omitempty"`
	Instreams            uint32            `protobuf:"varint,8,opt,name=instreams,proto3" json:"instreams,omitempty"`
	Outstreams           uint32            `protobuf:"varint,9,opt,name=outstreams,proto3" json:"outstreams,omitempty"`
	UeIds                map[uint64]uint64 `protobuf:"bytes,10,rep,name=ue_ids,json=ueIds,proto3" json:"ue_ids,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SupportedTaList      *SupportedTaList  `protobuf:"bytes,11,opt,name=supported_ta_list,json=supportedTaList,proto3" json:"supported_ta_list,omitempty"`
	RanCpIpaddr          []byte            `protobuf:"bytes,12,opt,name=ran_cp_ipaddr,json=ranCpIpaddr,proto3" json:"ran_cp_ipaddr,omitempty"`
	RanCpIpaddrSz        uint32            `protobuf:"varint,13,opt,name=ran_cp_ipaddr_sz,json=ranCpIpaddrSz,proto3" json:"ran_cp_ipaddr_sz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EnbDescription) Reset()         { *m = EnbDescription{} }
func (m *EnbDescription) String() string { return proto.CompactTextString(m) }
func (*EnbDescription) ProtoMessage()    {}
func (*EnbDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{3}
}

func (m *EnbDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnbDescription.Unmarshal(m, b)
}
func (m *EnbDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnbDescription.Marshal(b, m, deterministic)
}
func (m *EnbDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnbDescription.Merge(m, src)
}
func (m *EnbDescription) XXX_Size() int {
	return xxx_messageInfo_EnbDescription.Size(m)
}
func (m *EnbDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_EnbDescription.DiscardUnknown(m)
}

var xxx_messageInfo_EnbDescription proto.InternalMessageInfo

func (m *EnbDescription) GetEnbId() uint32 {
	if m != nil {
		return m.EnbId
	}
	return 0
}

func (m *EnbDescription) GetS1State() int32 {
	if m != nil {
		return m.S1State
	}
	return 0
}

func (m *EnbDescription) GetEnbName() []byte {
	if m != nil {
		return m.EnbName
	}
	return nil
}

func (m *EnbDescription) GetDefaultPagingDrx() uint32 {
	if m != nil {
		return m.DefaultPagingDrx
	}
	return 0
}

func (m *EnbDescription) GetNbUeAssociated() uint32 {
	if m != nil {
		return m.NbUeAssociated
	}
	return 0
}

func (m *EnbDescription) GetSctpAssocId() uint32 {
	if m != nil {
		return m.SctpAssocId
	}
	return 0
}

func (m *EnbDescription) GetNextSctpStream() uint32 {
	if m != nil {
		return m.NextSctpStream
	}
	return 0
}

func (m *EnbDescription) GetInstreams() uint32 {
	if m != nil {
		return m.Instreams
	}
	return 0
}

func (m *EnbDescription) GetOutstreams() uint32 {
	if m != nil {
		return m.Outstreams
	}
	return 0
}

func (m *EnbDescription) GetUeIds() map[uint64]uint64 {
	if m != nil {
		return m.UeIds
	}
	return nil
}

func (m *EnbDescription) GetSupportedTaList() *SupportedTaList {
	if m != nil {
		return m.SupportedTaList
	}
	return nil
}

func (m *EnbDescription) GetRanCpIpaddr() []byte {
	if m != nil {
		return m.RanCpIpaddr
	}
	return nil
}

func (m *EnbDescription) GetRanCpIpaddrSz() uint32 {
	if m != nil {
		return m.RanCpIpaddrSz
	}
	return 0
}

type UeDescription struct {
	S1UeState             int32      `protobuf:"varint,2,opt,name=s1_ue_state,json=s1UeState,proto3" json:"s1_ue_state,omitempty"`
	EnbUeS1ApId           uint32     `protobuf:"varint,3,opt,name=enb_ue_s1ap_id,json=enbUeS1apId,proto3" json:"enb_ue_s1ap_id,omitempty"`
	MmeUeS1ApId           uint32     `protobuf:"varint,4,opt,name=mme_ue_s1ap_id,json=mmeUeS1apId,proto3" json:"mme_ue_s1ap_id,omitempty"`
	SctpStreamRecv        uint32     `protobuf:"varint,5,opt,name=sctp_stream_recv,json=sctpStreamRecv,proto3" json:"sctp_stream_recv,omitempty"`
	SctpStreamSend        uint32     `protobuf:"varint,6,opt,name=sctp_stream_send,json=sctpStreamSend,proto3" json:"sctp_stream_send,omitempty"`
	S1ApUeContextRelTimer *S1ApTimer `protobuf:"bytes,7,opt,name=s1ap_ue_context_rel_timer,json=s1apUeContextRelTimer,proto3" json:"s1ap_ue_context_rel_timer,omitempty"`
	SctpAssocId           uint32     `protobuf:"varint,8,opt,name=sctp_assoc_id,json=sctpAssocId,proto3" json:"sctp_assoc_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *UeDescription) Reset()         { *m = UeDescription{} }
func (m *UeDescription) String() string { return proto.CompactTextString(m) }
func (*UeDescription) ProtoMessage()    {}
func (*UeDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{4}
}

func (m *UeDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UeDescription.Unmarshal(m, b)
}
func (m *UeDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UeDescription.Marshal(b, m, deterministic)
}
func (m *UeDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UeDescription.Merge(m, src)
}
func (m *UeDescription) XXX_Size() int {
	return xxx_messageInfo_UeDescription.Size(m)
}
func (m *UeDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_UeDescription.DiscardUnknown(m)
}

var xxx_messageInfo_UeDescription proto.InternalMessageInfo

func (m *UeDescription) GetS1UeState() int32 {
	if m != nil {
		return m.S1UeState
	}
	return 0
}

func (m *UeDescription) GetEnbUeS1ApId() uint32 {
	if m != nil {
		return m.EnbUeS1ApId
	}
	return 0
}

func (m *UeDescription) GetMmeUeS1ApId() uint32 {
	if m != nil {
		return m.MmeUeS1ApId
	}
	return 0
}

func (m *UeDescription) GetSctpStreamRecv() uint32 {
	if m != nil {
		return m.SctpStreamRecv
	}
	return 0
}

func (m *UeDescription) GetSctpStreamSend() uint32 {
	if m != nil {
		return m.SctpStreamSend
	}
	return 0
}

func (m *UeDescription) GetS1ApUeContextRelTimer() *S1ApTimer {
	if m != nil {
		return m.S1ApUeContextRelTimer
	}
	return nil
}

func (m *UeDescription) GetSctpAssocId() uint32 {
	if m != nil {
		return m.SctpAssocId
	}
	return 0
}

type S1ApState struct {
	Enbs                 map[uint32]*EnbDescription `protobuf:"bytes,1,rep,name=enbs,proto3" json:"enbs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mmeid2Associd        map[uint32]uint32          `protobuf:"bytes,2,rep,name=mmeid2associd,proto3" json:"mmeid2associd,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NumEnbs              uint32                     `protobuf:"varint,3,opt,name=num_enbs,json=numEnbs,proto3" json:"num_enbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *S1ApState) Reset()         { *m = S1ApState{} }
func (m *S1ApState) String() string { return proto.CompactTextString(m) }
func (*S1ApState) ProtoMessage()    {}
func (*S1ApState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{5}
}

func (m *S1ApState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S1ApState.Unmarshal(m, b)
}
func (m *S1ApState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S1ApState.Marshal(b, m, deterministic)
}
func (m *S1ApState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S1ApState.Merge(m, src)
}
func (m *S1ApState) XXX_Size() int {
	return xxx_messageInfo_S1ApState.Size(m)
}
func (m *S1ApState) XXX_DiscardUnknown() {
	xxx_messageInfo_S1ApState.DiscardUnknown(m)
}

var xxx_messageInfo_S1ApState proto.InternalMessageInfo

func (m *S1ApState) GetEnbs() map[uint32]*EnbDescription {
	if m != nil {
		return m.Enbs
	}
	return nil
}

func (m *S1ApState) GetMmeid2Associd() map[uint32]uint32 {
	if m != nil {
		return m.Mmeid2Associd
	}
	return nil
}

func (m *S1ApState) GetNumEnbs() uint32 {
	if m != nil {
		return m.NumEnbs
	}
	return 0
}

type S1ApImsiMap struct {
	MmeUeIdImsiMap       map[uint64]uint64 `protobuf:"bytes,1,rep,name=mme_ue_id_imsi_map,json=mmeUeIdImsiMap,proto3" json:"mme_ue_id_imsi_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *S1ApImsiMap) Reset()         { *m = S1ApImsiMap{} }
func (m *S1ApImsiMap) String() string { return proto.CompactTextString(m) }
func (*S1ApImsiMap) ProtoMessage()    {}
func (*S1ApImsiMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_d555416faabf15fc, []int{6}
}

func (m *S1ApImsiMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S1ApImsiMap.Unmarshal(m, b)
}
func (m *S1ApImsiMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S1ApImsiMap.Marshal(b, m, deterministic)
}
func (m *S1ApImsiMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S1ApImsiMap.Merge(m, src)
}
func (m *S1ApImsiMap) XXX_Size() int {
	return xxx_messageInfo_S1ApImsiMap.Size(m)
}
func (m *S1ApImsiMap) XXX_DiscardUnknown() {
	xxx_messageInfo_S1ApImsiMap.DiscardUnknown(m)
}

var xxx_messageInfo_S1ApImsiMap proto.InternalMessageInfo

func (m *S1ApImsiMap) GetMmeUeIdImsiMap() map[uint64]uint64 {
	if m != nil {
		return m.MmeUeIdImsiMap
	}
	return nil
}

func init() {
	proto.RegisterType((*S1ApTimer)(nil), "magma.lte.oai.S1apTimer")
	proto.RegisterType((*SupportedTaiItems)(nil), "magma.lte.oai.SupportedTaiItems")
	proto.RegisterType((*SupportedTaList)(nil), "magma.lte.oai.SupportedTaList")
	proto.RegisterType((*EnbDescription)(nil), "magma.lte.oai.EnbDescription")
	proto.RegisterMapType((map[uint64]uint64)(nil), "magma.lte.oai.EnbDescription.UeIdsEntry")
	proto.RegisterType((*UeDescription)(nil), "magma.lte.oai.UeDescription")
	proto.RegisterType((*S1ApState)(nil), "magma.lte.oai.S1apState")
	proto.RegisterMapType((map[uint32]*EnbDescription)(nil), "magma.lte.oai.S1apState.EnbsEntry")
	proto.RegisterMapType((map[uint32]uint32)(nil), "magma.lte.oai.S1apState.Mmeid2associdEntry")
	proto.RegisterType((*S1ApImsiMap)(nil), "magma.lte.oai.S1apImsiMap")
	proto.RegisterMapType((map[uint64]uint64)(nil), "magma.lte.oai.S1apImsiMap.MmeUeIdImsiMapEntry")
}

func init() { proto.RegisterFile("lte/protos/oai/s1ap_state.proto", fileDescriptor_d555416faabf15fc) }

var fileDescriptor_d555416faabf15fc = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xc7, 0xe1, 0x9f, 0x89, 0x9f, 0x22, 0xc7, 0x61, 0xd7, 0x41, 0x0d, 0x96, 0xd4, 0xf0, 0x0e,
	0x35, 0xb0, 0xcd, 0x86, 0x5d, 0x60, 0x28, 0x76, 0xd9, 0xba, 0xb4, 0x07, 0x0f, 0xeb, 0xd0, 0xc9,
	0xf5, 0x0e, 0xbd, 0x10, 0x94, 0xf8, 0x1a, 0x10, 0x13, 0x29, 0x41, 0xa4, 0x82, 0xb4, 0xc7, 0xfd,
	0x3d, 0xfb, 0x37, 0x76, 0xda, 0x79, 0xff, 0xcf, 0x40, 0x52, 0x76, 0x65, 0x27, 0x1d, 0xb0, 0x1b,
	0xf9, 0xf8, 0xe5, 0x23, 0xf5, 0xbe, 0x9f, 0x47, 0xc1, 0xe3, 0xcc, 0xe0, 0xbc, 0x28, 0x73, 0x93,
	0xeb, 0x79, 0xce, 0xc4, 0x5c, 0x2f, 0x58, 0x41, 0xb5, 0x61, 0x06, 0x67, 0x2e, 0x4a, 0x42, 0xc9,
	0xae, 0x25, 0x9b, 0x65, 0x06, 0x67, 0x39, 0x13, 0x93, 0x6f, 0x60, 0xb0, 0x5e, 0xb0, 0xe2, 0x8d,
	0x90, 0x58, 0x92, 0x21, 0xb4, 0x05, 0x8f, 0x5a, 0xe3, 0xd6, 0xb4, 0x17, 0xb7, 0x05, 0x27, 0x23,
	0xe8, 0x68, 0x4c, 0xa3, 0xb6, 0x0b, 0xd8, 0xe1, 0xe4, 0x1d, 0x9c, 0xad, 0xab, 0xa2, 0xc8, 0x4b,
	0x83, 0xfc, 0x0d, 0x13, 0x2b, 0x83, 0x52, 0x5b, 0x99, 0x61, 0xa9, 0xdb, 0x17, 0xc6, 0x76, 0x48,
	0x9e, 0xc0, 0x69, 0x52, 0x64, 0x52, 0x65, 0x42, 0x1b, 0x9a, 0xe6, 0x95, 0x32, 0x2e, 0x49, 0x18,
	0x0f, 0x77, 0xe1, 0x2b, 0x1b, 0x25, 0x9f, 0x43, 0xdf, 0x45, 0x74, 0xd4, 0x19, 0x77, 0xa6, 0x27,
	0x71, 0x3d, 0x9b, 0xfc, 0xd1, 0x82, 0xd3, 0xc6, 0x41, 0x3f, 0x0b, 0x6d, 0xc8, 0x05, 0x40, 0x23,
	0x9f, 0x3f, 0x6d, 0xf0, 0x31, 0xd5, 0x6b, 0x78, 0xa0, 0xb7, 0x3b, 0xa8, 0x61, 0x82, 0x0a, 0x7b,
	0xb9, 0xa8, 0x3d, 0xee, 0x4c, 0x83, 0xe5, 0x78, 0xb6, 0xf7, 0xd9, 0xb3, 0x3b, 0x1f, 0x11, 0x9f,
	0xe9, 0xc3, 0xd0, 0xe4, 0x9f, 0x2e, 0x0c, 0x5f, 0xaa, 0xe4, 0x05, 0xea, 0xb4, 0x14, 0x85, 0x11,
	0xb9, 0x22, 0x0f, 0xa1, 0x8f, 0x2a, 0xa1, 0x75, 0x95, 0xc2, 0xb8, 0x87, 0x2a, 0x59, 0x71, 0xf2,
	0x08, 0x8e, 0xf5, 0xc2, 0x97, 0xb9, 0xae, 0xd6, 0x91, 0x5e, 0xac, 0xed, 0xd4, 0x2e, 0xd9, 0x1d,
	0x8a, 0x49, 0x8c, 0x3a, 0xe3, 0xd6, 0xf4, 0x24, 0x3e, 0x42, 0x95, 0xfc, 0xc2, 0x24, 0x92, 0xaf,
	0x81, 0x70, 0x7c, 0xc7, 0xaa, 0xcc, 0xd0, 0x82, 0x5d, 0x0b, 0x75, 0x4d, 0x79, 0x79, 0x1b, 0x75,
	0x5d, 0xe2, 0x51, 0xbd, 0xf2, 0xda, 0x2d, 0xbc, 0x28, 0x6f, 0xc9, 0x14, 0x46, 0x2a, 0xa1, 0x15,
	0x52, 0xa6, 0x75, 0x9e, 0x0a, 0x66, 0x90, 0x47, 0x3d, 0x5f, 0x54, 0x95, 0x6c, 0xf0, 0xf9, 0x2e,
	0x4a, 0x26, 0x10, 0xea, 0xd4, 0x14, 0x5e, 0x68, 0xef, 0xda, 0x77, 0xb2, 0xc0, 0x06, 0x9d, 0x6c,
	0xc5, 0x5d, 0x36, 0xbc, 0x35, 0xd4, 0x09, 0xb5, 0x29, 0x91, 0xc9, 0xe8, 0xa8, 0xce, 0x86, 0xb7,
	0x66, 0x9d, 0x9a, 0x62, 0xed, 0xa2, 0xe4, 0x0b, 0x18, 0x08, 0xe5, 0x15, 0x3a, 0x3a, 0xf6, 0x55,
	0xdf, 0x05, 0xc8, 0x25, 0x40, 0x5e, 0x99, 0xed, 0xf2, 0xc0, 0x2d, 0x37, 0x22, 0xe4, 0x7b, 0xe8,
	0x57, 0x48, 0x05, 0xd7, 0x11, 0x38, 0x23, 0xa6, 0x07, 0x46, 0xec, 0xd7, 0x77, 0xb6, 0xc1, 0x15,
	0xd7, 0x2f, 0x95, 0x29, 0xdf, 0xc7, 0xbd, 0xca, 0x8e, 0xc9, 0x4f, 0x70, 0xd6, 0xb4, 0x95, 0x5a,
	0xc3, 0xa3, 0x60, 0xdc, 0x9a, 0x06, 0xcb, 0xcb, 0x4f, 0x9b, 0x6a, 0x81, 0x89, 0x4f, 0xf5, 0x01,
	0x41, 0x13, 0x08, 0x4b, 0xa6, 0x68, 0x5a, 0x50, 0x51, 0x30, 0xce, 0xcb, 0xe8, 0xc4, 0x19, 0x12,
	0x94, 0x4c, 0x5d, 0x15, 0x2b, 0x17, 0x22, 0x4f, 0x60, 0xb4, 0xa7, 0xa1, 0xfa, 0x43, 0x14, 0xba,
	0xcf, 0x0a, 0x1b, 0xb2, 0xf5, 0x87, 0xf3, 0x67, 0x00, 0x1f, 0x6f, 0x6b, 0x7b, 0xe0, 0x77, 0x7c,
	0xef, 0xa8, 0xe8, 0xc6, 0x76, 0x48, 0x3e, 0x83, 0xde, 0x0d, 0xcb, 0x2a, 0x0f, 0x44, 0x37, 0xf6,
	0x93, 0xef, 0xda, 0xcf, 0x5a, 0x93, 0xbf, 0xda, 0x10, 0x6e, 0xb0, 0x89, 0xd5, 0x25, 0x04, 0x7a,
	0x61, 0xbd, 0x6d, 0x22, 0x34, 0xd0, 0x8b, 0x0d, 0x7a, 0x88, 0xbe, 0x84, 0x21, 0x7a, 0xf3, 0x5d,
	0x3f, 0x0b, 0xee, 0x50, 0x0a, 0xe3, 0x00, 0xad, 0xf5, 0xb6, 0x81, 0x57, 0xdc, 0x8a, 0xa4, 0xc4,
	0xa6, 0xc8, 0xa3, 0x14, 0x48, 0x89, 0x3b, 0xd1, 0x14, 0x46, 0x0d, 0xcb, 0x69, 0x89, 0xe9, 0xcd,
	0x96, 0x22, 0xbd, 0xf3, 0x3c, 0xc6, 0xf4, 0xe6, 0x50, 0xa9, 0x51, 0x6d, 0x41, 0x6a, 0x28, 0xd7,
	0xa8, 0x38, 0x89, 0xe1, 0x91, 0x3b, 0xb1, 0x42, 0x9a, 0xe6, 0xca, 0x58, 0xac, 0x4a, 0xcc, 0xa8,
	0xb1, 0x6f, 0x8a, 0x83, 0x2a, 0x58, 0x46, 0x87, 0x56, 0x6d, 0xdf, 0x9c, 0xf8, 0xa1, 0xdd, 0xba,
	0xc1, 0x2b, 0xbf, 0x31, 0xc6, 0xcc, 0x3f, 0x45, 0x77, 0x18, 0x3e, 0xbe, 0xc3, 0xf0, 0xe4, 0xef,
	0xb6, 0x7f, 0xbc, 0x7c, 0x8d, 0xbe, 0x85, 0x2e, 0xaa, 0x44, 0x47, 0x2d, 0xc7, 0xd9, 0xe4, 0x9e,
	0x03, 0x9d, 0xce, 0x12, 0x57, 0x13, 0xe6, 0xf4, 0xe4, 0x57, 0x08, 0xa5, 0x44, 0xc1, 0x97, 0xbe,
	0xaf, 0x78, 0xfd, 0x62, 0x7c, 0xf5, 0xc9, 0x04, 0xaf, 0x9a, 0x6a, 0x9f, 0x69, 0x3f, 0x83, 0xed,
	0x79, 0x55, 0x49, 0xea, 0xae, 0xe3, 0x8d, 0x3a, 0x52, 0x95, 0xb4, 0x07, 0x9f, 0xff, 0x06, 0x83,
	0xdd, 0x05, 0x9a, 0xd0, 0x84, 0x1e, 0x9a, 0xa7, 0x4d, 0x68, 0x82, 0xe5, 0xc5, 0x7f, 0x76, 0x4b,
	0x83, 0xa9, 0xf3, 0x1f, 0x80, 0xdc, 0xbd, 0xd7, 0x3d, 0x07, 0xec, 0x51, 0x19, 0x36, 0xa9, 0xfc,
	0xb3, 0x05, 0x81, 0x83, 0x44, 0x6a, 0xf1, 0x8a, 0x15, 0xe4, 0x2d, 0x90, 0x1a, 0x27, 0xc1, 0xa9,
	0x90, 0x5a, 0x50, 0xc9, 0x8a, 0xba, 0xba, 0xb3, 0x7b, 0x8a, 0x53, 0xef, 0xb3, 0xe5, 0xb1, 0x7d,
	0x51, 0x4f, 0x7d, 0x7d, 0x86, 0x72, 0x2f, 0x78, 0xfe, 0x1c, 0x1e, 0xdc, 0x23, 0xfb, 0x3f, 0x4d,
	0xf4, 0xe3, 0xe3, 0xb7, 0x17, 0xee, 0x0e, 0x73, 0xfb, 0xc3, 0x4b, 0xb3, 0xbc, 0xe2, 0xf3, 0xeb,
	0xbc, 0xf1, 0xe7, 0x4b, 0xfa, 0x6e, 0xfc, 0xf4, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x9b,
	0x0f, 0x11, 0x12, 0x07, 0x00, 0x00,
}
