#!/bin/bash
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This script generates certs for the proxy tier for dev and testing
set -e

TEST_MODE=$(cat /var/opt/magma/envdir/TEST_MODE || echo 0)
if [ "${TEST_MODE}" != "1" ]; then
  echo "Not running in test mode!"
  exit 0
fi

DIR='/var/opt/magma/certs'
mkdir -p ${DIR}
cd ${DIR}

# If the certs are already present (when a volume is mounted), we reuse
# the certs instead of generating it everytime.
if [ -f rootCA.pem ]; then
  echo "rootCA.pem already exists!"
  exit 0
fi

echo "##################"
echo "Creating root CA.."
echo "##################"
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 \
      -out rootCA.pem -subj "/C=US/CN=rootca.magma.test"

echo "##########################"
echo "Creating controller cert.."
echo "##########################"
openssl genrsa -out controller.key 2048
openssl req -new -key controller.key -out controller.csr \
      -subj "/C=US/CN=*.magma.test"
openssl x509 -req -in controller.csr -CA rootCA.pem -CAkey rootCA.key \
      -CAcreateserial -out controller.crt -days 36400 -sha256

if [ ! -f certifier.key ]; then
  echo "#######################"
  echo "Creating certifier CA.."
  echo "#######################"
  openssl genrsa -out certifier.key 2048
  openssl req -x509 -new -nodes -key certifier.key -sha256 -days 365000 \
        -out certifier.pem -subj "/C=US/CN=certifier.magma.test"
fi
