# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Mount magma directory
  config.vm.synced_folder "../..", "/home/vagrant/magma"

  config.vm.define :cwag, primary: true do |cwag|
    cwag.vm.box = "generic/ubuntu1804"
    cwag.disksize.size = '50GB'
    cwag.vm.box_version = "1.9.12"
    cwag.vbguest.auto_update = false
    cwag.vm.hostname = "cwag-dev"
    cwag.vm.network "private_network", ip: "192.168.70.101", nic_type: "82540EM"
    cwag.vm.network "private_network", ip: "192.168.129.23", nic_type: "82540EM"
    cwag.vm.network "private_network", ip: "192.168.40.11", nic_type: "82540EM"
    cwag.ssh.password = "vagrant"
    cwag.ssh.insert_key = true

    cwag.vm.provider "virtualbox" do |vb|
      vb.name = "cwag-dev"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.provider :libvirt do |domain, override|
      override.vm.synced_folder "../..", "/home/vagrant/magma", type: 'nfs', linux__nfs_options: ['rw','no_subtree_check','no_root_squash'], mount_options: ['nolock']
      domain.uri = "qemu+unix:///system"
      domain.memory = 4096
      domain.cpus = 4
      domain.driver = "kvm"
      domain.host = "localhost"
      domain.connect_via_ssh = false
      domain.username = $user
      domain.storage_pool_name = "default"
      domain.nic_model_type = "e1000"
      domain.management_network_name = "magma-mgmt-net"
      domain.management_network_address = "172.17.2.0/24"
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
      domain.volume_cache = "unsafe"
      domain.disk_bus = "virtio"
      domain.graphics_ip = "0.0.0.0"
    end

    cwag.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/cwag_dev.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.extra_vars = {
        ingress_port: "eth1",
        uplink_ports: "eth2 eth3",
        li_port: "eth4",
      }
      ansible.verbose = 'v'
    end
  end

  config.vm.define :cwag_centos7, primary: false do |cwag_centos7|
    # mutually exclusive with :cwag
    # INTENTIONAL IP ADDRESS CONFLICT
    cwag_centos7.vm.box = "bento/centos-7"
#    cwag_centos7.disksize.size = '50GB'
    cwag_centos7.vm.box_version = "202005.21.0"
    cwag_centos7.vbguest.auto_update = false
    cwag_centos7.vm.hostname = "cwag-dev-centos7"
    cwag_centos7.vm.network "private_network", ip: "192.168.70.101", nic_type: "82540EM"
    cwag_centos7.vm.network "private_network", ip: "192.168.129.23", nic_type: "82540EM"
    cwag_centos7.vm.network "private_network", ip: "192.168.40.11", nic_type: "82540EM"
#    cwag_centos7.ssh.password = "vagrant"
    cwag_centos7.ssh.insert_key = true

    cwag_centos7.vm.provider "virtualbox" do |vb|
      vb.name = "cwag-dev-centos7"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    cwag_centos7.vm.provision "shell",
                              inline: "yum updateinfo; yum install -y python python3 python-setuptools python3-setuptools python-pip python3-pip libselinux-python3 git"
    cwag_centos7.vm.provision "shell",
                              inline: "touch /home/vagrant/.profile"
    
    cwag_centos7.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/cwag_dev_centos7.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.verbose = 'v'
    end
  end

  config.vm.define :cwag_test, primary: true do |cwag_test|
    cwag_test.vm.box = "generic/ubuntu1804"
    cwag_test.vm.box_version = "1.9.12"
    cwag_test.vm.hostname = "cwag-test"
    cwag_test.vm.network "private_network", ip: "192.168.70.102", nic_type: "82540EM"
    cwag_test.vm.network "private_network", ip: "192.168.40.12", nic_type: "82540EM"
    cwag_test.vm.network "forwarded_port", guest: 40000, host: 40000
    cwag_test.ssh.password = "vagrant"
    cwag_test.ssh.insert_key = true

    cwag_test.vm.provider "virtualbox" do |vb|
      vb.name = "cwag-test"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    cwag_test.vm.provider :libvirt do |domain, override|
      override.vm.synced_folder "../..", "/home/vagrant/magma", type: 'nfs', linux__nfs_options: ['rw','no_subtree_check','no_root_squash'], mount_options: ['nolock']
      domain.uri = "qemu+unix:///system"
      domain.memory = 4096
      domain.cpus = 4
      domain.driver = "kvm"
      domain.host = "localhost"
      domain.connect_via_ssh = false
      domain.username = $user
      domain.storage_pool_name = "default"
      domain.nic_model_type = "e1000"
      domain.management_network_name = "magma-mgmt-net"
      domain.management_network_address = "172.17.2.0/24"
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
      domain.volume_cache = "unsafe"
      domain.disk_bus = "virtio"
      domain.graphics_ip = "0.0.0.0"
    end

    cwag_test.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/cwag_test.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.verbose = 'v'
    end
  end
end
