# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (c) 2018-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Mount magma directory
  config.vm.synced_folder "../..", "/home/vagrant/magma"

  config.vm.define :cwag, primary: true do |cwag|
    cwag.vm.box = "generic/ubuntu1804"
    cwag.disksize.size = '50GB'
    cwag.vm.box_version = "1.9.12"
    cwag.vbguest.auto_update = false
    cwag.vm.hostname = "cwag-dev"
    cwag.vm.network "private_network", ip: "192.168.70.101", nic_type: "82540EM"
    cwag.vm.network "private_network", ip: "192.168.129.23", nic_type: "82540EM"
    cwag.vm.network "private_network", ip: "192.168.40.11", nic_type: "82540EM"
    cwag.ssh.password = "vagrant"
    cwag.ssh.insert_key = true

    cwag.vm.provider "virtualbox" do |vb|
      vb.name = "cwag-dev"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    cwag.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/cwag_dev.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.verbose = 'v'
    end
  end

  config.vm.define :cwag_test, primary: true do |cwag_test|
    cwag_test.vm.box = "generic/ubuntu1804"
    cwag_test.vm.box_version = "1.9.12"
    cwag_test.vm.hostname = "cwag-test"
    cwag_test.vm.network "private_network", ip: "192.168.70.102", nic_type: "82540EM"
    cwag_test.vm.network "private_network", ip: "192.168.40.12", nic_type: "82540EM"
    cwag_test.vm.network "forwarded_port", guest: 40000, host: 40000
    cwag_test.ssh.password = "vagrant"
    cwag_test.ssh.insert_key = true

    cwag_test.vm.provider "virtualbox" do |vb|
      vb.name = "cwag-test"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    cwag_test.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/cwag_test.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.verbose = 'v'
    end
  end
end
