// Code generated by go-swagger; DO NOT EDIT.

package federated_lte_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"magma/orc8r/cloud/api/v1/go/models"
)

// NewPostFegLTEParams creates a new PostFegLTEParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostFegLTEParams() *PostFegLTEParams {
	return &PostFegLTEParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostFegLTEParamsWithTimeout creates a new PostFegLTEParams object
// with the ability to set a timeout on a request.
func NewPostFegLTEParamsWithTimeout(timeout time.Duration) *PostFegLTEParams {
	return &PostFegLTEParams{
		timeout: timeout,
	}
}

// NewPostFegLTEParamsWithContext creates a new PostFegLTEParams object
// with the ability to set a context for a request.
func NewPostFegLTEParamsWithContext(ctx context.Context) *PostFegLTEParams {
	return &PostFegLTEParams{
		Context: ctx,
	}
}

// NewPostFegLTEParamsWithHTTPClient creates a new PostFegLTEParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostFegLTEParamsWithHTTPClient(client *http.Client) *PostFegLTEParams {
	return &PostFegLTEParams{
		HTTPClient: client,
	}
}

/* PostFegLTEParams contains all the parameters to send to the API endpoint
   for the post feg LTE operation.

   Typically these are written to a http.Request.
*/
type PostFegLTEParams struct {

	/* LTENetwork.

	   Configuration of the network to create
	*/
	LTENetwork *models.FegLTENetwork

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post feg LTE params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFegLTEParams) WithDefaults() *PostFegLTEParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post feg LTE params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFegLTEParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post feg LTE params
func (o *PostFegLTEParams) WithTimeout(timeout time.Duration) *PostFegLTEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post feg LTE params
func (o *PostFegLTEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post feg LTE params
func (o *PostFegLTEParams) WithContext(ctx context.Context) *PostFegLTEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post feg LTE params
func (o *PostFegLTEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post feg LTE params
func (o *PostFegLTEParams) WithHTTPClient(client *http.Client) *PostFegLTEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post feg LTE params
func (o *PostFegLTEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLTENetwork adds the lTENetwork to the post feg LTE params
func (o *PostFegLTEParams) WithLTENetwork(lTENetwork *models.FegLTENetwork) *PostFegLTEParams {
	o.SetLTENetwork(lTENetwork)
	return o
}

// SetLTENetwork adds the lteNetwork to the post feg LTE params
func (o *PostFegLTEParams) SetLTENetwork(lTENetwork *models.FegLTENetwork) {
	o.LTENetwork = lTENetwork
}

// WriteToRequest writes these params to a swagger request
func (o *PostFegLTEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.LTENetwork != nil {
		if err := r.SetBodyParam(o.LTENetwork); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
