// Code generated by go-swagger; DO NOT EDIT.

package carrier_wifi_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCwfNetworkIDParams creates a new DeleteCwfNetworkIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCwfNetworkIDParams() *DeleteCwfNetworkIDParams {
	return &DeleteCwfNetworkIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCwfNetworkIDParamsWithTimeout creates a new DeleteCwfNetworkIDParams object
// with the ability to set a timeout on a request.
func NewDeleteCwfNetworkIDParamsWithTimeout(timeout time.Duration) *DeleteCwfNetworkIDParams {
	return &DeleteCwfNetworkIDParams{
		timeout: timeout,
	}
}

// NewDeleteCwfNetworkIDParamsWithContext creates a new DeleteCwfNetworkIDParams object
// with the ability to set a context for a request.
func NewDeleteCwfNetworkIDParamsWithContext(ctx context.Context) *DeleteCwfNetworkIDParams {
	return &DeleteCwfNetworkIDParams{
		Context: ctx,
	}
}

// NewDeleteCwfNetworkIDParamsWithHTTPClient creates a new DeleteCwfNetworkIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCwfNetworkIDParamsWithHTTPClient(client *http.Client) *DeleteCwfNetworkIDParams {
	return &DeleteCwfNetworkIDParams{
		HTTPClient: client,
	}
}

/* DeleteCwfNetworkIDParams contains all the parameters to send to the API endpoint
   for the delete cwf network ID operation.

   Typically these are written to a http.Request.
*/
type DeleteCwfNetworkIDParams struct {

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cwf network ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCwfNetworkIDParams) WithDefaults() *DeleteCwfNetworkIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cwf network ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCwfNetworkIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) WithTimeout(timeout time.Duration) *DeleteCwfNetworkIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) WithContext(ctx context.Context) *DeleteCwfNetworkIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) WithHTTPClient(client *http.Client) *DeleteCwfNetworkIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) WithNetworkID(networkID string) *DeleteCwfNetworkIDParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the delete cwf network ID params
func (o *DeleteCwfNetworkIDParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCwfNetworkIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
