// Code generated by go-swagger; DO NOT EDIT.

package lte_networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// PutLTENetworkIDCellularEpcReader is a Reader for the PutLTENetworkIDCellularEpc structure.
type PutLTENetworkIDCellularEpcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLTENetworkIDCellularEpcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutLTENetworkIDCellularEpcNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutLTENetworkIDCellularEpcDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutLTENetworkIDCellularEpcNoContent creates a PutLTENetworkIDCellularEpcNoContent with default headers values
func NewPutLTENetworkIDCellularEpcNoContent() *PutLTENetworkIDCellularEpcNoContent {
	return &PutLTENetworkIDCellularEpcNoContent{}
}

/*PutLTENetworkIDCellularEpcNoContent handles this case with default header values.

Success
*/
type PutLTENetworkIDCellularEpcNoContent struct {
}

func (o *PutLTENetworkIDCellularEpcNoContent) Error() string {
	return fmt.Sprintf("[PUT /lte/{network_id}/cellular/epc][%d] putLteNetworkIdCellularEpcNoContent ", 204)
}

func (o *PutLTENetworkIDCellularEpcNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutLTENetworkIDCellularEpcDefault creates a PutLTENetworkIDCellularEpcDefault with default headers values
func NewPutLTENetworkIDCellularEpcDefault(code int) *PutLTENetworkIDCellularEpcDefault {
	return &PutLTENetworkIDCellularEpcDefault{
		_statusCode: code,
	}
}

/*PutLTENetworkIDCellularEpcDefault handles this case with default header values.

Unexpected Error
*/
type PutLTENetworkIDCellularEpcDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put LTE network ID cellular epc default response
func (o *PutLTENetworkIDCellularEpcDefault) Code() int {
	return o._statusCode
}

func (o *PutLTENetworkIDCellularEpcDefault) Error() string {
	return fmt.Sprintf("[PUT /lte/{network_id}/cellular/epc][%d] PutLTENetworkIDCellularEpc default  %+v", o._statusCode, o.Payload)
}

func (o *PutLTENetworkIDCellularEpcDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutLTENetworkIDCellularEpcDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
