// Code generated by go-swagger; DO NOT EDIT.

package federation_gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "magma/orc8r/cloud/go/obsidian/swagger/v1/models"
)

// DeleteFegNetworkIDGatewaysGatewayIDFederationReader is a Reader for the DeleteFegNetworkIDGatewaysGatewayIDFederation structure.
type DeleteFegNetworkIDGatewaysGatewayIDFederationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteFegNetworkIDGatewaysGatewayIDFederationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteFegNetworkIDGatewaysGatewayIDFederationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteFegNetworkIDGatewaysGatewayIDFederationNoContent creates a DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent with default headers values
func NewDeleteFegNetworkIDGatewaysGatewayIDFederationNoContent() *DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent {
	return &DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent{}
}

/*DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent handles this case with default header values.

Success
*/
type DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent struct {
}

func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent) Error() string {
	return fmt.Sprintf("[DELETE /feg/{network_id}/gateways/{gateway_id}/federation][%d] deleteFegNetworkIdGatewaysGatewayIdFederationNoContent ", 204)
}

func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFegNetworkIDGatewaysGatewayIDFederationDefault creates a DeleteFegNetworkIDGatewaysGatewayIDFederationDefault with default headers values
func NewDeleteFegNetworkIDGatewaysGatewayIDFederationDefault(code int) *DeleteFegNetworkIDGatewaysGatewayIDFederationDefault {
	return &DeleteFegNetworkIDGatewaysGatewayIDFederationDefault{
		_statusCode: code,
	}
}

/*DeleteFegNetworkIDGatewaysGatewayIDFederationDefault handles this case with default header values.

Unexpected Error
*/
type DeleteFegNetworkIDGatewaysGatewayIDFederationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete feg network ID gateways gateway ID federation default response
func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationDefault) Code() int {
	return o._statusCode
}

func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationDefault) Error() string {
	return fmt.Sprintf("[DELETE /feg/{network_id}/gateways/{gateway_id}/federation][%d] DeleteFegNetworkIDGatewaysGatewayIDFederation default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteFegNetworkIDGatewaysGatewayIDFederationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
