#!/bin/bash

# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

set -e

# Install ansible so that we can provision the hosts
# Also install daemontools for envdir
apt-add-repository -y ppa:ansible/ansible
apt-get -y update
apt-get -y install ansible daemontools

# Run the ansible script
envdir /var/opt/magma/envdir ansible-playbook /var/opt/magma/ansible/main.yml -i "localhost," -c local -v &> /tmp/ansible.log

# Cleanup the scipts after running
rm -rf /var/opt/magma/ansible
