# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "= 201808.24.0"

  config.vm.define :metrics, autostart: false do |metrics|
    metrics.vm.hostname = "magma-metrics"
    metrics.vm.network "private_network", ip: "192.168.80.50"
    metrics.vm.network "forwarded_port", guest: 9090, host: 9090
    metrics.vm.network "forwarded_port", guest: 9091, host: 9091

    metrics.ssh.password = "vagrant"
    metrics.ssh.insert_key = true

    metrics.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy/metrics.dev.yml"
      ansible.verbose = true
    end

    metrics.vm.synced_folder "../../../magma", "/home/vagrant/magma"

    metrics.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end
  end

end
