/*
   Copyright 2020 The Magma Authors.
   This source code is licensed under the BSD-style license found in the
   LICENSE file in the root directory of this source tree.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

#pragma once
namespace magma5g {
#define M5G_SESSION_MANAGEMENT_MESSAGES 0x2e
#define M5G_MOBILITY_MANAGEMENT_MESSAGES 0x7e
// 5G Mobility Management Message Types
#define REG_REQUEST 0x41
#define REG_ACCEPT 0x42
#define REG_COMPLETE 0x43
#define REG_REJECT 0x44
#define DE_REG_REQUEST_UE_ORIGIN 0x45
#define DE_REG_ACCEPT_UE_ORIGIN 0x46
#define DE_REG_REQUEST_UE_TERM 0x47
#define DE_REG_ACCEPT_UE_TERM 0x48
#define M5G_SERVICE_REQUEST 0x4c
#define M5G_SERVICE_REJECT 0x4d
#define M5G_SERVICE_ACCEPT 0x4e
#define CONFIGURATION_UPDATE_COMMAND 0x54
#define CONFIGURATION_UPDATE_COMPLETE 0x55
#define AUTH_REQUEST 0x56
#define AUTH_RESPONSE 0x57
#define AUTH_REJECT 0x58
#define AUTH_FAILURE 0x59
#define AUTH_RESULT 0x5a
#define M5G_IDENTITY_REQUEST 0x5b
#define M5G_IDENTITY_RESPONSE 0x5c
#define SEC_MODE_COMMAND 0x5d
#define SEC_MODE_COMPLETE 0x5e
#define SEC_MODE_REJECT 0x5f
#define NOTIFICATION 0x65
#define NOTIFICATION_RESPONSE 0x66
#define ULNASTRANSPORT 0x67
#define DLNASTRANSPORT 0x68
// IEI for Mobility Management Message
#define M5GS_MOBILE_IDENTITY 0X77
#define PLMN_LIST 0x4a
#define TAI_LIST 0x54
#define ALLOWED_NSSAI 0x15
#define REJECTED_NSSAI 0x11
#define M5GS_NETWORK_FEATURE_SUPPORT 0X21
#define PDU_SESSION_STATUS 0x50
#define PDU_SESSION_REACTIVATION_RESULT 0x26
#define PDU_SESSION_REACTIVATION_RESULT_ERROR 0X72
#define LADN_INFORMATION 0x79
#define MICO_INDICATION 0xB0
#define NETWORK_SLICING_INDICATION 0x90
#define SERVICE_AREA_LIST 0X27
#define GPRS_TIMER3 0x5E
#define GPRS_TIMER2 0x5D
#define EMERGENCY_NUMBER_LIST 0x34
#define EXTENDED_NUMBER_EMERGENCY_LIST 0x7A
#define SOR_TRANSPARANT_CONTAINER 0x73
#define EAP_MESSAGE 0x78
#define NSSAI_INCLUSION_MODE 0xA0
#define OPERATOR_DEFINED_ACCESS_CATEGORY_DEF 0x76
#define M5GS_DRX_PARAMETERS 0x51
#define NON_3GPP_NW_PROVIDED_POLICIES 0xD0
#define EPS_BEARER_CONTEXT_STATUS 0x60
#define NAS_KEY_IDENTIFIER 0xC0
#define M5GMM_CAPABILITY 0x10
#define UE_SECURITY_CAPABILITY 0x2E
#define S1_UE_NETWORK_CAPABILITY 0X17
#define REQUESTED_NSSAI 0x2F
#define UP_LINK_DATA_STATUS 0x40
#define UE_STATUS 0x2B
#define ALLOWED_PDU_SESSION_STATUS 0x25
#define UE_USSAGE_SETTING 0x18
#define EPS_NAS_MESSAGE_CONTAINER 0x70
#define PAYLOAD_CONTAINER_TYPE 0X80
#define PAYLOAD_CONTAINER 0x7B
#define M5GS_UPDATE_TYPE 0x53
#define NAS_MESSAGE_CONTAINER 0x71
#define TAI 0x52
#define AUTH_PARAM_RAND 0x21
#define AUTH_PARAM_AUTN 0x20
#define AUTH_RESPONSE_PARAMETER 0x2D
// 5G Session Management Message Types
#define PDU_SESSION_ESTABLISHMENT_REQUEST 0xC1
#define PDU_SESSION_ESTABLISHMENT_ACCEPT 0xC2
#define PDU_SESSION_ESTABLISHMENT_REJECT 0xC3
#define PDU_SESSION_RELEASE_REQUEST 0xD1
#define PDU_SESSION_RELEASE_REJECT 0xD2
#define PDU_SESSION_MODIFICATION_REQUEST 0xC9
#define PDU_SESSION_MODIFICATION_REJECT 0xCA
// 5G Session Management IE Types
#define PDU_SESSION_TYPE 0x09
#define PDU_SESSION_IDENTITY 0x12
#define SSC_MODE 0x0A
#define M5GSM_CAUSE 0x59
#define PDU_ADDRESS 0x29
#define DNN 0x25
// IE field values
#define M5GS_REGISTRATION_RESULT_MAXIMUM_LENGTH 1
#define M5GSMobileIdentityMsg_GUTI 0x02
#define M3GPP_ACCESS 1
#define NON_M3GPP_ACCESS 2
#define M3GPP_ACCESS_AND_NON_3GPP_ACCESS 3
#define NOT_ALLOWED 0
#define ALLOWED 1
#define EVEN_IDENTITY_DIGITS 0
#define ODD_IDENTITY_DIGITS 1
#define M5G_IDENTITY_SUCI 1
#define IMSI_LENGTH 15
#define NATIVE_SECURITY_CONTEXT 0
#define MAPPED_SECURITY_CONTEXT 1
}  // namespace magma5g
