#!/bin/sh /etc/rc.common
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck disable=SC1091,SC2034
START=98
CMD="radius"
FLGS="-stderr2syslog -stdout2stderr -config /etc/magma/configs/radius.config.json -log_fmt console"
. /etc/init.d/magma.template
