#!/bin/bash
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This script generates rooCA.pem needed for cloud and gateway communication

set -e

if [ $# -eq 0 ]
then
  echo "Usage: $0 <output_dir>"
  exit 1
fi

cd "$1"

if [ ! -f rootCA.pem ]; then
  echo "#################"
  echo "Creating root CA.."
  echo "#################"
  openssl genrsa -out rootCA.key 2048
  openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 -out rootCA.pem \
         -subj "/C=US/CN=rootca.magma.test"
fi
