#!/bin/bash
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script generates rooCA.pem needed for cloud and gateway communication

set -e

if [ $# -eq 0 ]
then
  echo "Usage: $0 <output_dir>"
  exit 1
fi

cd "$1"

if [ ! -f rootCA.pem ]; then
  echo "#################"
  echo "Creating root CA.."
  echo "#################"
  openssl genrsa -out rootCA.key 2048
  openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 -out rootCA.pem \
         -subj "/C=US/CN=rootca.magma.test"
fi
