#!/bin/bash

for e in $(tr "\000" "\n" < /proc/1/environ); do
  eval "export $e"
done

if [ -z "${SNOWFLAKE}" ]; then
  SNOWFLAKE="faceb00c-face-b00c-face-fbb05fbcface"
fi

if [ -z "${CLOUD_ADDRESS}" ]; then
  CLOUD_ADDRESS="controller.magma.etagecom.io"
fi

if [ -z "${BOOTSTRAP_CLOUD_ADDRESS}" ]; then
  BOOTSTRAP_CLOUD_ADDRESS="bootstrapper-controller.magma.etagecom.io"
fi

echo ${SNOWFLAKE} > /etc/snowflake
sed -i -E -e "s!%%bootstrap_cloud_address%%!${BOOTSTRAP_CLOUD_ADDRESS}!g" \
    -e "s!%%cloud_address%%!${CLOUD_ADDRESS}!g" \
    /etc/magma/control_proxy.yml

echo "System prepared with ${SNOWFLAKE}/${CLOUD_ADDRESS}/${BOOTSTRAP_CLOUD_ADDRESS}"
