# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder "../..", "/home/vagrant/magma"
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define :example, primary: true do |example|
    example.vm.hostname = "example-dev"
    example.vm.network "private_network", ip: "192.168.30.10"
    example.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/example.dev.yml"
      ansible.limit = "all"
      ansible.verbose = true
    end
  end

end
