#!/bin/bash
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This script generates certs for the controller tier for dev and testing
set -e

if [ "$TEST_MODE" != "1" ]; then
  echo "Not running in test mode!"
  exit 0
fi

DIR='/var/opt/magma/certs'
mkdir -p ${DIR}
cd ${DIR}

if [ ! -f bootstrapper.key ]; then
  echo "###########################"
  echo "Creating bootstrapper key.."
  echo "###########################"
  openssl genrsa -out bootstrapper.key 2048
fi

if [ ! -f certifier.key ]; then
  echo "#######################"
  echo "Creating certifier CA.."
  echo "#######################"
  openssl genrsa -out certifier.key 2048
  openssl req -x509 -new -nodes -key certifier.key -sha256 -days 365000 \
        -out certifier.pem -subj "/C=US/CN=certifier.magma.test"
fi

if [ ! -f vpn_ca.key ]; then
  echo "#################"
  echo "Creating VPN CA.."
  echo "#################"
  openssl genrsa -out vpn_ca.key 2048
  openssl req -x509 -new -nodes -key vpn_ca.key -sha256 -days 365000 \
        -out vpn_ca.crt -subj "/C=US/CN=vpn.magma.test"
fi

echo "Waiting for datastore to come up..."
timeout 20 bash -c 'until nc -z datastore 5432; do sleep 1; done'

ACCESSC='/var/opt/magma/bin/accessc'
if [ -f admin_operator.pfx ]; then
  echo "##########################"
  echo "Add existing admin certs.."
  echo "##########################"
  ${ACCESSC} add-existing -admin -cert admin_operator.pem admin_operator
else
  echo "####################"
  echo "Create admin certs.."
  echo "####################"
  ${ACCESSC} add-admin -cert admin_operator admin_operator
  openssl pkcs12 -passout pass:magma -export -out admin_operator.pfx \
        -inkey admin_operator.key.pem -in admin_operator.pem
fi
