/**
 * Copyright 2020 The Magma Authors.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdint.h>
#include <sys/types.h>

#include "asn_internal.h"
#include "constr_TYPE.h"

struct ngap_message_s;
#if HAVE_CONFIG_H_
#include "config.h"
#endif

#pragma once

#include "bstrlib.h"

/* Defined in asn_internal.h */
extern int asn_debug;

#if defined(EMIT_ASN_DEBUG_EXTERN)
inline void ASN_DEBUG(const char* fmt, ...);
#endif

#include "ANY.h"
#include "asn_application.h"
#include "asn_bit_data.h"
#include "asn_codecs.h"
#include "asn_codecs_prim.h"
#include "asn_internal.h"
#include "asn_ioc.h"
#include "asn_random_fill.h"
#include "asn_SEQUENCE_OF.h"
#include "asn_SET_OF.h"
#include "asn_system.h"
#include "ber_decoder.h"
#include "ber_tlv_length.h"
#include "ber_tlv_tag.h"
#include "BIT_STRING.h"
#include "constraints.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SET_OF.h"
#include "constr_TYPE.h"
#include "der_encoder.h"
#include "INTEGER.h"
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "Ngap_AdditionalDLUPTNLInformationForHOItem.h"
#include "Ngap_AdditionalDLUPTNLInformationForHOList.h"
#include "Ngap_AdditionalQosFlowInformation.h"
#include "Ngap_AllocationAndRetentionPriority.h"
#include "Ngap_AllowedNSSAI.h"
#include "Ngap_AllowedNSSAI-Item.h"
#include "Ngap_AllowedTACs.h"
#include "Ngap_AMFConfigurationUpdateAcknowledge.h"
#include "Ngap_AMFConfigurationUpdateFailure.h"
#include "Ngap_AMFConfigurationUpdate.h"
#include "Ngap_AMFName.h"
#include "Ngap_AMFPagingTarget.h"
#include "Ngap_AMFPointer.h"
#include "Ngap_AMFRegionID.h"
#include "Ngap_AMFSetID.h"
#include "Ngap_AMFStatusIndication.h"
#include "Ngap_AMF-TNLAssociationSetupItem.h"
#include "Ngap_AMF-TNLAssociationSetupList.h"
#include "Ngap_AMF-TNLAssociationToAddItem.h"
#include "Ngap_AMF-TNLAssociationToAddList.h"
#include "Ngap_AMF-TNLAssociationToRemoveItem.h"
#include "Ngap_AMF-TNLAssociationToRemoveList.h"
#include "Ngap_AMF-TNLAssociationToUpdateItem.h"
#include "Ngap_AMF-TNLAssociationToUpdateList.h"
#include "Ngap_AMF-UE-NGAP-ID.h"
#include "Ngap_AreaOfInterestCellItem.h"
#include "Ngap_AreaOfInterestCellList.h"
#include "Ngap_AreaOfInterest.h"
#include "Ngap_AreaOfInterestItem.h"
#include "Ngap_AreaOfInterestList.h"
#include "Ngap_AreaOfInterestRANNodeItem.h"
#include "Ngap_AreaOfInterestRANNodeList.h"
#include "Ngap_AreaOfInterestTAIItem.h"
#include "Ngap_AreaOfInterestTAIList.h"
#include "Ngap_asn_constant.h"
#include "Ngap_AssistanceDataForPaging.h"
#include "Ngap_AssistanceDataForRecommendedCells.h"
#include "Ngap_AssociatedQosFlowItem.h"
#include "Ngap_AssociatedQosFlowList.h"
#include "Ngap_AveragingWindow.h"
#include "Ngap_BitRate.h"
#include "Ngap_BroadcastCancelledAreaList.h"
#include "Ngap_BroadcastCompletedAreaList.h"
#include "Ngap_BroadcastPLMNItem.h"
#include "Ngap_BroadcastPLMNList.h"
#include "Ngap_CancelAllWarningMessages.h"
#include "Ngap_CancelledCellsInEAI-EUTRA.h"
#include "Ngap_CancelledCellsInEAI-EUTRA-Item.h"
#include "Ngap_CancelledCellsInEAI-NR.h"
#include "Ngap_CancelledCellsInEAI-NR-Item.h"
#include "Ngap_CancelledCellsInTAI-EUTRA.h"
#include "Ngap_CancelledCellsInTAI-EUTRA-Item.h"
#include "Ngap_CancelledCellsInTAI-NR.h"
#include "Ngap_CancelledCellsInTAI-NR-Item.h"
#include "Ngap_Cause.h"
#include "Ngap_CauseMisc.h"
#include "Ngap_CauseNas.h"
#include "Ngap_CauseProtocol.h"
#include "Ngap_CauseRadioNetwork.h"
#include "Ngap_CauseTransport.h"
#include "Ngap_CellIDBroadcastEUTRA.h"
#include "Ngap_CellIDBroadcastEUTRA-Item.h"
#include "Ngap_CellIDBroadcastNR.h"
#include "Ngap_CellIDBroadcastNR-Item.h"
#include "Ngap_CellIDCancelledEUTRA.h"
#include "Ngap_CellIDCancelledEUTRA-Item.h"
#include "Ngap_CellIDCancelledNR.h"
#include "Ngap_CellIDCancelledNR-Item.h"
#include "Ngap_CellIDListForRestart.h"
#include "Ngap_CellSize.h"
#include "Ngap_CellTrafficTrace.h"
#include "Ngap_CellType.h"
#include "Ngap_CNAssistedRANTuning.h"
#include "Ngap_CNTypeRestrictionsForEquivalent.h"
#include "Ngap_CNTypeRestrictionsForEquivalentItem.h"
#include "Ngap_CNTypeRestrictionsForServing.h"
#include "Ngap_CommonNetworkInstance.h"
#include "Ngap_CompletedCellsInEAI-EUTRA.h"
#include "Ngap_CompletedCellsInEAI-EUTRA-Item.h"
#include "Ngap_CompletedCellsInEAI-NR.h"
#include "Ngap_CompletedCellsInEAI-NR-Item.h"
#include "Ngap_CompletedCellsInTAI-EUTRA.h"
#include "Ngap_CompletedCellsInTAI-EUTRA-Item.h"
#include "Ngap_CompletedCellsInTAI-NR.h"
#include "Ngap_CompletedCellsInTAI-NR-Item.h"
#include "Ngap_ConcurrentWarningMessageInd.h"
#include "Ngap_ConfidentialityProtectionIndication.h"
#include "Ngap_ConfidentialityProtectionResult.h"
#include "Ngap_ConfiguredNSSAI.h"
#include "Ngap_CoreNetworkAssistanceInformationForInactive.h"
#include "Ngap_COUNTValueForPDCP-SN12.h"
#include "Ngap_COUNTValueForPDCP-SN18.h"
#include "Ngap_CPTransportLayerInformation.h"
#include "Ngap_CriticalityDiagnostics.h"
#include "Ngap_CriticalityDiagnostics-IE-Item.h"
#include "Ngap_CriticalityDiagnostics-IE-List.h"
#include "Ngap_Criticality.h"
#include "Ngap_DataCodingScheme.h"
#include "Ngap_DataForwardingAccepted.h"
#include "Ngap_DataForwardingNotPossible.h"
#include "Ngap_DataForwardingResponseDRBItem.h"
#include "Ngap_DataForwardingResponseDRBList.h"
#include "Ngap_DataForwardingResponseERABList.h"
#include "Ngap_DataForwardingResponseERABListItem.h"
#include "Ngap_DeactivateTrace.h"
#include "Ngap_DelayCritical.h"
#include "Ngap_DirectForwardingPathAvailability.h"
#include "Ngap_DLForwarding.h"
#include "Ngap_DL-NGU-TNLInformationReused.h"
#include "Ngap_DownlinkNASTransport.h"
#include "Ngap_DownlinkNonUEAssociatedNRPPaTransport.h"
#include "Ngap_DownlinkRANConfigurationTransfer.h"
#include "Ngap_DownlinkRANStatusTransfer.h"
#include "Ngap_DownlinkRIMInformationTransfer.h"
#include "Ngap_DownlinkUEAssociatedNRPPaTransport.h"
#include "Ngap_DRB-ID.h"
#include "Ngap_DRBsSubjectToStatusTransferItem.h"
#include "Ngap_DRBsSubjectToStatusTransferList.h"
#include "Ngap_DRBStatusDL12.h"
#include "Ngap_DRBStatusDL18.h"
#include "Ngap_DRBStatusDL.h"
#include "Ngap_DRBStatusUL12.h"
#include "Ngap_DRBStatusUL18.h"
#include "Ngap_DRBStatusUL.h"
#include "Ngap_DRBsToQosFlowsMappingItem.h"
#include "Ngap_DRBsToQosFlowsMappingList.h"
#include "Ngap_Dynamic5QIDescriptor.h"
#include "Ngap_EmergencyAreaIDBroadcastEUTRA.h"
#include "Ngap_EmergencyAreaIDBroadcastEUTRA-Item.h"
#include "Ngap_EmergencyAreaIDBroadcastNR.h"
#include "Ngap_EmergencyAreaIDBroadcastNR-Item.h"
#include "Ngap_EmergencyAreaIDCancelledEUTRA.h"
#include "Ngap_EmergencyAreaIDCancelledEUTRA-Item.h"
#include "Ngap_EmergencyAreaIDCancelledNR.h"
#include "Ngap_EmergencyAreaIDCancelledNR-Item.h"
#include "Ngap_EmergencyAreaID.h"
#include "Ngap_EmergencyAreaIDListForRestart.h"
#include "Ngap_EmergencyAreaIDList.h"
#include "Ngap_EmergencyFallbackIndicator.h"
#include "Ngap_EmergencyFallbackRequestIndicator.h"
#include "Ngap_EmergencyServiceTargetCN.h"
#include "Ngap_EN-DCSONConfigurationTransfer.h"
#include "Ngap_EndpointIPAddressAndPort.h"
#include "Ngap_EPS-TAC.h"
#include "Ngap_EPS-TAI.h"
#include "Ngap_EquivalentPLMNs.h"
#include "Ngap_E-RAB-ID.h"
#include "Ngap_E-RABInformationItem.h"
#include "Ngap_E-RABInformationList.h"
#include "Ngap_ErrorIndication.h"
#include "Ngap_EUTRACellIdentity.h"
#include "Ngap_EUTRA-CGI.h"
#include "Ngap_EUTRA-CGIListForWarning.h"
#include "Ngap_EUTRA-CGIList.h"
#include "Ngap_EUTRAencryptionAlgorithms.h"
#include "Ngap_EUTRAintegrityProtectionAlgorithms.h"
#include "Ngap_EventType.h"
#include "Ngap_ExpectedActivityPeriod.h"
#include "Ngap_ExpectedHOInterval.h"
#include "Ngap_ExpectedIdlePeriod.h"
#include "Ngap_ExpectedUEActivityBehaviour.h"
#include "Ngap_ExpectedUEBehaviour.h"
#include "Ngap_ExpectedUEMobility.h"
#include "Ngap_ExpectedUEMovingTrajectory.h"
#include "Ngap_ExpectedUEMovingTrajectoryItem.h"
#include "Ngap_FiveG-S-TMSI.h"
#include "Ngap_FiveG-TMSI.h"
#include "Ngap_FiveQI.h"
#include "Ngap_ForbiddenAreaInformation.h"
#include "Ngap_ForbiddenAreaInformation-Item.h"
#include "Ngap_ForbiddenTACs.h"
#include "Ngap_GBR-QosInformation.h"
#include "Ngap_GlobalGNB-ID.h"
#include "Ngap_GlobalN3IWF-ID.h"
#include "Ngap_GlobalNgENB-ID.h"
#include "Ngap_GlobalRANNodeID.h"
#include "Ngap_GNB-ID.h"
#include "Ngap_GNBSetID.h"
#include "Ngap_GTP-TEID.h"
#include "Ngap_GTPTunnel.h"
#include "Ngap_GUAMI.h"
#include "Ngap_GUAMIType.h"
#include "Ngap_HandoverCancelAcknowledge.h"
#include "Ngap_HandoverCancel.h"
#include "Ngap_HandoverCommand.h"
#include "Ngap_HandoverCommandTransfer.h"
#include "Ngap_HandoverFailure.h"
#include "Ngap_HandoverFlag.h"
#include "Ngap_HandoverNotify.h"
#include "Ngap_HandoverPreparationFailure.h"
#include "Ngap_HandoverPreparationUnsuccessfulTransfer.h"
#include "Ngap_HandoverRequestAcknowledge.h"
#include "Ngap_HandoverRequestAcknowledgeTransfer.h"
#include "Ngap_HandoverRequest.h"
#include "Ngap_HandoverRequired.h"
#include "Ngap_HandoverRequiredTransfer.h"
#include "Ngap_HandoverResourceAllocationUnsuccessfulTransfer.h"
#include "Ngap_HandoverType.h"
#include "Ngap_IMSVoiceSupportIndicator.h"
#include "Ngap_IndexToRFSP.h"
#include "Ngap_InfoOnRecommendedCellsAndRANNodesForPaging.h"
#include "Ngap_InitialContextSetupFailure.h"
#include "Ngap_InitialContextSetupRequest.h"
#include "Ngap_InitialContextSetupResponse.h"
#include "Ngap_InitialUEMessage.h"
#include "Ngap_InitiatingMessage.h"
#include "Ngap_IntegrityProtectionIndication.h"
#include "Ngap_IntegrityProtectionResult.h"
#include "Ngap_IntendedNumberOfPagingAttempts.h"
#include "Ngap_InterfacesToTrace.h"
#include "Ngap_LastVisitedCellInformation.h"
#include "Ngap_LastVisitedCellItem.h"
#include "Ngap_LastVisitedEUTRANCellInformation.h"
#include "Ngap_LastVisitedGERANCellInformation.h"
#include "Ngap_LastVisitedNGRANCellInformation.h"
#include "Ngap_LastVisitedUTRANCellInformation.h"
#include "Ngap_LocationReport.h"
#include "Ngap_LocationReportingAdditionalInfo.h"
#include "Ngap_LocationReportingControl.h"
#include "Ngap_LocationReportingFailureIndication.h"
#include "Ngap_LocationReportingReferenceID.h"
#include "Ngap_LocationReportingRequestType.h"
#include "Ngap_MaskedIMEISV.h"
#include "Ngap_MaximumDataBurstVolume.h"
#include "Ngap_MaximumIntegrityProtectedDataRate.h"
#include "Ngap_MessageIdentifier.h"
#include "Ngap_MICOModeIndication.h"
#include "Ngap_MobilityRestrictionList.h"
#include "Ngap_N3IWF-ID.h"
#include "Ngap_NASNonDeliveryIndication.h"
#include "Ngap_NAS-PDU.h"
#include "Ngap_NASSecurityParametersFromNGRAN.h"
#include "Ngap_NetworkInstance.h"
#include "Ngap_NewSecurityContextInd.h"
#include "Ngap_NextHopChainingCount.h"
#include "Ngap_NextPagingAreaScope.h"
#include "Ngap_NGAP-PDU.h"
#include "Ngap_NgENB-ID.h"
#include "Ngap_NGRAN-CGI.h"
#include "Ngap_NGRAN-TNLAssociationToRemoveItem.h"
#include "Ngap_NGRAN-TNLAssociationToRemoveList.h"
#include "Ngap_NGRANTraceID.h"
#include "Ngap_NGResetAcknowledge.h"
#include "Ngap_NGReset.h"
#include "Ngap_NGSetupFailure.h"
#include "Ngap_NGSetupRequest.h"
#include "Ngap_NGSetupResponse.h"
#include "Ngap_NonDynamic5QIDescriptor.h"
#include "Ngap_NotAllowedTACs.h"
#include "Ngap_NotificationCause.h"
#include "Ngap_NotificationControl.h"
#include "Ngap_NRCellIdentity.h"
#include "Ngap_NR-CGI.h"
#include "Ngap_NR-CGIListForWarning.h"
#include "Ngap_NR-CGIList.h"
#include "Ngap_NRencryptionAlgorithms.h"
#include "Ngap_NRintegrityProtectionAlgorithms.h"
#include "Ngap_NRPPa-PDU.h"
#include "Ngap_NumberOfBroadcasts.h"
#include "Ngap_NumberOfBroadcastsRequested.h"
#include "Ngap_OverloadAction.h"
#include "Ngap_OverloadResponse.h"
#include "Ngap_OverloadStart.h"
#include "Ngap_OverloadStartNSSAIItem.h"
#include "Ngap_OverloadStartNSSAIList.h"
#include "Ngap_OverloadStop.h"
#include "Ngap_PacketDelayBudget.h"
#include "Ngap_PacketErrorRate.h"
#include "Ngap_PacketLossRate.h"
#include "Ngap_PagingAttemptCount.h"
#include "Ngap_PagingAttemptInformation.h"
#include "Ngap_PagingDRX.h"
#include "Ngap_Paging.h"
#include "Ngap_PagingOrigin.h"
#include "Ngap_PagingPriority.h"
#include "Ngap_PathSwitchRequestAcknowledge.h"
#include "Ngap_PathSwitchRequestAcknowledgeTransfer.h"
#include "Ngap_PathSwitchRequestFailure.h"
#include "Ngap_PathSwitchRequest.h"
#include "Ngap_PathSwitchRequestSetupFailedTransfer.h"
#include "Ngap_PathSwitchRequestTransfer.h"
#include "Ngap_PathSwitchRequestUnsuccessfulTransfer.h"
#include "Ngap_PDUSessionAggregateMaximumBitRate.h"
#include "Ngap_PDUSessionID.h"
#include "Ngap_PDUSessionResourceAdmittedItem.h"
#include "Ngap_PDUSessionResourceAdmittedList.h"
#include "Ngap_PDUSessionResourceFailedToModifyItemModCfm.h"
#include "Ngap_PDUSessionResourceFailedToModifyItemModRes.h"
#include "Ngap_PDUSessionResourceFailedToModifyListModCfm.h"
#include "Ngap_PDUSessionResourceFailedToModifyListModRes.h"
#include "Ngap_PDUSessionResourceFailedToSetupItemCxtFail.h"
#include "Ngap_PDUSessionResourceFailedToSetupItemCxtRes.h"
#include "Ngap_PDUSessionResourceFailedToSetupItemHOAck.h"
#include "Ngap_PDUSessionResourceFailedToSetupItemPSReq.h"
#include "Ngap_PDUSessionResourceFailedToSetupItemSURes.h"
#include "Ngap_PDUSessionResourceFailedToSetupListCxtFail.h"
#include "Ngap_PDUSessionResourceFailedToSetupListCxtRes.h"
#include "Ngap_PDUSessionResourceFailedToSetupListHOAck.h"
#include "Ngap_PDUSessionResourceFailedToSetupListPSReq.h"
#include "Ngap_PDUSessionResourceFailedToSetupListSURes.h"
#include "Ngap_PDUSessionResourceHandoverItem.h"
#include "Ngap_PDUSessionResourceHandoverList.h"
#include "Ngap_PDUSessionResourceInformationItem.h"
#include "Ngap_PDUSessionResourceInformationList.h"
#include "Ngap_PDUSessionResourceItemCxtRelCpl.h"
#include "Ngap_PDUSessionResourceItemCxtRelReq.h"
#include "Ngap_PDUSessionResourceItemHORqd.h"
#include "Ngap_PDUSessionResourceListCxtRelCpl.h"
#include "Ngap_PDUSessionResourceListCxtRelReq.h"
#include "Ngap_PDUSessionResourceListHORqd.h"
#include "Ngap_PDUSessionResourceModifyConfirm.h"
#include "Ngap_PDUSessionResourceModifyConfirmTransfer.h"
#include "Ngap_PDUSessionResourceModifyIndication.h"
#include "Ngap_PDUSessionResourceModifyIndicationTransfer.h"
#include "Ngap_PDUSessionResourceModifyIndicationUnsuccessfulTransfer.h"
#include "Ngap_PDUSessionResourceModifyItemModCfm.h"
#include "Ngap_PDUSessionResourceModifyItemModInd.h"
#include "Ngap_PDUSessionResourceModifyItemModReq.h"
#include "Ngap_PDUSessionResourceModifyItemModRes.h"
#include "Ngap_PDUSessionResourceModifyListModCfm.h"
#include "Ngap_PDUSessionResourceModifyListModInd.h"
#include "Ngap_PDUSessionResourceModifyListModReq.h"
#include "Ngap_PDUSessionResourceModifyListModRes.h"
#include "Ngap_PDUSessionResourceModifyRequest.h"
#include "Ngap_PDUSessionResourceModifyRequestTransfer.h"
#include "Ngap_PDUSessionResourceModifyResponse.h"
#include "Ngap_PDUSessionResourceModifyResponseTransfer.h"
#include "Ngap_PDUSessionResourceModifyUnsuccessfulTransfer.h"
#include "Ngap_PDUSessionResourceNotify.h"
#include "Ngap_PDUSessionResourceNotifyItem.h"
#include "Ngap_PDUSessionResourceNotifyList.h"
#include "Ngap_PDUSessionResourceNotifyReleasedTransfer.h"
#include "Ngap_PDUSessionResourceNotifyTransfer.h"
#include "Ngap_PDUSessionResourceReleaseCommand.h"
#include "Ngap_PDUSessionResourceReleaseCommandTransfer.h"
#include "Ngap_PDUSessionResourceReleasedItemNot.h"
#include "Ngap_PDUSessionResourceReleasedItemPSAck.h"
#include "Ngap_PDUSessionResourceReleasedItemPSFail.h"
#include "Ngap_PDUSessionResourceReleasedItemRelRes.h"
#include "Ngap_PDUSessionResourceReleasedListNot.h"
#include "Ngap_PDUSessionResourceReleasedListPSAck.h"
#include "Ngap_PDUSessionResourceReleasedListPSFail.h"
#include "Ngap_PDUSessionResourceReleasedListRelRes.h"
#include "Ngap_PDUSessionResourceReleaseResponse.h"
#include "Ngap_PDUSessionResourceReleaseResponseTransfer.h"
#include "Ngap_PDUSessionResourceSecondaryRATUsageItem.h"
#include "Ngap_PDUSessionResourceSecondaryRATUsageList.h"
#include "Ngap_PDUSessionResourceSetupItemCxtReq.h"
#include "Ngap_PDUSessionResourceSetupItemCxtRes.h"
#include "Ngap_PDUSessionResourceSetupItemHOReq.h"
#include "Ngap_PDUSessionResourceSetupItemSUReq.h"
#include "Ngap_PDUSessionResourceSetupItemSURes.h"
#include "Ngap_PDUSessionResourceSetupListCxtReq.h"
#include "Ngap_PDUSessionResourceSetupListCxtRes.h"
#include "Ngap_PDUSessionResourceSetupListHOReq.h"
#include "Ngap_PDUSessionResourceSetupListSUReq.h"
#include "Ngap_PDUSessionResourceSetupListSURes.h"
#include "Ngap_PDUSessionResourceSetupRequest.h"
#include "Ngap_PDUSessionResourceSetupRequestTransfer.h"
#include "Ngap_PDUSessionResourceSetupResponse.h"
#include "Ngap_PDUSessionResourceSetupResponseTransfer.h"
#include "Ngap_PDUSessionResourceSetupUnsuccessfulTransfer.h"
#include "Ngap_PDUSessionResourceSwitchedItem.h"
#include "Ngap_PDUSessionResourceSwitchedList.h"
#include "Ngap_PDUSessionResourceToBeSwitchedDLItem.h"
#include "Ngap_PDUSessionResourceToBeSwitchedDLList.h"
#include "Ngap_PDUSessionResourceToReleaseItemHOCmd.h"
#include "Ngap_PDUSessionResourceToReleaseItemRelCmd.h"
#include "Ngap_PDUSessionResourceToReleaseListHOCmd.h"
#include "Ngap_PDUSessionResourceToReleaseListRelCmd.h"
#include "Ngap_PDUSessionType.h"
#include "Ngap_PDUSessionUsageReport.h"
#include "Ngap_PeriodicRegistrationUpdateTimer.h"
#include "Ngap_PLMNIdentity.h"
#include "Ngap_PLMNSupportItem.h"
#include "Ngap_PLMNSupportList.h"
#include "Ngap_PortNumber.h"
#include "Ngap_Pre-emptionCapability.h"
#include "Ngap_Pre-emptionVulnerability.h"
#include "Ngap_Presence.h"
#include "Ngap_PriorityLevelARP.h"
#include "Ngap_PriorityLevelQos.h"
#include "Ngap_PrivateIE-Container.h"
#include "Ngap_PrivateIE-Field.h"
#include "Ngap_PrivateIE-ID.h"
#include "Ngap_PrivateMessage.h"
#include "Ngap_ProcedureCode.h"
#include "Ngap_ProtocolExtensionContainer.h"
#include "Ngap_ProtocolExtensionField.h"
#include "Ngap_ProtocolExtensionID.h"
#include "Ngap_ProtocolIE-Container.h"
#include "Ngap_ProtocolIE-ContainerList.h"
#include "Ngap_ProtocolIE-ContainerPair.h"
#include "Ngap_ProtocolIE-ContainerPairList.h"
#include "Ngap_ProtocolIE-Field.h"
#include "Ngap_ProtocolIE-FieldPair.h"
#include "Ngap_ProtocolIE-ID.h"
#include "Ngap_ProtocolIE-SingleContainer.h"
#include "Ngap_PWSCancelRequest.h"
#include "Ngap_PWSCancelResponse.h"
#include "Ngap_PWSFailedCellIDList.h"
#include "Ngap_PWSFailureIndication.h"
#include "Ngap_PWSRestartIndication.h"
#include "Ngap_QosCharacteristics.h"
#include "Ngap_QosFlowAcceptedItem.h"
#include "Ngap_QosFlowAcceptedList.h"
#include "Ngap_QosFlowAddOrModifyRequestItem.h"
#include "Ngap_QosFlowAddOrModifyRequestList.h"
#include "Ngap_QosFlowAddOrModifyResponseItem.h"
#include "Ngap_QosFlowAddOrModifyResponseList.h"
#include "Ngap_QosFlowIdentifier.h"
#include "Ngap_QosFlowInformationItem.h"
#include "Ngap_QosFlowInformationList.h"
#include "Ngap_QosFlowItemWithDataForwarding.h"
#include "Ngap_QosFlowLevelQosParameters.h"
#include "Ngap_QosFlowListWithCause.h"
#include "Ngap_QosFlowListWithDataForwarding.h"
#include "Ngap_QosFlowModifyConfirmItem.h"
#include "Ngap_QosFlowModifyConfirmList.h"
#include "Ngap_QosFlowNotifyItem.h"
#include "Ngap_QosFlowNotifyList.h"
#include "Ngap_QosFlowPerTNLInformation.h"
#include "Ngap_QosFlowPerTNLInformationItem.h"
#include "Ngap_QosFlowPerTNLInformationList.h"
#include "Ngap_QosFlowSetupRequestItem.h"
#include "Ngap_QosFlowSetupRequestList.h"
#include "Ngap_QosFlowSetupResponseItemSURes.h"
#include "Ngap_QosFlowSetupResponseListSURes.h"
#include "Ngap_QoSFlowsUsageReport-Item.h"
#include "Ngap_QoSFlowsUsageReportList.h"
#include "Ngap_QosFlowToBeForwardedItem.h"
#include "Ngap_QosFlowToBeForwardedList.h"
#include "Ngap_QosFlowWithCauseItem.h"
#include "Ngap_RANConfigurationUpdateAcknowledge.h"
#include "Ngap_RANConfigurationUpdateFailure.h"
#include "Ngap_RANConfigurationUpdate.h"
#include "Ngap_RANNodeName.h"
#include "Ngap_RANPagingPriority.h"
#include "Ngap_RANStatusTransfer-TransparentContainer.h"
#include "Ngap_RAN-UE-NGAP-ID.h"
#include "Ngap_RATRestrictionInformation.h"
#include "Ngap_RATRestrictions.h"
#include "Ngap_RATRestrictions-Item.h"
#include "Ngap_RecommendedCellItem.h"
#include "Ngap_RecommendedCellList.h"
#include "Ngap_RecommendedCellsForPaging.h"
#include "Ngap_RecommendedRANNodeItem.h"
#include "Ngap_RecommendedRANNodeList.h"
#include "Ngap_RecommendedRANNodesForPaging.h"
#include "Ngap_RedirectionVoiceFallback.h"
#include "Ngap_ReferenceID.h"
#include "Ngap_ReflectiveQosAttribute.h"
#include "Ngap_RejectedNSSAIinPLMN.h"
#include "Ngap_RejectedNSSAIinTA.h"
#include "Ngap_RelativeAMFCapacity.h"
#include "Ngap_RepetitionPeriod.h"
#include "Ngap_ReportArea.h"
#include "Ngap_RerouteNASRequest.h"
#include "Ngap_ResetAll.h"
#include "Ngap_ResetType.h"
#include "Ngap_RIMInformation.h"
#include "Ngap_RIMInformationTransfer.h"
#include "Ngap_RoutingID.h"
#include "Ngap_RRCContainer.h"
#include "Ngap_RRCEstablishmentCause.h"
#include "Ngap_RRCInactiveTransitionReport.h"
#include "Ngap_RRCInactiveTransitionReportRequest.h"
#include "Ngap_RRCState.h"
#include "Ngap_SCTP-TLAs.h"
#include "Ngap_SD.h"
#include "Ngap_SecondaryRATDataUsageReport.h"
#include "Ngap_SecondaryRATDataUsageReportTransfer.h"
#include "Ngap_SecondaryRATUsageInformation.h"
#include "Ngap_SecurityContext.h"
#include "Ngap_SecurityIndication.h"
#include "Ngap_SecurityKey.h"
#include "Ngap_SecurityResult.h"
#include "Ngap_SerialNumber.h"
#include "Ngap_ServedGUAMIItem.h"
#include "Ngap_ServedGUAMIList.h"
#include "Ngap_ServiceAreaInformation.h"
#include "Ngap_ServiceAreaInformation-Item.h"
#include "Ngap_SliceOverloadItem.h"
#include "Ngap_SliceOverloadList.h"
#include "Ngap_SliceSupportItem.h"
#include "Ngap_SliceSupportList.h"
#include "Ngap_S-NSSAI.h"
#include "Ngap_SONConfigurationTransfer.h"
#include "Ngap_SONInformation.h"
#include "Ngap_SONInformationReply.h"
#include "Ngap_SONInformationRequest.h"
#include "Ngap_SourceNGRANNode-ToTargetNGRANNode-TransparentContainer.h"
#include "Ngap_SourceOfUEActivityBehaviourInformation.h"
#include "Ngap_SourceRANNodeID.h"
#include "Ngap_SourceToTarget-AMFInformationReroute.h"
#include "Ngap_SourceToTarget-TransparentContainer.h"
#include "Ngap_SST.h"
#include "Ngap_SuccessfulOutcome.h"
#include "Ngap_SupportedTAItem.h"
#include "Ngap_SupportedTAList.h"
#include "Ngap_TAC.h"
#include "Ngap_TAIBroadcastEUTRA.h"
#include "Ngap_TAIBroadcastEUTRA-Item.h"
#include "Ngap_TAIBroadcastNR.h"
#include "Ngap_TAIBroadcastNR-Item.h"
#include "Ngap_TAICancelledEUTRA.h"
#include "Ngap_TAICancelledEUTRA-Item.h"
#include "Ngap_TAICancelledNR.h"
#include "Ngap_TAICancelledNR-Item.h"
#include "Ngap_TAI.h"
#include "Ngap_TAIListForInactive.h"
#include "Ngap_TAIListForInactiveItem.h"
#include "Ngap_TAIListForPaging.h"
#include "Ngap_TAIListForPagingItem.h"
#include "Ngap_TAIListForRestart.h"
#include "Ngap_TAIListForWarning.h"
#include "Ngap_TargeteNB-ID.h"
#include "Ngap_TargetID.h"
#include "Ngap_TargetNGRANNode-ToSourceNGRANNode-TransparentContainer.h"
#include "Ngap_TargetRANNodeID.h"
#include "Ngap_TargetToSource-TransparentContainer.h"
#include "Ngap_TimerApproachForGUAMIRemoval.h"
#include "Ngap_TimeStamp.h"
#include "Ngap_TimeToWait.h"
#include "Ngap_TimeUEStayedInCellEnhancedGranularity.h"
#include "Ngap_TimeUEStayedInCell.h"
#include "Ngap_TNLAddressWeightFactor.h"
#include "Ngap_TNLAssociationItem.h"
#include "Ngap_TNLAssociationList.h"
#include "Ngap_TNLAssociationUsage.h"
#include "Ngap_TraceActivation.h"
#include "Ngap_TraceDepth.h"
#include "Ngap_TraceFailureIndication.h"
#include "Ngap_TraceStart.h"
#include "Ngap_TrafficLoadReductionIndication.h"
#include "Ngap_TransportLayerAddress.h"
#include "Ngap_TriggeringMessage.h"
#include "Ngap_TypeOfError.h"
#include "Ngap_UEAggregateMaximumBitRate.h"
#include "Ngap_UE-associatedLogicalNG-connectionItem.h"
#include "Ngap_UE-associatedLogicalNG-connectionList.h"
#include "Ngap_UEContextModificationFailure.h"
#include "Ngap_UEContextModificationRequest.h"
#include "Ngap_UEContextModificationResponse.h"
#include "Ngap_UEContextReleaseCommand.h"
#include "Ngap_UEContextReleaseComplete.h"
#include "Ngap_UEContextReleaseRequest.h"
#include "Ngap_UEContextRequest.h"
#include "Ngap_UEHistoryInformation.h"
#include "Ngap_UEIdentityIndexValue.h"
#include "Ngap_UE-NGAP-ID-pair.h"
#include "Ngap_UE-NGAP-IDs.h"
#include "Ngap_UEPagingIdentity.h"
#include "Ngap_UEPresence.h"
#include "Ngap_UEPresenceInAreaOfInterestItem.h"
#include "Ngap_UEPresenceInAreaOfInterestList.h"
#include "Ngap_UERadioCapabilityCheckRequest.h"
#include "Ngap_UERadioCapabilityCheckResponse.h"
#include "Ngap_UERadioCapabilityForPaging.h"
#include "Ngap_UERadioCapabilityForPagingOfEUTRA.h"
#include "Ngap_UERadioCapabilityForPagingOfNR.h"
#include "Ngap_UERadioCapability.h"
#include "Ngap_UERadioCapabilityInfoIndication.h"
#include "Ngap_UERetentionInformation.h"
#include "Ngap_UESecurityCapabilities.h"
#include "Ngap_UETNLABindingReleaseRequest.h"
#include "Ngap_ULForwarding.h"
#include "Ngap_UL-NGU-UP-TNLModifyItem.h"
#include "Ngap_UL-NGU-UP-TNLModifyList.h"
#include "Ngap_UnavailableGUAMIItem.h"
#include "Ngap_UnavailableGUAMIList.h"
#include "Ngap_UnsuccessfulOutcome.h"
#include "Ngap_UplinkNASTransport.h"
#include "Ngap_UplinkNonUEAssociatedNRPPaTransport.h"
#include "Ngap_UplinkRANConfigurationTransfer.h"
#include "Ngap_UplinkRANStatusTransfer.h"
#include "Ngap_UplinkRIMInformationTransfer.h"
#include "Ngap_UplinkUEAssociatedNRPPaTransport.h"
#include "Ngap_UPTransportLayerInformation.h"
#include "Ngap_UPTransportLayerInformationItem.h"
#include "Ngap_UPTransportLayerInformationList.h"
#include "Ngap_UPTransportLayerInformationPairItem.h"
#include "Ngap_UPTransportLayerInformationPairList.h"
#include "Ngap_UserLocationInformationEUTRA.h"
#include "Ngap_UserLocationInformation.h"
#include "Ngap_UserLocationInformationN3IWF.h"
#include "Ngap_UserLocationInformationNR.h"
#include "Ngap_UserPlaneSecurityInformation.h"
#include "Ngap_VolumeTimedReport-Item.h"
#include "Ngap_VolumeTimedReportList.h"
#include "Ngap_WarningAreaCoordinates.h"
#include "Ngap_WarningAreaList.h"
#include "Ngap_WarningMessageContents.h"
#include "Ngap_WarningSecurityInfo.h"
#include "Ngap_WarningType.h"
#include "Ngap_WriteReplaceWarningRequest.h"
#include "Ngap_WriteReplaceWarningResponse.h"
#include "Ngap_XnExtTLA-Item.h"
#include "Ngap_XnExtTLAs.h"
#include "Ngap_XnGTP-TLAs.h"
#include "Ngap_XnTLAs.h"
#include "Ngap_XnTNLConfigurationInfo.h"
#include "OBJECT_IDENTIFIER.h"
#include "OCTET_STRING.h"
#include "oer_decoder.h"
#include "oer_encoder.h"
#include "oer_support.h"
#include "OPEN_TYPE.h"
#include "per_decoder.h"
#include "per_encoder.h"
#include "per_opentype.h"
#include "per_support.h"
#include "PrintableString.h"
#include "xer_decoder.h"
#include "xer_encoder.h"
#include "xer_support.h"

#include <stdbool.h>

#include "amf_default_values.h"
#include "common_defs.h"
#include "3gpp_23.003.h"
#include "3gpp_24.008.h"
#include "3gpp_33.401.h"
#include "3gpp_38.401.h"
#include "security_types.h"
#include "common_types.h"
#include "ngap_messages_types.h"
#include "bstrlib.h"
//#include "ngap_state.h"
#include "ngap_types.h"

// Forward declaration
struct ngap_message_s;
#define NGAP_FIND_PROTOCOLIE_BY_ID(                                            \
    IE_TYPE, initialContextSetupResponseIEs_p, container, IE_ID, mandatory)    \
  do {                                                                         \
    IE_TYPE** ptr;                                                             \
    initialContextSetupResponseIEs_p = NULL;                                   \
    for (ptr = container->protocolIEs.list.array;                              \
         ptr < &container->protocolIEs.list                                    \
                    .array[container->protocolIEs.list.count];                 \
         ptr++) {                                                              \
      if ((*ptr)->id == IE_ID) {                                               \
        initialContextSetupResponseIEs_p = *ptr;                               \
        break;                                                                 \
      }                                                                        \
    }                                                                          \
    if (initialContextSetupResponseIEs_p == NULL) {                            \
      if (mandatory)                                                           \
        OAILOG_ERROR(                                                          \
            LOG_NGAP,                                                          \
            "NGAP_FIND_PROTOCOLIE_BY_ID: %s %d: Mandatory ie is NULL\n",       \
            __FILE__, __LINE__);                                               \
      else                                                                     \
        OAILOG_DEBUG(                                                          \
            LOG_NGAP,                                                          \
            "NGAP_FIND_PROTOCOLIE_BY_ID: %s %d: Optional ie is NULL\n",        \
            __FILE__, __LINE__);                                               \
    }                                                                          \
    if (mandatory) DevAssert(ie != NULL);                                      \
  } while (0)

/** \brief Function callback prototype.
 **/
typedef int (*ngap_message_handler_t)(
    ngap_state_t* state, const sctp_assoc_id_t assoc_id,
    const sctp_stream_id_t stream, Ngap_NGAP_PDU_t* pdu);

/** \brief Encode a successful outcome message
 \param buffer pointer to buffer in which data will be encoded
 \param length pointer to the length of buffer
 \param procedureCode Procedure code for the message
 \param criticality Criticality of the message
 \param td ASN1C type descriptor of the sptr
 \param sptr Dereferenced pointer to the structure to encode
 @returns size in bytes encded on success or 0 on failure
 **/

ssize_t ngap_generate_successful_outcome(
    uint8_t** buffer, uint32_t* length, Ngap_ProcedureCode_t procedureCode,
    Ngap_Criticality_t criticality, asn_TYPE_descriptor_t* td, void* sptr);

/** \brief Encode an initiating message
 \param buffer pointer to buffer in which data will be encoded
 \param length pointer to the length of buffer
 \param procedureCode Procedure code for the message
 \param criticality Criticality of the message
 \param td ASN1C type descriptor of the sptr
 \param sptr Dereferenced pointer to the structure to encode
 @returns size in bytes encded on success or 0 on failure
 **/

ssize_t ngap_generate_initiating_message(
    uint8_t** buffer, uint32_t* length, Ngap_ProcedureCode_t procedureCode,
    Ngap_Criticality_t criticality, asn_TYPE_descriptor_t* td, void* sptr);

/** \brief Encode an unsuccessful outcome message
 \param buffer pointer to buffer in which data will be encoded
 \param length pointer to the length of buffer
 \param procedureCode Procedure code for the message
 \param criticality Criticality of the message
 \param td ASN1C type descriptor of the sptr
 \param sptr Dereferenced pointer to the structure to encode
 @returns size in bytes encded on success or 0 on failure
 **/
ssize_t ngap_generate_unsuccessful_outcome(
    uint8_t** buffer, uint32_t* length, Ngap_ProcedureCode_t procedureCode,
    Ngap_Criticality_t criticality, asn_TYPE_descriptor_t* td, void* sptr);

/** \brief Handle criticality
 \param criticality Criticality of the IE
 @returns void
 **/
void ngap_handle_criticality(Ngap_Criticality_t criticality);
